export const translations = {
  EN: {
    yourDay: "Your Day",
    goodMorning: "Good morning,",
    timeline: "TIMELINE",
    noEvents: "No events today",
    clearDay: "Clear day — enjoy it.",
    workout: "Workout",
    todaysPlan: "TODAY'S PLAN",
    setReminder: "Set reminder",
    workoutIn: "Workout in 15 minutes",
    settings: "Profile",
    syncNow: "Sync Now",
    disconnect: "Disconnect",
    signOut: "Sign Out",
    pushNotifications: "Push Notifications",
    workoutReminders: "Workout reminders",
    version: "Version",
    stats: "STATS",
    calendar: "CALENDAR",
    preferences: "PREFERENCES",
    googleConnected: "Google Calendar connected",
    readOnly: "Read only",
    schedule: "Schedule",

    synced: "Synced",
    welcomeBack: "Welcome back",
    signInContinue: "Sign in to continue",
    email: "EMAIL",
    password: "PASSWORD",
    signIn: "Sign In",
    orContinueWith: "or continue with",
    continueGoogle: "Continue with Google",
    noAccount: "Don't have an account?",
    signUp: "Sign Up",
    connect: "Connect",
    cancel: "Cancel",
    restDay: "Rest Day",
    restBody: "Rest is when your body rebuilds. Light walk recommended.",
    saveToSchedule: "Save to Schedule",
    savedToSchedule: "Saved to schedule!",
    reminder: "REMINDER",
    reminderSet: "Reminder set",
    fitSched: "FitSched",
    connectCalendar: "Connect Calendar",
    syncDescription: "Read-only sync to find workout windows.",
    signInWithGoogle: "Sign in with Google",
    syncing: "Syncing...",
    connecting: "Connecting...",
    autoScheduled: "Auto-scheduled",
    avgWorkout: "Avg workout",
    decisions: "Decisions",
    days: "Days",
    tagline: "Your schedule. Your pace.",
    startJourney: "Start your journey.",
    createAccount: "Create account",
    itsFree: "It's free, always.",
    hasAccount: "Already have an account?",
    exercises: "Exercises",
    add: "Add",
    searchExercises: "Search exercises...",
    all: "All",
    defaultLabel: "Default",
    noExercises: "No exercises found",
    addExercise: "Add Exercise",
    name: "Name",
    description: "Description",
    optionalDescription: "Optional description",
    muscle: "Muscle",
    equipment: "Equipment",
    difficulty: "Difficulty",
    exerciseName: "Exercise name",
    progress: "Progress",
    trackJourney: "Track your workout journey",
    overview: "Overview",
    charts: "Charts",
    totalWorkouts: "Total Workouts",
    totalSets: "Total Sets",
    avgRating: "Avg Rating",
    thisWeek: "This Week",
    recentActivity: "Recent Activity",
    noWorkouts: "No workouts logged yet",
    currentStreak: "Current Streak",
    totalExercises: "Total Exercises",
    last8Weeks: "Last 8 Weeks",
    mostTrained: "Most Trained",
    setsPerSession: "Sets per Session",
    noData: "No data yet",
    ratingTrend: "Rating Trend",
    language: "Language",
    workoutLabel: "WORKOUT",
    addSchedule: "Add schedule",
    editSchedule: "Edit schedule",
    addToSchedule: "Add to schedule",
    saveChanges: "Save changes",
    adding: "Adding...",
    saving: "Saving...",
    manual: "Manual",
    edit: "Edit",
    delete: "Delete",
    deleting: "...",
    goExercise: "Go Exercise",
    exercisesCount: "exercises",
    title: "TITLE",
    time: "TIME",
    optionalNotes: "Optional notes",
    classWorkAppointment: "Class, work, appointment...",
    workoutLockedTitle: "Workout locked for this day",
    workoutLockedBody: "You already completed this workout, so FitTokens are protected until the next workout day.",
    checkingWorkout: "CHECKING WORKOUT",
    workoutAlreadyComplete: "Workout already complete",
    workoutAlreadyCompleteBody: "This day is locked so FitTokens stay fair. Come back for the next workout day.",
    noWorkoutLoaded: "No workout loaded",
    noWorkoutLoadedBody: "Start from the Workout tab to begin an exercise session.",
    backToWorkout: "Back to Workout",
    back: "Back",
    exercisesDone: "EXERCISES DONE",
    restTime: "Rest time",
    nowTraining: "Now training",
    resting: "Resting...",
    pauseTimer: "Pause Timer",
    resumeTimer: "Resume Timer",
    exerciseLabel: "EXERCISE",
    setLabel: "SET",
    ofLabel: "OF",
    repsThisSet: "reps this set",
    setsDone: "sets done",
    skipRest: "Skip Rest",
    doneSet: "Done Set",
    finishWorkout: "Finish Workout",
    workoutCompleteTitle: "Workout complete",
    workoutCompleteBody: "You showed up today. Keep this rhythm going.",
    streakLabel: "STREAK",
    dayStreak: "day streak",
    receiveFitToken: "RECEIVE FITTOKEN",
    continueLabel: "Continue",
  },
  CN: {
    yourDay: "你的一天",
    goodMorning: "早上好，",
    timeline: "时间线",
    noEvents: "今天没有活动",
    clearDay: "轻松的一天 — 好好享受。",
    workout: "锻炼",
    todaysPlan: "今日计划",
    setReminder: "设置提醒",
    workoutIn: "15分钟后锻炼",
    settings: "设置",
    syncNow: "立即同步",
    disconnect: "断开连接",
    signOut: "退出登录",
    pushNotifications: "推送通知",
    workoutReminders: "锻炼提醒",
    version: "版本",
    stats: "统计",
    calendar: "日历",
    preferences: "偏好设置",
    googleConnected: "Google日历已连接",
    readOnly: "只读",
    schedule: "日程",

    synced: "已同步",
    welcomeBack: "欢迎回来",
    signInContinue: "登录以继续",
    email: "邮箱",
    password: "密码",
    signIn: "登录",
    orContinueWith: "或继续使用",
    continueGoogle: "使用Google继续",
    noAccount: "没有账号？",
    signUp: "注册",
    connect: "连接",
    cancel: "取消",
    restDay: "休息日",
    restBody: "休息是身体重建的时候。建议轻度散步。",
    saveToSchedule: "保存到日程",
    savedToSchedule: "已保存到日程！",
    reminder: "提醒",
    reminderSet: "已设置提醒",
    fitSched: "FitSched",
    connectCalendar: "连接日历",
    syncDescription: "只读同步以查找锻炼窗口。",
    signInWithGoogle: "使用Google登录",
    syncing: "同步中...",
    connecting: "连接中...",
    autoScheduled: "自动安排",
    avgWorkout: "平均锻炼",
    decisions: "决策",
    days: "天",
    tagline: "你的日程。你的节奏。",
    startJourney: "开始你的旅程。",
    createAccount: "创建账户",
    itsFree: "永久免费。",
    hasAccount: "已有账号？",
    exercises: "动作库",
    add: "添加",
    searchExercises: "搜索动作...",
    all: "全部",
    defaultLabel: "默认",
    noExercises: "未找到动作",
    addExercise: "添加动作",
    name: "名称",
    description: "描述",
    optionalDescription: "可选描述",
    muscle: "肌肉",
    equipment: "器材",
    difficulty: "难度",
    exerciseName: "动作名称",
    progress: "进度",
    trackJourney: "跟踪你的锻炼旅程",
    overview: "概览",
    charts: "图表",
    totalWorkouts: "总锻炼",
    totalSets: "总组数",
    avgRating: "平均评分",
    thisWeek: "本周",
    recentActivity: "最近活动",
    noWorkouts: "尚无锻炼记录",
    currentStreak: "当前连续",
    totalExercises: "总动作数",
    last8Weeks: "最近8周",
    mostTrained: "最常训练",
    setsPerSession: "每组组数",
    noData: "暂无数据",
    ratingTrend: "评分趋势",
    language: "语言",
    workoutLabel: "锻炼",
    addSchedule: "添加日程",
    editSchedule: "编辑日程",
    addToSchedule: "添加到日程",
    saveChanges: "保存更改",
    adding: "添加中...",
    saving: "保存中...",
    manual: "手动",
    edit: "编辑",
    delete: "删除",
    deleting: "...",
    goExercise: "开始锻炼",
    exercisesCount: "个动作",
    title: "标题",
    time: "时间",
    optionalNotes: "可选备注",
    classWorkAppointment: "课程、工作、约会...",
    workoutLockedTitle: "今天的锻炼已锁定",
    workoutLockedBody: "你已经完成了这次锻炼，所以 FitToken 会保护到下一个锻炼日。",
    checkingWorkout: "正在检查锻炼",
    workoutAlreadyComplete: "锻炼已完成",
    workoutAlreadyCompleteBody: "这一天已锁定，确保 FitToken 公平。下一个锻炼日再回来吧。",
    noWorkoutLoaded: "没有载入锻炼",
    noWorkoutLoadedBody: "请从“锻炼”页面开始一次训练。",
    backToWorkout: "返回锻炼",
    back: "返回",
    exercisesDone: "个动作已完成",
    restTime: "休息时间",
    nowTraining: "正在训练",
    resting: "休息中...",
    pauseTimer: "暂停计时",
    resumeTimer: "继续计时",
    exerciseLabel: "动作",
    setLabel: "组",
    ofLabel: "共",
    repsThisSet: "次本组",
    setsDone: "组已完成",
    skipRest: "跳过休息",
    doneSet: "完成本组",
    finishWorkout: "完成锻炼",
    workoutCompleteTitle: "锻炼完成",
    workoutCompleteBody: "你今天坚持了。继续保持这个节奏。",
    streakLabel: "连续",
    dayStreak: "天连续",
    receiveFitToken: "领取 FITTOKEN",
    continueLabel: "继续",
  },
  JP: {
    yourDay: "今日の予定",
    goodMorning: "おはようございます、",
    timeline: "タイムライン",
    noEvents: "今日の予定はありません",
    clearDay: "予定なし — ゆっくり過ごしてください。",
    workout: "ワークアウト",
    todaysPlan: "今日のプラン",
    setReminder: "リマインダーを設定",
    workoutIn: "15分後にワークアウト",
    settings: "設定",
    syncNow: "今すぐ同期",
    disconnect: "切断",
    signOut: "サインアウト",
    pushNotifications: "プッシュ通知",
    workoutReminders: "ワークアウトリマインダー",
    version: "バージョン",
    stats: "統計",
    calendar: "カレンダー",
    preferences: "設定",
    googleConnected: "Googleカレンダー接続済み",
    readOnly: "読み取り専用",
    schedule: "スケジュール",

    synced: "同期済み",
    welcomeBack: "おかえりなさい",
    signInContinue: "続けるにはサインインしてください",
    email: "メール",
    password: "パスワード",
    signIn: "サインイン",
    orContinueWith: "または続ける",
    continueGoogle: "Googleで続ける",
    noAccount: "アカウントをお持ちでないですか？",
    signUp: "登録",
    connect: "接続",
    cancel: "キャンセル",
    restDay: "休息日",
    restBody: "休息は体が回復する時間です。軽い散歩をおすすめします。",
    saveToSchedule: "スケジュールに保存",
    savedToSchedule: "スケジュールに保存しました！",
    reminder: "リマインダー",
    reminderSet: "リマインダー設定済み",
    fitSched: "FitSched",
    connectCalendar: "カレンダーを接続",
    syncDescription: "ワークアウトの時間帯を見つけるための読み取り専用同期。",
    signInWithGoogle: "Googleでサインイン",
    syncing: "同期中...",
    connecting: "接続中...",
    autoScheduled: "自動スケジュール",
    avgWorkout: "平均ワークアウト",
    decisions: "決定",
    days: "日",
    tagline: "あなたのスケジュール。あなたのペース。",
    startJourney: "旅を始めましょう。",
    createAccount: "アカウント作成",
    itsFree: "いつでも無料です。",
    hasAccount: "すでにアカウントをお持ちですか？",
    exercises: "エクササイズ",
    add: "追加",
    searchExercises: "エクササイズを検索...",
    all: "すべて",
    defaultLabel: "デフォルト",
    noExercises: "エクササイズが見つかりません",
    addExercise: "エクササイズを追加",
    name: "名前",
    description: "説明",
    optionalDescription: "任意の説明",
    muscle: "筋肉",
    equipment: "器具",
    difficulty: "難易度",
    exerciseName: "エクササイズ名",
    progress: "進捗",
    trackJourney: "ワークアウトの旅を記録",
    overview: "概要",
    charts: "チャート",
    totalWorkouts: "総ワークアウト",
    totalSets: "総セット数",
    avgRating: "平均評価",
    thisWeek: "今週",
    recentActivity: "最近の活動",
    noWorkouts: "まだワークアウトが記録されていません",
    currentStreak: "現在の連続",
    totalExercises: "総エクササイズ数",
    last8Weeks: "最近8週間",
    mostTrained: "最も鍛えた部位",
    setsPerSession: "セッションあたりのセット数",
    noData: "データがまだありません",
    ratingTrend: "評価の傾向",
    language: "言語",
    workoutLabel: "ワークアウト",
    addSchedule: "予定を追加",
    editSchedule: "予定を編集",
    addToSchedule: "予定に追加",
    saveChanges: "変更を保存",
    adding: "追加中...",
    saving: "保存中...",
    manual: "手動",
    edit: "編集",
    delete: "削除",
    deleting: "...",
    goExercise: "運動を開始",
    exercisesCount: "種目",
    title: "タイトル",
    time: "時間",
    optionalNotes: "任意のメモ",
    classWorkAppointment: "授業、仕事、予定...",
    workoutLockedTitle: "この日のワークアウトはロック済み",
    workoutLockedBody: "このワークアウトは完了済みのため、次のワークアウト日までFitTokenを保護します。",
    checkingWorkout: "ワークアウトを確認中",
    workoutAlreadyComplete: "ワークアウトは完了済み",
    workoutAlreadyCompleteBody: "FitTokenの公平性を守るため、この日はロックされています。次のワークアウト日に戻ってきてください。",
    noWorkoutLoaded: "ワークアウトが読み込まれていません",
    noWorkoutLoadedBody: "ワークアウトタブから運動セッションを開始してください。",
    backToWorkout: "ワークアウトへ戻る",
    back: "戻る",
    exercisesDone: "種目完了",
    restTime: "休憩時間",
    nowTraining: "トレーニング中",
    resting: "休憩中...",
    pauseTimer: "タイマーを一時停止",
    resumeTimer: "タイマーを再開",
    exerciseLabel: "種目",
    setLabel: "セット",
    ofLabel: "中",
    repsThisSet: "回このセット",
    setsDone: "セット完了",
    skipRest: "休憩をスキップ",
    doneSet: "セット完了",
    finishWorkout: "ワークアウトを完了",
    workoutCompleteTitle: "ワークアウト完了",
    workoutCompleteBody: "今日もやり切りました。このリズムを続けましょう。",
    streakLabel: "連続",
    dayStreak: "日連続",
    receiveFitToken: "FITTOKENを受け取る",
    continueLabel: "続ける",
  },
  VI: {
    yourDay: "Ngày của bạn",
    goodMorning: "Chào buổi sáng,",
    timeline: "THỜI GIAN BIỂU",
    noEvents: "Không có sự kiện hôm nay",
    clearDay: "Ngày trống — hãy tận hưởng.",
    workout: "Tập luyện",
    todaysPlan: "KẾ HOẠCH HÔM NAY",
    setReminder: "Đặt nhắc nhở",
    workoutIn: "Tập luyện sau 15 phút",
    settings: "Cài đặt",
    syncNow: "Đồng bộ ngay",
    disconnect: "Ngắt kết nối",
    signOut: "Đăng xuất",
    pushNotifications: "Thông báo đẩy",
    workoutReminders: "Nhắc nhở tập luyện",
    version: "Phiên bản",
    stats: "THỐNG KÊ",
    calendar: "LỊCH",
    preferences: "TÙY CHỌN",
    googleConnected: "Google Calendar đã kết nối",
    readOnly: "Chỉ đọc",
    schedule: "Lịch trình",

    synced: "Đã đồng bộ",
    welcomeBack: "Chào mừng trở lại",
    signInContinue: "Đăng nhập để tiếp tục",
    email: "EMAIL",
    password: "MẬT KHẨU",
    signIn: "Đăng nhập",
    orContinueWith: "hoặc tiếp tục với",
    continueGoogle: "Tiếp tục với Google",
    noAccount: "Chưa có tài khoản?",
    signUp: "Đăng ký",
    connect: "Kết nối",
    cancel: "Hủy",
    restDay: "Ngày nghỉ",
    restBody: "Nghỉ ngơi là lúc cơ thể phục hồi. Đi bộ nhẹ được khuyến khích.",
    saveToSchedule: "Lưu vào Lịch trình",
    savedToSchedule: "Đã lưu vào lịch trình!",
    reminder: "NHẮC NHỞ",
    reminderSet: "Đã đặt nhắc nhở",
    fitSched: "FitSched",
    connectCalendar: "Kết nối Lịch",
    syncDescription: "Đồng bộ chỉ đọc để tìm khung giờ tập luyện.",
    signInWithGoogle: "Đăng nhập bằng Google",
    syncing: "Đang đồng bộ...",
    connecting: "Đang kết nối...",
    autoScheduled: "Tự động lên lịch",
    avgWorkout: "TB tập luyện",
    decisions: "Quyết định",
    days: "Ngày",
    tagline: "Lịch trình của bạn. Nhịp độ của bạn.",
    startJourney: "Bắt đầu hành trình của bạn.",
    createAccount: "Tạo tài khoản",
    itsFree: "Hoàn toàn miễn phí.",
    hasAccount: "Đã có tài khoản?",
    exercises: "Bài tập",
    add: "Thêm",
    searchExercises: "Tìm kiếm bài tập...",
    all: "Tất cả",
    defaultLabel: "Mặc định",
    noExercises: "Không tìm thấy bài tập",
    addExercise: "Thêm bài tập",
    name: "Tên",
    description: "Mô tả",
    optionalDescription: "Mô tả tùy chọn",
    muscle: "Cơ",
    equipment: "Thiết bị",
    difficulty: "Độ khó",
    exerciseName: "Tên bài tập",
    progress: "Tiến độ",
    trackJourney: "Theo dõi hành trình tập luyện của bạn",
    overview: "Tổng quan",
    charts: "Biểu đồ",
    totalWorkouts: "Tổng số buổi tập",
    totalSets: "Tổng số hiệp",
    avgRating: "Đánh giá TB",
    thisWeek: "Tuần này",
    recentActivity: "Hoạt động gần đây",
    noWorkouts: "Chưa có buổi tập nào",
    currentStreak: "Chuỗi hiện tại",
    totalExercises: "Tổng bài tập",
    last8Weeks: "8 tuần qua",
    mostTrained: "Nhóm cơ tập nhiều nhất",
    setsPerSession: "Số hiệp mỗi buổi",
    noData: "Chưa có dữ liệu",
    ratingTrend: "Xu hướng đánh giá",
    language: "Ngôn ngữ",
    workoutLabel: "TẬP LUYỆN",
    addSchedule: "Thêm lịch",
    editSchedule: "Sửa lịch",
    addToSchedule: "Thêm vào lịch",
    saveChanges: "Lưu thay đổi",
    adding: "Đang thêm...",
    saving: "Đang lưu...",
    manual: "Thủ công",
    edit: "Sửa",
    delete: "Xóa",
    deleting: "...",
    goExercise: "Bắt đầu tập",
    exercisesCount: "bài tập",
    title: "TIÊU ĐỀ",
    time: "THỜI GIAN",
    optionalNotes: "Ghi chú tùy chọn",
    classWorkAppointment: "Lớp học, công việc, cuộc hẹn...",
    workoutLockedTitle: "Bài tập hôm nay đã khóa",
    workoutLockedBody: "Bạn đã hoàn thành bài tập này, nên FitTokens được bảo vệ đến ngày tập tiếp theo.",
    checkingWorkout: "ĐANG KIỂM TRA BÀI TẬP",
    workoutAlreadyComplete: "Bài tập đã hoàn thành",
    workoutAlreadyCompleteBody: "Ngày này đã khóa để giữ FitTokens công bằng. Hãy quay lại vào ngày tập tiếp theo.",
    noWorkoutLoaded: "Chưa tải bài tập",
    noWorkoutLoadedBody: "Bắt đầu từ tab Tập luyện để vào buổi tập.",
    backToWorkout: "Quay lại Tập luyện",
    back: "Quay lại",
    exercisesDone: "BÀI TẬP ĐÃ XONG",
    restTime: "Thời gian nghỉ",
    nowTraining: "Đang tập",
    resting: "Đang nghỉ...",
    pauseTimer: "Tạm dừng giờ",
    resumeTimer: "Tiếp tục giờ",
    exerciseLabel: "BÀI TẬP",
    setLabel: "HIỆP",
    ofLabel: "TRÊN",
    repsThisSet: "lần hiệp này",
    setsDone: "hiệp đã xong",
    skipRest: "Bỏ qua nghỉ",
    doneSet: "Xong hiệp",
    finishWorkout: "Hoàn thành bài tập",
    workoutCompleteTitle: "Hoàn thành bài tập",
    workoutCompleteBody: "Hôm nay bạn đã xuất hiện. Hãy giữ nhịp này.",
    streakLabel: "CHUỖI",
    dayStreak: "ngày liên tiếp",
    receiveFitToken: "NHẬN FITTOKEN",
    continueLabel: "Tiếp tục",
  },
} as const

export type Language = keyof typeof translations
export type TranslationKey = keyof typeof translations.EN

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: "EN", label: "EN" },
  { code: "CN", label: "CN" },
  { code: "JP", label: "JP" },
  { code: "VI", label: "VI" },
]
