export const translations = {
  EN: {
    yourDay: "Your Day",
    goodMorning: "Good morning,",
    timeline: "TIMELINE",
    noEvents: "No events today",
    clearDay: "Clear day — enjoy it.",
    workout: "Workout",
    todaysPlan: "TODAY'S PLAN",
    askForTips: "Ask for tips",
    alternative: "Alternative",
    settings: "Settings",
    syncNow: "Sync Now",
    signOut: "Sign Out",
    howCanIHelp: "How can I help?",
    askAnything: "Ask anything...",
    schedule: "Schedule",
    ai: "AI",
  },
  CN: {
    yourDay: "你的一天",
    goodMorning: "早上好，",
    timeline: "时间线",
    noEvents: "今天没有活动",
    clearDay: "轻松的一天 — 好好享受。",
    workout: "锻炼",
    todaysPlan: "今日计划",
    askForTips: "获取建议",
    alternative: "替代方案",
    settings: "设置",
    syncNow: "立即同步",
    signOut: "退出登录",
    howCanIHelp: "我能帮你什么？",
    askAnything: "随便问...",
    schedule: "日程",
    ai: "AI",
  },
  JP: {
    yourDay: "今日の予定",
    goodMorning: "おはようございます、",
    timeline: "タイムライン",
    noEvents: "今日の予定はありません",
    clearDay: "予定なし — ゆっくり過ごしてください。",
    workout: "ワークアウト",
    todaysPlan: "今日のプラン",
    askForTips: "アドバイスを求める",
    alternative: "代替案",
    settings: "設定",
    syncNow: "今すぐ同期",
    signOut: "サインアウト",
    howCanIHelp: "どのようにお手伝いできますか？",
    askAnything: "何でも聞いてください...",
    schedule: "スケジュール",
    ai: "AI",
  },
  VI: {
    yourDay: "Ngày của bạn",
    goodMorning: "Chào buổi sáng,",
    timeline: "THỜI GIAN BIỂU",
    noEvents: "Không có sự kiện hôm nay",
    clearDay: "Ngày trống — hãy tận hưởng.",
    workout: "Tập luyện",
    todaysPlan: "KẾ HOẠCH HÔM NAY",
    askForTips: "Xin lời khuyên",
    alternative: "Thay thế",
    settings: "Cài đặt",
    syncNow: "Đồng bộ ngay",
    signOut: "Đăng xuất",
    howCanIHelp: "Tôi có thể giúp gì cho bạn?",
    askAnything: "Hỏi bất cứ điều gì...",
    schedule: "Lịch trình",
    ai: "AI",
  },
} as const

export type Language = keyof typeof translations
export type TranslationKey = keyof typeof translations.EN

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: "EN", label: "EN" },
  { code: "CN", label: "CN" },
  { code: "JP", label: "JP" },
  { code: "VI", label: "VI" },
]
