ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "heightCm" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "weightKg" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bmi" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hasInjury" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "injuryNotes" TEXT;
