"use client"
import { createContext, useContext, useEffect, useState } from 'react'

type Lang = 'EN' | 'CN' | 'JP' | 'VI'

const translations = {
  EN: {
    yourDay: 'Your Day',
    goodMorning: 'Good morning,',
    timeline: 'TIMELINE',
    noEvents: 'No events today',
    clearDay: 'Clear day \u2014 enjoy it.',
    workout: 'Workout',
    todaysPlan: "TODAY'S PLAN",
    askForTips: 'Ask for tips',
    alternative: 'Alternative',
    setReminder: 'Set reminder',
    workoutIn: 'Workout in 15 minutes',
    settings: 'Profile',
    syncNow: 'Sync Now',
    disconnect: 'Disconnect',
    signOut: 'Sign Out',
    pushNotifications: 'Push Notifications',
    workoutReminders: 'Workout reminders',
    version: 'Version',
    stats: 'STATS',
    calendar: 'CALENDAR',
    preferences: 'PREFERENCES',
    googleConnected: 'Google Calendar connected',
    readOnly: 'Read only',
    howCanIHelp: 'How can I help?',
    askSubtitle: 'Ask about your schedule or workouts',
    askAnything: 'Ask anything...',
    schedule: 'Schedule',
    ai: 'AI',
    synced: 'Synced',
    welcomeBack: 'Welcome back',
    signInContinue: 'Sign in to continue',
    email: 'EMAIL',
    password: 'PASSWORD',
    signIn: 'Sign In',
    orContinueWith: 'or continue with',
    continueGoogle: 'Continue with Google',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    connect: 'Connect',
    workoutPlanner: 'Workout planner',
    fitSchedAI: 'FitSched AI',
    connectionError: 'Could not connect. Check your internet and try again.',
    enabled: 'Enabled',
    user: 'User',
    nameLabel: 'NAME',
    creatingAccount: 'Creating account...',
    addToSchedule: 'Add to Schedule',
    saveFailed: 'Failed to save. Try again.',
    cancel: 'Cancel',
    addedToSchedule: 'Added to your schedule!',
    restDay: 'Rest Day',
    restBody: 'Rest is when your body rebuilds. Light walk recommended.',
    showStretch: 'Show stretch routine',
    saveToSchedule: 'Save to Schedule',
    savedToSchedule: 'Saved to schedule!',
    reminder: 'REMINDER',
    reminderSet: 'Reminder set',
    fitSched: 'FitSched',
    connectCalendar: 'Connect Calendar',
    syncDescription: 'Read-only sync to find workout windows.',
    signInWithGoogle: 'Sign in with Google',
    syncing: 'Syncing...',
    connecting: 'Connecting...',
    autoScheduled: 'Auto-scheduled',
    avgWorkout: 'Avg workout',
    decisions: 'Decisions',
    days: 'Days',
    tagline: 'Your schedule. Your pace.',
    startJourney: 'Start your journey.',
    createAccount: 'Create account',
    itsFree: "It's free, always.",
    hasAccount: 'Already have an account?',
    exercises: 'Exercises',
    add: 'Add',
    searchExercises: 'Search exercises...',
    all: 'All',
    defaultLabel: 'Default',
    noExercises: 'No exercises found',
    addExercise: 'Add Exercise',
    name: 'Name',
    description: 'Description',
    optionalDescription: 'Optional description',
    muscle: 'Muscle',
    equipment: 'Equipment',
    difficulty: 'Difficulty',
    exerciseName: 'Exercise name',
    progress: 'Progress',
    trackJourney: 'Track your workout journey',
    overview: 'Overview',
    charts: 'Charts',
    totalWorkouts: 'Total Workouts',
    totalSets: 'Total Sets',
    avgRating: 'Avg Rating',
    thisWeek: 'This Week',
    recentActivity: 'Recent Activity',
    noWorkouts: 'No workouts logged yet',
    setsPerSession: 'Sets per Session',
    noData: 'No data yet',
    ratingTrend: 'Rating Trend',
    language: 'Language',
    workoutLabel: 'WORKOUT',
  },
  CN: {
    yourDay: '你的一天',
    goodMorning: '早上好，',
    timeline: '时间线',
    noEvents: '今天没有活动',
    clearDay: '轻松的一天 \u2014 好好享受。',
    workout: '锻炼',
    todaysPlan: '今日计划',
    askForTips: '获取建议',
    alternative: '替代方案',
    setReminder: '设置提醒',
    workoutIn: '15分钟后锻炼',
    settings: '个人资料',
    syncNow: '立即同步',
    disconnect: '断开连接',
    signOut: '退出登录',
    pushNotifications: '推送通知',
    workoutReminders: '锻炼提醒',
    version: '版本',
    stats: '统计',
    calendar: '日历',
    preferences: '偏好设置',
    googleConnected: 'Google日历已连接',
    readOnly: '只读',
    howCanIHelp: '我能帮你什么？',
    askSubtitle: '询问您的日程或锻炼计划',
    askAnything: '随便问...',
    schedule: '日程',
    ai: 'AI',
    synced: '已同步',
    welcomeBack: '欢迎回来',
    signInContinue: '登录以继续',
    email: '邮箱',
    password: '密码',
    signIn: '登录',
    orContinueWith: '或继续使用',
    continueGoogle: '使用Google继续',
    noAccount: '没有账号？',
    signUp: '注册',
    connect: '连接',
    workoutPlanner: '锻炼计划器',
    fitSchedAI: 'FitSched AI',
    connectionError: '无法连接。请检查网络后重试。',
    enabled: '已启用',
    user: '用户',
    nameLabel: '名称',
    creatingAccount: '正在创建账户...',
    addToSchedule: '添加到日程',
    saveFailed: '保存失败。请重试。',
    cancel: '取消',
    addedToSchedule: '已添加到日程！',
    restDay: '休息日',
    restBody: '休息是身体重建的时候。建议轻度散步。',
    showStretch: '展示拉伸动作',
    saveToSchedule: '保存到日程',
    savedToSchedule: '已保存到日程！',
    reminder: '提醒',
    reminderSet: '已设置提醒',
    fitSched: 'FitSched',
    connectCalendar: '连接日历',
    syncDescription: '只读同步以查找锻炼窗口。',
    signInWithGoogle: '使用Google登录',
    syncing: '同步中...',
    connecting: '连接中...',
    autoScheduled: '自动安排',
    avgWorkout: '平均锻炼',
    decisions: '决策',
    days: '天',
    tagline: '你的日程。你的节奏。',
    startJourney: '开始你的旅程。',
    createAccount: '创建账户',
    itsFree: '永久免费。',
    hasAccount: '已有账号？',
    exercises: '动作库',
    add: '添加',
    searchExercises: '搜索动作...',
    all: '全部',
    defaultLabel: '默认',
    noExercises: '未找到动作',
    addExercise: '添加动作',
    name: '名称',
    description: '描述',
    optionalDescription: '可选描述',
    muscle: '肌肉',
    equipment: '器材',
    difficulty: '难度',
    exerciseName: '动作名称',
    progress: '进度',
    trackJourney: '跟踪你的锻炼旅程',
    overview: '概览',
    charts: '图表',
    totalWorkouts: '总锻炼',
    totalSets: '总组数',
    avgRating: '平均评分',
    thisWeek: '本周',
    recentActivity: '最近活动',
    noWorkouts: '尚无锻炼记录',
    setsPerSession: '每组组数',
    noData: '暂无数据',
    ratingTrend: '评分趋势',
    language: '语言',
    workoutLabel: '锻炼',
  },
  JP: {
    yourDay: '今日の予定',
    goodMorning: 'おはようございます、',
    timeline: 'タイムライン',
    noEvents: '今日の予定はありません',
    clearDay: '予定なし \u2014 ゆっくり過ごしてください。',
    workout: 'ワークアウト',
    todaysPlan: '今日のプラン',
    askForTips: 'アドバイスを求める',
    alternative: '代替案',
    setReminder: 'リマインダーを設定',
    workoutIn: '15分後にワークアウト',
    settings: 'プロフィール',
    syncNow: '今すぐ同期',
    disconnect: '切断',
    signOut: 'サインアウト',
    pushNotifications: 'プッシュ通知',
    workoutReminders: 'ワークアウトリマインダー',
    version: 'バージョン',
    stats: '統計',
    calendar: 'カレンダー',
    preferences: '設定',
    googleConnected: 'Googleカレンダー接続済み',
    readOnly: '読み取り専用',
    howCanIHelp: 'どのようにお手伝いできますか？',
    askSubtitle: 'スケジュールやワークアウトについて質問してください',
    askAnything: '何でも聞いてください...',
    schedule: 'スケジュール',
    ai: 'AI',
    synced: '同期済み',
    welcomeBack: 'おかえりなさい',
    signInContinue: '続けるにはサインインしてください',
    email: 'メール',
    password: 'パスワード',
    signIn: 'サインイン',
    orContinueWith: 'または続ける',
    continueGoogle: 'Googleで続ける',
    noAccount: 'アカウントをお持ちでないですか？',
    signUp: '登録',
    connect: '接続',
    workoutPlanner: 'ワークアウトプランナー',
    fitSchedAI: 'FitSched AI',
    connectionError: '接続できませんでした。インターネットを確認してもう一度お試しください。',
    enabled: '有効',
    user: 'ユーザー',
    nameLabel: '名前',
    creatingAccount: 'アカウント作成中...',
    addToSchedule: 'スケジュールに追加',
    saveFailed: '保存に失敗しました。もう一度お試しください。',
    cancel: 'キャンセル',
    addedToSchedule: 'スケジュールに追加しました！',
    restDay: '休息日',
    restBody: '休息は体が回復する時間です。軽い散歩をおすすめします。',
    showStretch: 'ストレッチを見る',
    saveToSchedule: 'スケジュールに保存',
    savedToSchedule: 'スケジュールに保存しました！',
    reminder: 'リマインダー',
    reminderSet: 'リマインダー設定済み',
    fitSched: 'FitSched',
    connectCalendar: 'カレンダーを接続',
    syncDescription: 'ワークアウトの時間帯を見つけるための読み取り専用同期。',
    signInWithGoogle: 'Googleでサインイン',
    syncing: '同期中...',
    connecting: '接続中...',
    autoScheduled: '自動スケジュール',
    avgWorkout: '平均ワークアウト',
    decisions: '決定',
    days: '日',
    tagline: 'あなたのスケジュール。あなたのペース。',
    startJourney: '旅を始めましょう。',
    createAccount: 'アカウント作成',
    itsFree: 'いつでも無料です。',
    hasAccount: 'すでにアカウントをお持ちですか？',
    exercises: 'エクササイズ',
    add: '追加',
    searchExercises: 'エクササイズを検索...',
    all: 'すべて',
    defaultLabel: 'デフォルト',
    noExercises: 'エクササイズが見つかりません',
    addExercise: 'エクササイズを追加',
    name: '名前',
    description: '説明',
    optionalDescription: '任意の説明',
    muscle: '筋肉',
    equipment: '器具',
    difficulty: '難易度',
    exerciseName: 'エクササイズ名',
    progress: '進捗',
    trackJourney: 'ワークアウトの旅を記録',
    overview: '概要',
    charts: 'チャート',
    totalWorkouts: '総ワークアウト',
    totalSets: '総セット数',
    avgRating: '平均評価',
    thisWeek: '今週',
    recentActivity: '最近の活動',
    noWorkouts: 'まだワークアウトが記録されていません',
    setsPerSession: 'セッションあたりのセット数',
    noData: 'データがまだありません',
    ratingTrend: '評価の傾向',
    language: '言語',
    workoutLabel: 'ワークアウト',
  },
  VI: {
    yourDay: 'Ngày của bạn',
    goodMorning: 'Chào buổi sáng,',
    timeline: 'THỜI GIAN BIỂU',
    noEvents: 'Không có sự kiện hôm nay',
    clearDay: 'Ngày trống \u2014 hãy tận hưởng.',
    workout: 'Tập luyện',
    todaysPlan: 'KẾ HOẠCH HÔM NAY',
    askForTips: 'Xin lời khuyên',
    alternative: 'Thay thế',
    setReminder: 'Đặt nhắc nhở',
    workoutIn: 'Tập luyện sau 15 phút',
    settings: 'Hồ sơ',
    syncNow: 'Đồng bộ ngay',
    disconnect: 'Ngắt kết nối',
    signOut: 'Đăng xuất',
    pushNotifications: 'Thông báo đẩy',
    workoutReminders: 'Nhắc nhở tập luyện',
    version: 'Phiên bản',
    stats: 'THỐNG KÊ',
    calendar: 'LỊCH',
    preferences: 'TÙY CHỌN',
    googleConnected: 'Google Calendar đã kết nối',
    readOnly: 'Chỉ đọc',
    howCanIHelp: 'Tôi có thể giúp gì cho bạn?',
    askSubtitle: 'Hỏi về lịch trình hoặc bài tập của bạn',
    askAnything: 'Hỏi bất cứ điều gì...',
    schedule: 'Lịch trình',
    ai: 'AI',
    synced: 'Đã đồng bộ',
    welcomeBack: 'Chào mừng trở lại',
    signInContinue: 'Đăng nhập để tiếp tục',
    email: 'EMAIL',
    password: 'MẬT KHẨU',
    signIn: 'Đăng nhập',
    orContinueWith: 'hoặc tiếp tục với',
    continueGoogle: 'Tiếp tục với Google',
    noAccount: 'Chưa có tài khoản?',
    signUp: 'Đăng ký',
    connect: 'Kết nối',
    workoutPlanner: 'Trình lập kế hoạch tập luyện',
    fitSchedAI: 'FitSched AI',
    connectionError: 'Không thể kết nối. Kiểm tra internet và thử lại.',
    enabled: 'Đã bật',
    user: 'Người dùng',
    nameLabel: 'TÊN',
    creatingAccount: 'Đang tạo tài khoản...',
    addToSchedule: 'Thêm vào Lịch trình',
    saveFailed: 'Lưu thất bại. Thử lại.',
    cancel: 'Hủy',
    addedToSchedule: 'Đã thêm vào lịch trình!',
    restDay: 'Ngày nghỉ',
    restBody: 'Nghỉ ngơi là lúc cơ thể phục hồi. Đi bộ nhẹ được khuyến khích.',
    showStretch: 'Xem bài giãn cơ',
    saveToSchedule: 'Lưu vào Lịch trình',
    savedToSchedule: 'Đã lưu vào lịch trình!',
    reminder: 'NHẮC NHỞ',
    reminderSet: 'Đã đặt nhắc nhở',
    fitSched: 'FitSched',
    connectCalendar: 'Kết nối Lịch',
    syncDescription: 'Đồng bộ chỉ đọc để tìm khung giờ tập luyện.',
    signInWithGoogle: 'Đăng nhập bằng Google',
    syncing: 'Đang đồng bộ...',
    connecting: 'Đang kết nối...',
    autoScheduled: 'Tự động lên lịch',
    avgWorkout: 'TB tập luyện',
    decisions: 'Quyết định',
    days: 'Ngày',
    tagline: 'Lịch trình của bạn. Nhịp độ của bạn.',
    startJourney: 'Bắt đầu hành trình của bạn.',
    createAccount: 'Tạo tài khoản',
    itsFree: 'Hoàn toàn miễn phí.',
    hasAccount: 'Đã có tài khoản?',
    exercises: 'Bài tập',
    add: 'Thêm',
    searchExercises: 'Tìm kiếm bài tập...',
    all: 'Tất cả',
    defaultLabel: 'Mặc định',
    noExercises: 'Không tìm thấy bài tập',
    addExercise: 'Thêm bài tập',
    name: 'Tên',
    description: 'Mô tả',
    optionalDescription: 'Mô tả tùy chọn',
    muscle: 'Cơ',
    equipment: 'Thiết bị',
    difficulty: 'Độ khó',
    exerciseName: 'Tên bài tập',
    progress: 'Tiến độ',
    trackJourney: 'Theo dõi hành trình tập luyện của bạn',
    overview: 'Tổng quan',
    charts: 'Biểu đồ',
    totalWorkouts: 'Tổng số buổi tập',
    totalSets: 'Tổng số hiệp',
    avgRating: 'Đánh giá TB',
    thisWeek: 'Tuần này',
    recentActivity: 'Hoạt động gần đây',
    noWorkouts: 'Chưa có buổi tập nào',
    setsPerSession: 'Số hiệp mỗi buổi',
    noData: 'Chưa có dữ liệu',
    ratingTrend: 'Xu hướng đánh giá',
    language: 'Ngôn ngữ',
    workoutLabel: 'TẬP LUYỆN',
  }
}

type TranslationKey = keyof typeof translations.EN

const LanguageContext = createContext<{
  language: Lang
  t: typeof translations.EN
  cycleLanguage: () => void
  changeLanguage: (lang: Lang) => void
}>({
  language: 'EN',
  t: translations.EN,
  cycleLanguage: () => {},
  changeLanguage: () => {}
})

export function LanguageProvider({
  children
}: {
  children: React.ReactNode
}) {
  const [language, setLanguage] = useState<Lang>('EN')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Lang || 'EN'
    setLanguage(saved)
  }, [])

  const cycleLanguage = () => {
    const langs: Lang[] = ['EN', 'CN', 'JP', 'VI']
    const next = langs[(langs.indexOf(language) + 1) % langs.length]
    setLanguage(next)
    localStorage.setItem('language', next)
    document.documentElement.setAttribute('lang', next.toLowerCase())
  }

  const changeLanguage = (lang: Lang) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
    document.documentElement.setAttribute('lang', lang.toLowerCase())
  }

  return (
    <LanguageContext.Provider value={{
      language,
      t: translations[language],
      cycleLanguage,
      changeLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
