"use client"
import { createContext, useContext, useEffect, useState } from 'react'

type Lang = 'EN' | 'CN' | 'JP' | 'VI'

const translations = {
  EN: {
    yourDay: 'Your Day',
    days: {
      sun: 'Sun', mon: 'Mon', tue: 'Tue',
      wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat'
    },
    goodMorning: 'Good morning,',
    timeline: 'TIMELINE',
    noEvents: 'No events today',
    clearDay: 'Clear day \u2014 enjoy it.',
    workout: 'Workout',
    todaysPlan: "TODAY'S PLAN",
    setReminder: 'Set reminder',
    workoutIn: 'Workout in 15 minutes',
    settings: 'Settings',
    syncNow: 'Sync Now',
    disconnect: 'Disconnect',
    signOut: 'Sign Out',
    pushNotifications: 'Push Notifications',
    workoutReminders: 'Workout reminders',
    version: 'Version',
    stats: 'STATS',
    calendar: 'CALENDAR',
    preferences: 'PREFERENCES',
    workoutSetup: 'Workout setup',
    workoutSetupDescription: 'Used for exercise recommendations',
    homeWorkout: 'Home workout',
    noEquipment: 'No equipment',
    homeDumbbells: 'Home + dumbbells',
    dumbbellAccess: 'Dumbbell access',
    gym: 'Gym',
    fullEquipment: 'Full equipment',
    hike: 'Hike',
    googleConnected: 'Google Calendar connected',
    readOnly: 'Read only',
    schedule: 'Schedule',
    synced: 'Synced',
    welcomeBack: 'Welcome back',
    signInContinue: 'Sign in to continue',
    email: 'EMAIL',
    password: 'PASSWORD',
    signIn: 'Sign In',
    orContinueWith: 'or continue with',
    continueGoogle: 'Continue with Google',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    forgotPassword: 'Forgot password?',
    continueGuest: 'Continue as Guest',
    startingGuest: 'Starting guest session…',
    connect: 'Connect',

    enabled: 'Enabled',
    user: 'User',
    nameLabel: 'NAME',
    creatingAccount: 'Creating account...',
    cancel: 'Cancel',
    restDay: 'Rest Day',
    restBody: 'Rest is when your body rebuilds. Light walk recommended.',
    lightWorkoutBtn: 'Try a light workout →',
    saveToSchedule: 'Save to Schedule',
    savedToSchedule: 'Saved to schedule!',
    reminder: 'REMINDER',
    reminderSet: 'Reminder set',
    fitSched: 'FitSched',
    connectCalendar: 'Connect Calendar',
    syncDescription: 'Read-only sync to find workout windows.',
    signInWithGoogle: 'Sign in with Google',
    syncing: 'Syncing...',
    connecting: 'Connecting...',
    autoScheduled: 'Auto-scheduled',
    avgWorkout: 'Avg workout',
    decisions: 'Decisions',
    daysLabel: 'Days',
    tagline: 'Your schedule. Your pace.',
    startJourney: 'Start your journey.',
    createAccount: 'Create account',
    itsFree: "It's free, always.",
    hasAccount: 'Already have an account?',
    exercises: 'Exercises',
    add: 'Add',
    searchExercises: 'Search exercises...',
    all: 'All',
    defaultLabel: 'Default',
    noExercises: 'No exercises found',
    addExercise: 'Add Exercise',
    name: 'Name',
    description: 'Description',
    optionalDescription: 'Optional description',
    muscle: 'Muscle',
    equipment: 'Equipment',
    difficulty: 'Difficulty',
    exerciseName: 'Exercise name',
    history: 'History',
    progress: 'Progress',
    trackJourney: 'Track your workout journey',
    overview: 'Overview',
    charts: 'Charts',
    totalWorkouts: 'Total Workouts',
    totalSets: 'Total Sets',
    avgRating: 'Avg Rating',
    thisWeek: 'This Week',
    recentActivity: 'Recent Activity',
    noWorkouts: 'No workouts logged yet',
    setsPerSession: 'Sets per Session',
    noData: 'No data yet',
    ratingTrend: 'Rating Trend',
    language: 'Language',
    workoutLabel: 'WORKOUT',
    markAsDone: '✓ Mark as Done',
    workoutCompleted: '✓ Workout completed!',
    logWorkout: 'Log Workout',
    adjustReps: 'Adjust actual reps and sets completed',
    saveWorkoutLog: 'Save Workout Log',
    sets: 'SETS',
    reps: 'REPS',
    currentStreak: 'Current Streak',
    totalExercises: 'Total Exercises',
    last8Weeks: 'Last 8 Weeks',
    mostTrained: 'Most Trained',
    workoutHistory: 'WORKOUT HISTORY',
    alreadyHaveAccount: 'Already have an account?',
    addSchedule: 'Add schedule',
    editSchedule: 'Edit schedule',
    addToSchedule: 'Add to schedule',
    saveChanges: 'Save changes',
    adding: 'Adding...',
    saving: 'Saving...',
    manual: 'Manual',
    edit: 'Edit',
    delete: 'Delete',
    deleting: '...',
    goExercise: 'Go Exercise',
    exercisesCount: 'exercises',
    title: 'TITLE',
    time: 'TIME',
    optionalNotes: 'Optional notes',
    classWorkAppointment: 'Class, work, appointment...',
    workoutLockedTitle: 'Workout locked for this day',
    workoutLockedBody: 'You already completed this workout, so FitTokens are protected until the next workout day.',
    todayWorkoutOnlyTitle: "Today's workout only",
    todayWorkoutOnlyBody: 'FitTokens can only be earned from the current day, so other days are preview-only.',
    todayOnly: 'Today only',
    checkingWorkout: 'CHECKING WORKOUT',
    workoutAlreadyComplete: 'Workout already complete',
    workoutAlreadyCompleteBody: 'This day is locked so FitTokens stay fair. Come back for the next workout day.',
    noWorkoutLoaded: 'No workout loaded',
    noWorkoutLoadedBody: 'Start from the Workout tab to begin an exercise session.',
    backToWorkout: 'Back to Workout',
    back: 'Back',
    exercisesDone: 'EXERCISES DONE',
    restTime: 'Rest time',
    nowTraining: 'Now training',
    resting: 'Resting...',
    pauseTimer: 'Pause Timer',
    resumeTimer: 'Resume Timer',
    exerciseLabel: 'EXERCISE',
    setLabel: 'SET',
    ofLabel: 'OF',
    repsThisSet: 'reps this set',
    setsDone: 'sets done',
    skipRest: 'Skip Rest',
    doneSet: 'Done Set',
    finishWorkout: 'Finish Workout',
    workoutCompleteTitle: 'Workout complete',
    workoutCompleteBody: 'You showed up today. Keep this rhythm going.',
    streakLabel: 'STREAK',
    dayStreak: 'day streak',
    receiveFitToken: 'RECEIVE FITTOKEN',
    continueLabel: 'Continue',
    lpHeroLine1: 'Plan smarter.',
    lpHeroLine2: 'Train harder.',
    lpHeroBody: 'Build a full weekly workout plan around your exercises, equipment, and schedule — then track every session, streak, and hike.',
    lpSeeHow: 'See how it works',
    lpCheck1: 'Build a custom 7-day plan with 80+ exercises',
    lpCheck2: 'Track every session, streak, and rest day',
    lpCheck3: 'GPS hike tracking built in',
    lpCtaTitle: 'Your first workout plan is two minutes away.',
    lpCtaBody: 'No credit card. Just set up your plan and start training.',
    lpGetStartedFree: 'Get started free',
    setsCount: 'sets',
    showLess: 'Show less',
    showAll: 'Show all {n} workouts',
    completeFirstWorkout: 'Complete your first workout and your progress will appear here.',
    goToSchedule: 'Go to Schedule',
    freeWindow: 'Free window',
    classLabel: 'Class',
    clearDayTitle: 'Clear day',
    clearDayHint: 'Nothing scheduled — tap + to add a block or enjoy the rest.',
    byTheNumbers: 'BY THE NUMBERS',
    workoutsDone: 'Workouts done',
    exercisesDoneLabel: 'Exercises done',
    bestStreakLabel: 'Best streak',
    lifetimeLabel: 'lifetime',
    // Landing page specific
    lpFitnessScheduler: 'Fitness Scheduler',
    lpPlanGenerator: 'Plan Generator',
    lpPlanLine1: 'One prompt.',
    lpPlanLine2: 'A full week of training.',
    lpSessionPush: 'Push day',
    lpSessionRest: 'Rest',
    lpSessionLower: 'Lower body',
    lpSessionPushTime: 'Mon · 3 sets · 6 ex',
    lpSessionRestTime: 'Wed · Recovery',
    lpSessionLowerTime: 'Fri · 4 sets · 5 ex',
    lpStreakTitle: 'Streak',
    lpDaysInARow: 'days in a row',
    lpLongestRun: 'Your longest run: 31 days',
    lpProgressLabel: 'Progress',
    lpLast10Days: 'Last 10 days',
    lpSessionsCompleted: 'sessions completed',
    lpVsLastWeek: '+12% vs last week',
    lpBuiltDifferent: 'Built different',
    lpEveryTool: 'Every tool you need.',
    lpNothingYouDont: "Nothing you don't.",
    lpStatExercises: 'exercises in the library',
    lpStatPlans: 'custom workout plans',
    lpStatHike: 'hike & route tracking',
    lpStatStreak: 'average streak days',
    lpStartToday: 'Start today',
    lpFooterTagline: 'Your fitness, scheduled.',
    lpMarqueeItems: [
      'Plan Generator', 'Streak Tracking', 'GPS Hike Tracking',
      'Exercise Library', 'Progress Reports', 'FitTokens',
      'Workout Plans', '80+ Exercises', 'Google Calendar Sync',
      'Session History', 'Rest Day Logic', 'Habit Tracking',
    ],
    fitnessProfile: 'FITNESS PROFILE',
    earnings: 'EARNINGS',
    goalLabel: 'Goal',
    experienceLevelLabel: 'Experience level',
    bodyStats: 'Body stats',
    deleteAccount: 'Delete account',
    typeDeleteToConfirm: 'Type DELETE to confirm',
    temporaryAccount: 'Temporary account',
    yourProgressIsTemporary: 'Your progress is temporary',
    profileUpdated: 'Profile updated',
  },
  CN: {
    yourDay: '你的一天',
    days: {
      sun: '周日', mon: '周一', tue: '周二',
      wed: '周三', thu: '周四', fri: '周五', sat: '周六'
    },
    goodMorning: '早上好，',
    timeline: '时间线',
    noEvents: '今天没有活动',
    clearDay: '轻松的一天 \u2014 好好享受。',
    workout: '锻炼',
    todaysPlan: '今日计划',
    setReminder: '设置提醒',
    workoutIn: '15分钟后锻炼',
    settings: '设置',
    syncNow: '立即同步',
    disconnect: '断开连接',
    signOut: '退出登录',
    pushNotifications: '推送通知',
    workoutReminders: '锻炼提醒',
    version: '版本',
    stats: '统计',
    calendar: '日历',
    preferences: '偏好设置',
    workoutSetup: '\u8bad\u7ec3\u8bbe\u7f6e',
    workoutSetupDescription: '\u7528\u4e8e\u8fd0\u52a8\u63a8\u8350',
    homeWorkout: '\u5c45\u5bb6\u8bad\u7ec3',
    noEquipment: '\u65e0\u9700\u5668\u6750',
    homeDumbbells: '\u5c45\u5bb6 + \u54d1\u94c3',
    dumbbellAccess: '\u53ef\u4f7f\u7528\u54d1\u94c3',
    gym: '\u5065\u8eab\u623f',
    fullEquipment: '\u5b8c\u6574\u5668\u6750',
    hike: '\u5f92\u6b65',
    googleConnected: 'Google日历已连接',
    readOnly: '只读',
    schedule: '日程',
    synced: '已同步',
    welcomeBack: '欢迎回来',
    signInContinue: '登录以继续',
    email: '邮箱',
    password: '密码',
    signIn: '登录',
    orContinueWith: '或继续使用',
    continueGoogle: '使用Google继续',
    noAccount: '没有账号？',
    signUp: '注册',
    forgotPassword: '忘记密码？',
    continueGuest: '以访客身份继续',
    startingGuest: '正在启动访客会话…',
    connect: '连接',

    enabled: '已启用',
    user: '用户',
    nameLabel: '名称',
    creatingAccount: '正在创建账户...',
    cancel: '取消',
    restDay: '休息日',
    restBody: '休息是身体重建的时候。建议轻度散步。',
    lightWorkoutBtn: '试试轻度锻炼 →',
    saveToSchedule: '保存到日程',
    savedToSchedule: '已保存到日程！',
    reminder: '提醒',
    reminderSet: '已设置提醒',
    fitSched: 'FitSched',
    connectCalendar: '连接日历',
    syncDescription: '只读同步以查找锻炼窗口。',
    signInWithGoogle: '使用Google登录',
    syncing: '同步中...',
    connecting: '连接中...',
    autoScheduled: '自动安排',
    avgWorkout: '平均锻炼',
    decisions: '决策',
    daysLabel: '天',
    tagline: '你的日程。你的节奏。',
    startJourney: '开始你的旅程。',
    createAccount: '创建账户',
    itsFree: '永久免费。',
    hasAccount: '已有账号？',
    exercises: '动作库',
    add: '添加',
    searchExercises: '搜索动作...',
    all: '全部',
    defaultLabel: '默认',
    noExercises: '未找到动作',
    addExercise: '添加动作',
    name: '名称',
    description: '描述',
    optionalDescription: '可选描述',
    muscle: '肌肉',
    equipment: '器材',
    difficulty: '难度',
    exerciseName: '动作名称',
    history: '历史',
    progress: '进度',
    trackJourney: '跟踪你的锻炼旅程',
    overview: '概览',
    charts: '图表',
    totalWorkouts: '总锻炼',
    totalSets: '总组数',
    avgRating: '平均评分',
    thisWeek: '本周',
    recentActivity: '最近活动',
    noWorkouts: '尚无锻炼记录',
    setsPerSession: '每组组数',
    noData: '暂无数据',
    ratingTrend: '评分趋势',
    language: '语言',
    workoutLabel: '锻炼',
    markAsDone: '✓ 标记完成',
    workoutCompleted: '✓ 锻炼完成！',
    logWorkout: '记录锻炼',
    adjustReps: '调整实际完成的组数和次数',
    saveWorkoutLog: '保存锻炼记录',
    sets: '组数',
    reps: '次数',
    currentStreak: '当前连续',
    totalExercises: '总动作数',
    last8Weeks: '最近8周',
    mostTrained: '最常训练',
    workoutHistory: '锻炼历史',
    alreadyHaveAccount: '已有账号？',
    addSchedule: '添加日程',
    editSchedule: '编辑日程',
    addToSchedule: '添加到日程',
    saveChanges: '保存更改',
    adding: '添加中...',
    saving: '保存中...',
    manual: '手动',
    edit: '编辑',
    delete: '删除',
    deleting: '...',
    goExercise: '开始锻炼',
    exercisesCount: '个动作',
    title: '标题',
    time: '时间',
    optionalNotes: '可选备注',
    classWorkAppointment: '课程、工作、约会...',
    workoutLockedTitle: '今天的锻炼已锁定',
    workoutLockedBody: '你已经完成了这次锻炼，所以 FitToken 会保护到下一个锻炼日。',
    todayWorkoutOnlyTitle: '只能完成今天的锻炼',
    todayWorkoutOnlyBody: 'FitToken 只能通过当天锻炼获得，其他日期只能预览。',
    todayOnly: '仅限今天',
    checkingWorkout: '正在检查锻炼',
    workoutAlreadyComplete: '锻炼已完成',
    workoutAlreadyCompleteBody: '这一天已锁定，确保 FitToken 公平。下一个锻炼日再回来吧。',
    noWorkoutLoaded: '没有载入锻炼',
    noWorkoutLoadedBody: '请从“锻炼”页面开始一次训练。',
    backToWorkout: '返回锻炼',
    back: '返回',
    exercisesDone: '个动作已完成',
    restTime: '休息时间',
    nowTraining: '正在训练',
    resting: '休息中...',
    pauseTimer: '暂停计时',
    resumeTimer: '继续计时',
    exerciseLabel: '动作',
    setLabel: '组',
    ofLabel: '共',
    repsThisSet: '次本组',
    setsDone: '组已完成',
    skipRest: '跳过休息',
    doneSet: '完成本组',
    finishWorkout: '完成锻炼',
    workoutCompleteTitle: '锻炼完成',
    workoutCompleteBody: '你今天坚持了。继续保持这个节奏。',
    streakLabel: '连续',
    dayStreak: '天连续',
    receiveFitToken: '领取 FITTOKEN',
    continueLabel: '继续',
    lpHeroLine1: '更智慧地规划。',
    lpHeroLine2: '更努力地训练。',
    lpHeroBody: '围绕你的运动、器材和日程，制定完整的每周训练计划——然后跟踪每次训练、连续打卡和徒步。',
    lpSeeHow: '了解更多',
    lpCheck1: '用80+个动作定制7天计划',
    lpCheck2: '跟踪每次训练、连续打卡和休息日',
    lpCheck3: '内置GPS徒步追踪',
    lpCtaTitle: '两分钟内生成你的第一份训练计划。',
    lpCtaBody: '无需信用卡。只需设置你的计划并开始训练。',
    lpGetStartedFree: '免费开始',
    setsCount: '组',
    showLess: '收起',
    showAll: '显示全部 {n} 次训练',
    completeFirstWorkout: '完成第一次训练后，你的进度将显示在这里。',
    goToSchedule: '前往日程',
    freeWindow: '空闲时间',
    classLabel: '课程',
    clearDayTitle: '轻松一天',
    clearDayHint: '没有安排 — 点击 + 添加，或好好休息。',
    byTheNumbers: '数据统计',
    workoutsDone: '已完成锻炼',
    exercisesDoneLabel: '已完成动作',
    bestStreakLabel: '最佳连续',
    lifetimeLabel: '总计',
    // Landing page specific
    lpFitnessScheduler: '健身计划助手',
    lpPlanGenerator: '智能计划',
    lpPlanLine1: '一句话，',
    lpPlanLine2: '生成完整周计划。',
    lpSessionPush: '推胸日',
    lpSessionRest: '休息',
    lpSessionLower: '下肢日',
    lpSessionPushTime: '周一 · 3组 · 6个动作',
    lpSessionRestTime: '周三 · 恢复',
    lpSessionLowerTime: '周五 · 4组 · 5个动作',
    lpStreakTitle: '连续',
    lpDaysInARow: '天连续',
    lpLongestRun: '最长连续：31天',
    lpProgressLabel: '进度',
    lpLast10Days: '最近10天',
    lpSessionsCompleted: '次训练完成',
    lpVsLastWeek: '+12% vs 上周',
    lpBuiltDifferent: '与众不同',
    lpEveryTool: '你所需要的一切工具。',
    lpNothingYouDont: '没有多余的。',
    lpStatExercises: '个动作库',
    lpStatPlans: '定制训练计划',
    lpStatHike: '徒步路线追踪',
    lpStatStreak: '平均连续天数',
    lpStartToday: '今天开始',
    lpFooterTagline: '你的健身，已规划。',
    lpMarqueeItems: [
      '智能计划', '连续追踪', 'GPS徒步追踪',
      '动作库', '进度报告', 'FitTokens',
      '训练计划', '80+个动作', 'Google日历同步',
      '训练历史', '休息日管理', '习惯追踪',
    ],
    fitnessProfile: '健身档案',
    earnings: '收益',
    goalLabel: '目标',
    experienceLevelLabel: '经验等级',
    bodyStats: '身体数据',
    deleteAccount: '删除账户',
    typeDeleteToConfirm: '输入 DELETE 以确认',
    temporaryAccount: '临时账户',
    yourProgressIsTemporary: '您的进度是临时的',
    profileUpdated: '档案已更新',
  },
  JP: {
    yourDay: '今日の予定',
    days: {
      sun: '日曜', mon: '月曜', tue: '火曜',
      wed: '水曜', thu: '木曜', fri: '金曜', sat: '土曜'
    },
    goodMorning: 'おはようございます、',
    timeline: 'タイムライン',
    noEvents: '今日の予定はありません',
    clearDay: '予定なし \u2014 ゆっくり過ごしてください。',
    workout: 'ワークアウト',
    todaysPlan: '今日のプラン',
    setReminder: 'リマインダーを設定',
    workoutIn: '15分後にワークアウト',
    settings: '設定',
    syncNow: '今すぐ同期',
    disconnect: '切断',
    signOut: 'サインアウト',
    pushNotifications: 'プッシュ通知',
    workoutReminders: 'ワークアウトリマインダー',
    version: 'バージョン',
    stats: '統計',
    calendar: 'カレンダー',
    preferences: '設定',
    workoutSetup: '\u30c8\u30ec\u30fc\u30cb\u30f3\u30b0\u74b0\u5883',
    workoutSetupDescription: '\u7a2e\u76ee\u306e\u304a\u3059\u3059\u3081\u306b\u4f7f\u7528',
    homeWorkout: '\u81ea\u5b85\u30c8\u30ec',
    noEquipment: '\u5668\u5177\u306a\u3057',
    homeDumbbells: '\u81ea\u5b85 + \u30c0\u30f3\u30d9\u30eb',
    dumbbellAccess: '\u30c0\u30f3\u30d9\u30eb\u3042\u308a',
    gym: '\u30b8\u30e0',
    fullEquipment: '\u5168\u5668\u5177\u3042\u308a',
    hike: '\u30cf\u30a4\u30af',
    googleConnected: 'Googleカレンダー接続済み',
    readOnly: '読み取り専用',
    schedule: 'スケジュール',
    synced: '同期済み',
    welcomeBack: 'おかえりなさい',
    signInContinue: '続けるにはサインインしてください',
    email: 'メール',
    password: 'パスワード',
    signIn: 'サインイン',
    orContinueWith: 'または続ける',
    continueGoogle: 'Googleで続ける',
    noAccount: 'アカウントをお持ちでないですか？',
    signUp: '登録',
    forgotPassword: 'パスワードをお忘れですか？',
    continueGuest: 'ゲストとして続ける',
    startingGuest: 'ゲストセッションを開始中…',
    connect: '接続',

    enabled: '有効',
    user: 'ユーザー',
    nameLabel: '名前',
    creatingAccount: 'アカウント作成中...',
    cancel: 'キャンセル',
    restDay: '休息日',
    restBody: '休息は体が回復する時間です。軽い散歩をおすすめします。',
    lightWorkoutBtn: '軽めのワークアウトを試す →',
    saveToSchedule: 'スケジュールに保存',
    savedToSchedule: 'スケジュールに保存しました！',
    reminder: 'リマインダー',
    reminderSet: 'リマインダー設定済み',
    fitSched: 'FitSched',
    connectCalendar: 'カレンダーを接続',
    syncDescription: 'ワークアウトの時間帯を見つけるための読み取り専用同期。',
    signInWithGoogle: 'Googleでサインイン',
    syncing: '同期中...',
    connecting: '接続中...',
    autoScheduled: '自動スケジュール',
    avgWorkout: '平均ワークアウト',
    decisions: '決定',
    daysLabel: '日',
    tagline: 'あなたのスケジュール。あなたのペース。',
    startJourney: '旅を始めましょう。',
    createAccount: 'アカウント作成',
    itsFree: 'いつでも無料です。',
    hasAccount: 'すでにアカウントをお持ちですか？',
    exercises: 'エクササイズ',
    add: '追加',
    searchExercises: 'エクササイズを検索...',
    all: 'すべて',
    defaultLabel: 'デフォルト',
    noExercises: 'エクササイズが見つかりません',
    addExercise: 'エクササイズを追加',
    name: '名前',
    description: '説明',
    optionalDescription: '任意の説明',
    muscle: '筋肉',
    equipment: '器具',
    difficulty: '難易度',
    exerciseName: 'エクササイズ名',
    history: '履歴',
    progress: '進捗',
    trackJourney: 'ワークアウトの旅を記録',
    overview: '概要',
    charts: 'チャート',
    totalWorkouts: '総ワークアウト',
    totalSets: '総セット数',
    avgRating: '平均評価',
    thisWeek: '今週',
    recentActivity: '最近の活動',
    noWorkouts: 'まだワークアウトが記録されていません',
    setsPerSession: 'セッションあたりのセット数',
    noData: 'データがまだありません',
    ratingTrend: '評価の傾向',
    language: '言語',
    workoutLabel: 'ワークアウト',
    markAsDone: '✓ 完了としてマーク',
    workoutCompleted: '✓ ワークアウト完了！',
    logWorkout: 'ワークアウトを記録',
    adjustReps: '実際に完了したセット数とレップ数を調整',
    saveWorkoutLog: 'ワークアウトログを保存',
    sets: 'セット',
    reps: 'レップ',
    currentStreak: '現在の連続',
    totalExercises: '総エクササイズ数',
    last8Weeks: '最近8週間',
    mostTrained: '最も鍛えた部位',
    workoutHistory: 'ワークアウト履歴',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    addSchedule: '予定を追加',
    editSchedule: '予定を編集',
    addToSchedule: '予定に追加',
    saveChanges: '変更を保存',
    adding: '追加中...',
    saving: '保存中...',
    manual: '手動',
    edit: '編集',
    delete: '削除',
    deleting: '...',
    goExercise: '運動を開始',
    exercisesCount: '種目',
    title: 'タイトル',
    time: '時間',
    optionalNotes: '任意のメモ',
    classWorkAppointment: '授業、仕事、予定...',
    workoutLockedTitle: 'この日のワークアウトはロック済み',
    workoutLockedBody: 'このワークアウトは完了済みのため、次のワークアウト日までFitTokenを保護します。',
    todayWorkoutOnlyTitle: '今日のワークアウトのみ',
    todayWorkoutOnlyBody: 'FitTokenは当日のワークアウトでのみ獲得できます。他の日はプレビュー専用です。',
    todayOnly: '今日のみ',
    checkingWorkout: 'ワークアウトを確認中',
    workoutAlreadyComplete: 'ワークアウトは完了済み',
    workoutAlreadyCompleteBody: 'FitTokenの公平性を守るため、この日はロックされています。次のワークアウト日に戻ってきてください。',
    noWorkoutLoaded: 'ワークアウトが読み込まれていません',
    noWorkoutLoadedBody: 'ワークアウトタブから運動セッションを開始してください。',
    backToWorkout: 'ワークアウトへ戻る',
    back: '戻る',
    exercisesDone: '種目完了',
    restTime: '休憩時間',
    nowTraining: 'トレーニング中',
    resting: '休憩中...',
    pauseTimer: 'タイマーを一時停止',
    resumeTimer: 'タイマーを再開',
    exerciseLabel: '種目',
    setLabel: 'セット',
    ofLabel: '中',
    repsThisSet: '回このセット',
    setsDone: 'セット完了',
    skipRest: '休憩をスキップ',
    doneSet: 'セット完了',
    finishWorkout: 'ワークアウトを完了',
    workoutCompleteTitle: 'ワークアウト完了',
    workoutCompleteBody: '今日もやり切りました。このリズムを続けましょう。',
    streakLabel: '連続',
    dayStreak: '日連続',
    receiveFitToken: 'FITTOKENを受け取る',
    continueLabel: '続ける',
    lpHeroLine1: '賢くプランを。',
    lpHeroLine2: 'ハードに鍛える。',
    lpHeroBody: 'あなたの種目・器具・スケジュールに合わせた週間トレーニングプランを作成し、すべてのセッション、ストリーク、ハイクを記録します。',
    lpSeeHow: '詳しく見る',
    lpCheck1: '80種目以上で7日間のカスタムプランを作成',
    lpCheck2: 'すべてのセッション・ストリーク・休息日を記録',
    lpCheck3: 'GPSハイクトラッキング内蔵',
    lpCtaTitle: '2分以内に最初のワークアウトプランを作成。',
    lpCtaBody: 'クレジットカード不要。プランを設定してトレーニング開始。',
    lpGetStartedFree: '無料で始める',
    setsCount: 'セット',
    showLess: '折りたたむ',
    showAll: '全 {n} 件を表示',
    completeFirstWorkout: '最初のワークアウトを完了すると、進捗がここに表示されます。',
    goToSchedule: 'スケジュールへ',
    freeWindow: '空き時間',
    classLabel: '授業',
    clearDayTitle: '空き日',
    clearDayHint: '予定なし — + をタップして追加するか、ゆっくり過ごしてください。',
    byTheNumbers: '記録',
    workoutsDone: '完了したワークアウト',
    exercisesDoneLabel: '完了した種目',
    bestStreakLabel: '最長連続',
    lifetimeLabel: '累計',
    // Landing page specific
    lpFitnessScheduler: 'フィットネス管理',
    lpPlanGenerator: 'プラン生成',
    lpPlanLine1: '一言で、',
    lpPlanLine2: '一週間のプランが完成。',
    lpSessionPush: 'プッシュ日',
    lpSessionRest: '休息',
    lpSessionLower: '下半身',
    lpSessionPushTime: '月曜 · 3セット · 6種目',
    lpSessionRestTime: '水曜 · 回復',
    lpSessionLowerTime: '金曜 · 4セット · 5種目',
    lpStreakTitle: 'ストリーク',
    lpDaysInARow: '日連続',
    lpLongestRun: '最長記録：31日',
    lpProgressLabel: '進捗',
    lpLast10Days: '直近10日',
    lpSessionsCompleted: 'セッション完了',
    lpVsLastWeek: '+12% 先週比',
    lpBuiltDifferent: '他とは違う',
    lpEveryTool: '必要なツール、すべて。',
    lpNothingYouDont: '余計なものは何もない。',
    lpStatExercises: '種目ライブラリ',
    lpStatPlans: 'カスタムトレーニング',
    lpStatHike: 'ハイク追跡',
    lpStatStreak: '平均連続日数',
    lpStartToday: '今日から始める',
    lpFooterTagline: 'あなたのフィットネス、予定通りに。',
    lpMarqueeItems: [
      'プラン生成', 'ストリーク記録', 'GPSハイク追跡',
      '種目ライブラリ', '進捗レポート', 'FitTokens',
      'トレーニング計画', '80種目以上', 'Googleカレンダー同期',
      'セッション履歴', '休息日管理', '習慣記録',
    ],
    fitnessProfile: 'フィットネスプロフィール',
    earnings: '収益',
    goalLabel: '目標',
    experienceLevelLabel: '経験レベル',
    bodyStats: '身体測定値',
    deleteAccount: 'アカウント削除',
    typeDeleteToConfirm: '確認のため DELETE と入力',
    temporaryAccount: '一時アカウント',
    yourProgressIsTemporary: 'あなたの進捗は一時的です',
    profileUpdated: 'プロフィールを更新しました',
  },
  VI: {
    yourDay: 'Ngày của bạn',
    days: {
      sun: 'CN', mon: 'T2', tue: 'T3',
      wed: 'T4', thu: 'T5', fri: 'T6', sat: 'T7'
    },
    goodMorning: 'Chào buổi sáng,',
    timeline: 'THỜI GIAN BIỂU',
    noEvents: 'Không có sự kiện hôm nay',
    clearDay: 'Ngày trống \u2014 hãy tận hưởng.',
    workout: 'Tập luyện',
    todaysPlan: 'KẾ HOẠCH HÔM NAY',
    setReminder: 'Đặt nhắc nhở',
    workoutIn: 'Tập luyện sau 15 phút',
    settings: 'Cài đặt',
    syncNow: 'Đồng bộ ngay',
    disconnect: 'Ngắt kết nối',
    signOut: 'Đăng xuất',
    pushNotifications: 'Thông báo đẩy',
    workoutReminders: 'Nhắc nhở tập luyện',
    version: 'Phiên bản',
    stats: 'THỐNG KÊ',
    calendar: 'LỊCH',
    preferences: 'TÙY CHỌN',
    workoutSetup: 'Thi\u1ebft l\u1eadp t\u1eadp luy\u1ec7n',
    workoutSetupDescription: 'D\u00f9ng \u0111\u1ec3 g\u1ee3i \u00fd b\u00e0i t\u1eadp',
    homeWorkout: 'T\u1eadp \u1edf nh\u00e0',
    noEquipment: 'Kh\u00f4ng c\u1ea7n d\u1ee5ng c\u1ee5',
    homeDumbbells: 'Nh\u00e0 + t\u1ea1 \u0111\u01a1n',
    dumbbellAccess: 'C\u00f3 t\u1ea1 \u0111\u01a1n',
    gym: 'Ph\u00f2ng gym',
    fullEquipment: '\u0110\u1ea7y \u0111\u1ee7 d\u1ee5ng c\u1ee5',
    hike: 'Leo n\u00fai',
    googleConnected: 'Google Calendar đã kết nối',
    readOnly: 'Chỉ đọc',
    schedule: 'Lịch trình',
    synced: 'Đã đồng bộ',
    welcomeBack: 'Chào mừng trở lại',
    signInContinue: 'Đăng nhập để tiếp tục',
    email: 'EMAIL',
    password: 'MẬT KHẨU',
    signIn: 'Đăng nhập',
    orContinueWith: 'hoặc tiếp tục với',
    continueGoogle: 'Tiếp tục với Google',
    noAccount: 'Chưa có tài khoản?',
    signUp: 'Đăng ký',
    forgotPassword: 'Quên mật khẩu?',
    continueGuest: 'Tiếp tục với tư cách khách',
    startingGuest: 'Đang bắt đầu phiên khách…',
    connect: 'Kết nối',

    enabled: 'Đã bật',
    user: 'Người dùng',
    nameLabel: 'TÊN',
    creatingAccount: 'Đang tạo tài khoản...',
    cancel: 'Hủy',
    restDay: 'Ngày nghỉ',
    restBody: 'Nghỉ ngơi là lúc cơ thể phục hồi. Đi bộ nhẹ được khuyến khích.',
    lightWorkoutBtn: 'Thử bài tập nhẹ →',
    saveToSchedule: 'Lưu vào Lịch trình',
    savedToSchedule: 'Đã lưu vào lịch trình!',
    reminder: 'NHẮC NHỞ',
    reminderSet: 'Đã đặt nhắc nhở',
    fitSched: 'FitSched',
    connectCalendar: 'Kết nối Lịch',
    syncDescription: 'Đồng bộ chỉ đọc để tìm khung giờ tập luyện.',
    signInWithGoogle: 'Đăng nhập bằng Google',
    syncing: 'Đang đồng bộ...',
    connecting: 'Đang kết nối...',
    autoScheduled: 'Tự động lên lịch',
    avgWorkout: 'TB tập luyện',
    decisions: 'Quyết định',
    daysLabel: 'Ngày',
    tagline: 'Lịch trình của bạn. Nhịp độ của bạn.',
    startJourney: 'Bắt đầu hành trình của bạn.',
    createAccount: 'Tạo tài khoản',
    itsFree: 'Hoàn toàn miễn phí.',
    hasAccount: 'Đã có tài khoản?',
    exercises: 'Bài tập',
    add: 'Thêm',
    searchExercises: 'Tìm kiếm bài tập...',
    all: 'Tất cả',
    defaultLabel: 'Mặc định',
    noExercises: 'Không tìm thấy bài tập',
    addExercise: 'Thêm bài tập',
    name: 'Tên',
    description: 'Mô tả',
    optionalDescription: 'Mô tả tùy chọn',
    muscle: 'Cơ',
    equipment: 'Thiết bị',
    difficulty: 'Độ khó',
    exerciseName: 'Tên bài tập',
    history: 'Lịch sử',
    progress: 'Tiến độ',
    trackJourney: 'Theo dõi hành trình tập luyện của bạn',
    overview: 'Tổng quan',
    charts: 'Biểu đồ',
    totalWorkouts: 'Tổng số buổi tập',
    totalSets: 'Tổng số hiệp',
    avgRating: 'Đánh giá TB',
    thisWeek: 'Tuần này',
    recentActivity: 'Hoạt động gần đây',
    noWorkouts: 'Chưa có buổi tập nào',
    setsPerSession: 'Số hiệp mỗi buổi',
    noData: 'Chưa có dữ liệu',
    ratingTrend: 'Xu hướng đánh giá',
    language: 'Ngôn ngữ',
    workoutLabel: 'TẬP LUYỆN',
    markAsDone: '✓ Đánh dấu hoàn thành',
    workoutCompleted: '✓ Hoàn thành bài tập!',
    logWorkout: 'Ghi lại bài tập',
    adjustReps: 'Điều chỉnh số hiệp và số lần thực tế',
    saveWorkoutLog: 'Lưu nhật ký tập luyện',
    sets: 'HIỆP',
    reps: 'LẦN',
    currentStreak: 'Chuỗi hiện tại',
    totalExercises: 'Tổng bài tập',
    last8Weeks: '8 tuần qua',
    mostTrained: 'Nhóm cơ tập nhiều nhất',
    workoutHistory: 'LỊCH SỬ TẬP LUYỆN',
    alreadyHaveAccount: 'Đã có tài khoản？',
    addSchedule: 'Thêm lịch',
    editSchedule: 'Sửa lịch',
    addToSchedule: 'Thêm vào lịch',
    saveChanges: 'Lưu thay đổi',
    adding: 'Đang thêm...',
    saving: 'Đang lưu...',
    manual: 'Thủ công',
    edit: 'Sửa',
    delete: 'Xóa',
    deleting: '...',
    goExercise: 'Bắt đầu tập',
    exercisesCount: 'bài tập',
    title: 'TIÊU ĐỀ',
    time: 'THỜI GIAN',
    optionalNotes: 'Ghi chú tùy chọn',
    classWorkAppointment: 'Lớp học, công việc, cuộc hẹn...',
    workoutLockedTitle: 'Bài tập hôm nay đã khóa',
    workoutLockedBody: 'Bạn đã hoàn thành bài tập này, nên FitTokens được bảo vệ đến ngày tập tiếp theo.',
    todayWorkoutOnlyTitle: 'Chỉ bài tập hôm nay',
    todayWorkoutOnlyBody: 'FitTokens chỉ nhận được từ ngày hiện tại, các ngày khác chỉ để xem trước.',
    todayOnly: 'Chỉ hôm nay',
    checkingWorkout: 'ĐANG KIỂM TRA BÀI TẬP',
    workoutAlreadyComplete: 'Bài tập đã hoàn thành',
    workoutAlreadyCompleteBody: 'Ngày này đã khóa để giữ FitTokens công bằng. Hãy quay lại vào ngày tập tiếp theo.',
    noWorkoutLoaded: 'Chưa tải bài tập',
    noWorkoutLoadedBody: 'Bắt đầu từ tab Tập luyện để vào buổi tập.',
    backToWorkout: 'Quay lại Tập luyện',
    back: 'Quay lại',
    exercisesDone: 'BÀI TẬP ĐÃ XONG',
    restTime: 'Thời gian nghỉ',
    nowTraining: 'Đang tập',
    resting: 'Đang nghỉ...',
    pauseTimer: 'Tạm dừng giờ',
    resumeTimer: 'Tiếp tục giờ',
    exerciseLabel: 'BÀI TẬP',
    setLabel: 'HIỆP',
    ofLabel: 'TRÊN',
    repsThisSet: 'lần hiệp này',
    setsDone: 'hiệp đã xong',
    skipRest: 'Bỏ qua nghỉ',
    doneSet: 'Xong hiệp',
    finishWorkout: 'Hoàn thành bài tập',
    workoutCompleteTitle: 'Hoàn thành bài tập',
    workoutCompleteBody: 'Hôm nay bạn đã xuất hiện. Hãy giữ nhịp này.',
    streakLabel: 'CHUỖI',
    dayStreak: 'ngày liên tiếp',
    receiveFitToken: 'NHẬN FITTOKEN',
    continueLabel: 'Tiếp tục',
    lpHeroLine1: 'Lên kế hoạch thông minh hơn.',
    lpHeroLine2: 'Tập luyện chăm chỉ hơn.',
    lpHeroBody: 'Xây dựng kế hoạch tập luyện hàng tuần xung quanh bài tập, thiết bị và lịch trình của bạn — sau đó theo dõi mọi buổi tập, chuỗi và chuyến đi bộ.',
    lpSeeHow: 'Xem cách hoạt động',
    lpCheck1: 'Tạo kế hoạch 7 ngày tùy chỉnh với 80+ bài tập',
    lpCheck2: 'Theo dõi mọi buổi tập, chuỗi và ngày nghỉ',
    lpCheck3: 'Tích hợp theo dõi GPS đi bộ',
    lpCtaTitle: 'Kế hoạch tập luyện đầu tiên của bạn chỉ trong hai phút.',
    lpCtaBody: 'Không cần thẻ tín dụng. Chỉ cần thiết lập kế hoạch và bắt đầu tập luyện.',
    lpGetStartedFree: 'Bắt đầu miễn phí',
    setsCount: 'hiệp',
    showLess: 'Thu gọn',
    showAll: 'Xem tất cả {n} buổi tập',
    completeFirstWorkout: 'Hoàn thành buổi tập đầu tiên và tiến độ của bạn sẽ hiển thị ở đây.',
    goToSchedule: 'Đến Lịch trình',
    freeWindow: 'Khung giờ rảnh',
    classLabel: 'Lớp học',
    clearDayTitle: 'Ngày rảnh',
    clearDayHint: 'Chưa có lịch — nhấn + để thêm hoặc tận hưởng ngày nghỉ.',
    byTheNumbers: 'THỐNG KÊ',
    workoutsDone: 'Buổi tập đã xong',
    exercisesDoneLabel: 'Bài tập đã xong',
    bestStreakLabel: 'Chuỗi dài nhất',
    lifetimeLabel: 'tổng cộng',
    // Landing page specific
    lpFitnessScheduler: 'Lên lịch thể dục',
    lpPlanGenerator: 'Tạo kế hoạch',
    lpPlanLine1: 'Một câu lệnh.',
    lpPlanLine2: 'Kế hoạch cả tuần.',
    lpSessionPush: 'Ngày đẩy',
    lpSessionRest: 'Nghỉ',
    lpSessionLower: 'Ngày chân',
    lpSessionPushTime: 'T2 · 3 hiệp · 6 bài',
    lpSessionRestTime: 'T4 · Hồi phục',
    lpSessionLowerTime: 'T6 · 4 hiệp · 5 bài',
    lpStreakTitle: 'Chuỗi',
    lpDaysInARow: 'ngày liên tiếp',
    lpLongestRun: 'Kỷ lục của bạn: 31 ngày',
    lpProgressLabel: 'Tiến độ',
    lpLast10Days: '10 ngày qua',
    lpSessionsCompleted: 'buổi tập hoàn thành',
    lpVsLastWeek: '+12% so tuần trước',
    lpBuiltDifferent: 'Khác biệt',
    lpEveryTool: 'Mọi công cụ bạn cần.',
    lpNothingYouDont: 'Không có gì thừa.',
    lpStatExercises: 'bài tập trong thư viện',
    lpStatPlans: 'kế hoạch tập tùy chỉnh',
    lpStatHike: 'theo dõi hành trình',
    lpStatStreak: 'ngày chuỗi trung bình',
    lpStartToday: 'Bắt đầu hôm nay',
    lpFooterTagline: 'Sức khỏe của bạn, được lên lịch.',
    lpMarqueeItems: [
      'Tạo kế hoạch', 'Theo dõi chuỗi', 'Theo dõi GPS',
      'Thư viện bài tập', 'Báo cáo tiến độ', 'FitTokens',
      'Kế hoạch tập', '80+ bài tập', 'Đồng bộ Google',
      'Lịch sử tập', 'Quản lý nghỉ', 'Theo dõi thói quen',
    ],
    fitnessProfile: 'HỒ SƠ THỂ DỤC',
    earnings: 'THU NHẬP',
    goalLabel: 'Mục tiêu',
    experienceLevelLabel: 'Mức kinh nghiệm',
    bodyStats: 'Số đo cơ thể',
    deleteAccount: 'Xóa tài khoản',
    typeDeleteToConfirm: 'Nhập DELETE để xác nhận',
    temporaryAccount: 'Tài khoản tạm thời',
    yourProgressIsTemporary: 'Tiến độ của bạn là tạm thời',
    profileUpdated: 'Hồ sơ đã cập nhật',
  }
}

type TranslationKey = keyof typeof translations.EN

const LanguageContext = createContext<{
  language: Lang
  t: typeof translations.EN
  cycleLanguage: () => void
  changeLanguage: (lang: Lang) => void
}>({
  language: 'EN',
  t: translations.EN,
  cycleLanguage: () => {},
  changeLanguage: () => {}
})

export function LanguageProvider({
  children
}: {
  children: React.ReactNode
}) {
  const [language, setLanguage] = useState<Lang>('EN')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Lang || 'EN'
    setLanguage(saved)
  }, [])

  const cycleLanguage = () => {
    const langs: Lang[] = ['EN', 'CN', 'JP', 'VI']
    const next = langs[(langs.indexOf(language) + 1) % langs.length]
    setLanguage(next)
    localStorage.setItem('language', next)
    document.documentElement.setAttribute('lang', next.toLowerCase())
  }

  const changeLanguage = (lang: Lang) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
    document.documentElement.setAttribute('lang', lang.toLowerCase())
  }

  return (
    <LanguageContext.Provider value={{
      language,
      t: translations[language],
      cycleLanguage,
      changeLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
