"use client"
import { createContext, useContext, useEffect, useState } from 'react'

type Lang = 'EN' | 'CN' | 'JP' | 'VI'

const translations = {
  EN: {
    yourDay: 'Your Day',
    days: {
      sun: 'Sun', mon: 'Mon', tue: 'Tue',
      wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat'
    },
    goodMorning: 'Good morning,',
    timeline: 'TIMELINE',
    noEvents: 'No events today',
    clearDay: 'Clear day \u2014 enjoy it.',
    workout: 'Workout',
    todaysPlan: "TODAY'S PLAN",
    setReminder: 'Set reminder',
    workoutIn: 'Workout in 15 minutes',
    settings: 'Settings',
    syncNow: 'Sync Now',
    disconnect: 'Disconnect',
    signOut: 'Sign Out',
    pushNotifications: 'Push Notifications',
    workoutReminders: 'Workout reminders',
    version: 'Version',
    stats: 'STATS',
    calendar: 'CALENDAR',
    preferences: 'PREFERENCES',
    workoutSetup: 'Workout setup',
    workoutSetupDescription: 'Used for exercise recommendations',
    homeWorkout: 'Home workout',
    noEquipment: 'No equipment',
    homeDumbbells: 'Home + dumbbells',
    dumbbellAccess: 'Dumbbell access',
    gym: 'Gym',
    fullEquipment: 'Full equipment',
    hike: 'Hike',
    googleConnected: 'Google Calendar connected',
    readOnly: 'Read only',
    schedule: 'Schedule',
    synced: 'Synced',
    welcomeBack: 'Welcome back',
    signInContinue: 'Sign in to continue',
    email: 'EMAIL',
    password: 'PASSWORD',
    signIn: 'Sign In',
    orContinueWith: 'or continue with',
    continueGoogle: 'Continue with Google',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    forgotPassword: 'Forgot password?',
    continueGuest: 'Continue as Guest',
    startingGuest: 'Starting guest session…',
    connect: 'Connect',

    enabled: 'Enabled',
    user: 'User',
    nameLabel: 'NAME',
    creatingAccount: 'Creating account...',
    cancel: 'Cancel',
    restDay: 'Rest Day',
    restBody: 'Rest is when your body rebuilds. Light walk recommended.',
    lightWorkoutBtn: 'Try a light workout →',
    saveToSchedule: 'Save to Schedule',
    savedToSchedule: 'Saved to schedule!',
    reminder: 'REMINDER',
    reminderSet: 'Reminder set',
    fitSched: 'FitSched',
    connectCalendar: 'Connect Calendar',
    syncDescription: 'Read-only sync to find workout windows.',
    signInWithGoogle: 'Sign in with Google',
    syncing: 'Syncing...',
    connecting: 'Connecting...',
    autoScheduled: 'Auto-scheduled',
    avgWorkout: 'Avg workout',
    decisions: 'Decisions',
    daysLabel: 'Days',
    tagline: 'Your schedule. Your pace.',
    startJourney: 'Start your journey.',
    createAccount: 'Create account',
    itsFree: "It's free, always.",
    hasAccount: 'Already have an account?',
    exercises: 'Exercises',
    add: 'Add',
    searchExercises: 'Search exercises...',
    all: 'All',
    defaultLabel: 'Default',
    noExercises: 'No exercises found',
    addExercise: 'Add Exercise',
    name: 'Name',
    description: 'Description',
    optionalDescription: 'Optional description',
    muscle: 'Muscle',
    equipment: 'Equipment',
    difficulty: 'Difficulty',
    exerciseName: 'Exercise name',
    history: 'History',
    progress: 'Progress',
    trackJourney: 'Track your workout journey',
    overview: 'Overview',
    charts: 'Charts',
    totalWorkouts: 'Total Workouts',
    totalSets: 'Total Sets',
    avgRating: 'Avg Rating',
    thisWeek: 'This Week',
    recentActivity: 'Recent Activity',
    noWorkouts: 'No workouts logged yet',
    setsPerSession: 'Sets per Session',
    noData: 'No data yet',
    ratingTrend: 'Rating Trend',
    language: 'Language',
    workoutLabel: 'WORKOUT',
    markAsDone: '✓ Mark as Done',
    workoutCompleted: '✓ Workout completed!',
    logWorkout: 'Log Workout',
    adjustReps: 'Adjust actual reps and sets completed',
    saveWorkoutLog: 'Save Workout Log',
    sets: 'SETS',
    reps: 'REPS',
    currentStreak: 'Current Streak',
    totalExercises: 'Total Exercises',
    last8Weeks: 'Last 8 Weeks',
    mostTrained: 'Most Trained',
    workoutHistory: 'WORKOUT HISTORY',
    alreadyHaveAccount: 'Already have an account?',
    addSchedule: 'Add schedule',
    editSchedule: 'Edit schedule',
    addToSchedule: 'Add to schedule',
    saveChanges: 'Save changes',
    adding: 'Adding...',
    saving: 'Saving...',
    manual: 'Manual',
    edit: 'Edit',
    delete: 'Delete',
    deleting: '...',
    goExercise: 'Go Exercise',
    exercisesCount: 'exercises',
    title: 'TITLE',
    time: 'TIME',
    optionalNotes: 'Optional notes',
    classWorkAppointment: 'Class, work, appointment...',
    workoutLockedTitle: 'Workout locked for this day',
    workoutLockedBody: 'You already completed this workout, so FitTokens are protected until the next workout day.',
    todayWorkoutOnlyTitle: "Today's workout only",
    todayWorkoutOnlyBody: 'FitTokens can only be earned from the current day, so other days are preview-only.',
    todayOnly: 'Today only',
    checkingWorkout: 'CHECKING WORKOUT',
    workoutAlreadyComplete: 'Workout already complete',
    workoutAlreadyCompleteBody: 'This day is locked so FitTokens stay fair. Come back for the next workout day.',
    noWorkoutLoaded: 'No workout loaded',
    noWorkoutLoadedBody: 'Start from the Workout tab to begin an exercise session.',
    backToWorkout: 'Back to Workout',
    back: 'Back',
    exercisesDone: 'EXERCISES DONE',
    restTime: 'Rest time',
    nowTraining: 'Now training',
    resting: 'Resting...',
    pauseTimer: 'Pause Timer',
    resumeTimer: 'Resume Timer',
    exerciseLabel: 'EXERCISE',
    setLabel: 'SET',
    ofLabel: 'OF',
    repsThisSet: 'reps this set',
    setsDone: 'sets done',
    skipRest: 'Skip Rest',
    doneSet: 'Done Set',
    finishWorkout: 'Finish Workout',
    workoutCompleteTitle: 'Workout complete',
    workoutCompleteBody: 'You showed up today. Keep this rhythm going.',
    streakLabel: 'STREAK',
    dayStreak: 'day streak',
    receiveFitToken: 'RECEIVE FITTOKEN',
    continueLabel: 'Continue',
    lpHeroLine1: 'Plan smarter.',
    lpHeroLine2: 'Train harder.',
    lpHeroBody: 'Build a full weekly workout plan around your exercises, equipment, and schedule — then track every session, streak, and hike.',
    lpSeeHow: 'See how it works',
    lpCheck1: 'Build a custom 7-day plan with 80+ exercises',
    lpCheck2: 'Track every session, streak, and rest day',
    lpCheck3: 'GPS hike tracking built in',
    lpCtaTitle: 'Your first workout plan is two minutes away.',
    lpCtaBody: 'No credit card. Just set up your plan and start training.',
    lpGetStartedFree: 'Get started free',
    setsCount: 'sets',
    showLess: 'Show less',
    showAll: 'Show all {n} workouts',
    completeFirstWorkout: 'Complete your first workout and your progress will appear here.',
    goToSchedule: 'Go to Schedule',
    freeWindow: 'Free window',
    classLabel: 'Class',
    clearDayTitle: 'Clear day',
    clearDayHint: 'Nothing scheduled — tap + to add a block or enjoy the rest.',
    byTheNumbers: 'BY THE NUMBERS',
    workoutsDone: 'Workouts done',
    exercisesDoneLabel: 'Exercises done',
    bestStreakLabel: 'Best streak',
    lifetimeLabel: 'lifetime',
    // Landing page specific
    lpFitnessScheduler: 'Fitness Scheduler',
    lpPlanGenerator: 'Plan Generator',
    lpPlanLine1: 'One prompt.',
    lpPlanLine2: 'A full week of training.',
    lpSessionPush: 'Push day',
    lpSessionRest: 'Rest',
    lpSessionLower: 'Lower body',
    lpSessionPushTime: 'Mon · 3 sets · 6 ex',
    lpSessionRestTime: 'Wed · Recovery',
    lpSessionLowerTime: 'Fri · 4 sets · 5 ex',
    lpStreakTitle: 'Streak',
    lpDaysInARow: 'days in a row',
    lpLongestRun: 'Your longest run: 31 days',
    lpProgressLabel: 'Progress',
    lpLast10Days: 'Last 10 days',
    lpSessionsCompleted: 'sessions completed',
    lpVsLastWeek: '+12% vs last week',
    lpBuiltDifferent: 'Built different',
    lpEveryTool: 'Every tool you need.',
    lpNothingYouDont: "Nothing you don't.",
    lpStatExercises: 'exercises in the library',
    lpStatPlans: 'custom workout plans',
    lpStatHike: 'hike & route tracking',
    lpStatStreak: 'average streak days',
    lpStartToday: 'Start today',
    lpFooterTagline: 'Your fitness, scheduled.',
    lpMarqueeItems: [
      'Plan Generator', 'Streak Tracking', 'GPS Hike Tracking',
      'Exercise Library', 'Progress Reports', 'FitTokens',
      'Workout Plans', '80+ Exercises', 'Google Calendar Sync',
      'Session History', 'Rest Day Logic', 'Habit Tracking',
    ],
    fitnessProfile: 'FITNESS PROFILE',
    earnings: 'EARNINGS',
    goalLabel: 'Goal',
    experienceLevelLabel: 'Experience level',
    bodyStats: 'Body stats',
    deleteAccount: 'Delete account',
    typeDeleteToConfirm: 'Type DELETE to confirm',
    temporaryAccount: 'Temporary account',
    yourProgressIsTemporary: 'Your progress is temporary',
    profileUpdated: 'Profile updated',
    todayLabel: 'Today',
    lastWorkoutLabel: 'Last workout',
    noMuscleMapYet: 'No workout logged yet — your muscle map will appear after your first session.',
    primaryLabel: 'Primary',
    secondaryLabel: 'Secondary',
    lightLabel: 'Light',
    targetLabel: 'Target',
    // Landing page — hero + sections
    lpEyebrow: 'Fitness · Tokens · Habits',
    lpHead1: 'TRAIN.',
    lpHead2: 'GET',
    lpHead3: 'REWARDED.',
    lpPerWorkout: 'per completed workout',
    lpBaseNetwork: 'Base Network · EVM',
    lpStatExercisesLabel: 'Exercises',
    lpStatPerSession: 'Per session',
    lpStatHikeTracking: 'Hike tracking',
    lpStatNoCard: 'No card needed',
    lpStatFree: 'Free',
    lpHowItWorks: 'How it works',
    lpSteps: '3 steps',
    lpStepSchedule: 'Schedule',
    lpStepScheduleDesc: 'Set your weekly training goal. FitSched builds your plan starting from day one — no wasted rest day — and adapts every session to your muscle recovery, readiness, and available equipment.',
    lpStepTrain: 'Train',
    lpStepTrainDesc: 'Follow the guided session. Device motion sensors verify each movement so every rep earns you the full token reward.',
    lpStepEarn: 'Earn',
    lpStepEarnDesc: 'Finish the session and earn FitTokens — tracked off-chain, claimable to your Base wallet. Streak bonuses stack on top.',
    lpFtPerCompleted: 'Per Completed Workout',
    lpFtTitle: 'Real crypto rewards for real effort.',
    lpFtBody: 'Every workout earns FitTokens — tracked off-chain, claimable to your Base wallet. Streak bonuses and verification multipliers mean the harder you train, the more you earn.',
    lpRewardBase: 'Base workout',
    lpRewardStreak: '7-day streak bonus',
    lpRewardVerified: 'Motion verified',
    lpFullReward: 'Full reward',
    lpFeatSmartSched: 'Smart Scheduling',
    lpFeatSmartSchedDesc: 'Plans that start the day you join and adapt to your recovery and goals — with a freshest-muscle pick whenever you want a bonus session.',
    lpFeatStreak: 'Streak System',
    lpFeatStreakDesc: "Daily streaks with rest days that don't break your run.",
    lpFeatGps: 'GPS Hike Tracking',
    lpFeatGpsDesc: 'Log outdoor hikes with live GPS route recording and elevation data.',
    lpFeatMotion: 'Motion Verification',
    lpFeatMotionDesc: 'Device sensors confirm every rep and award full token rewards.',
    lpFeatAchieve: 'Achievements',
    lpFeatAchieveDesc: 'Unlock badges and track personal records across every muscle group.',
    lpFeatCalSync: 'Calendar Sync',
    lpFeatCalSyncDesc: 'Push your workout schedule directly to Google Calendar.',
    lpCtaTitle1: 'Start training',
    lpCtaTitle2: 'today.',
    lpFreeNoCard: 'Free · No credit card',
    // Schedule — smart workout time
    smartTime: 'Smart pick',
    pickWorkoutTime: 'What time?',
    smartTimeHint: 'Based on when you usually train',
    // Landing page phone mockups
    lpmPushDay: 'Push Day',
    lpmChestShoulders: 'Chest & Shoulders',
    lpmRecovery: 'Recovery',
    lpmSetsReps: 'of 4 sets · 8 reps',
    lpmRest: 'REST · 00:48',
    lpmCompleteSet: 'Complete Set',
    lpmRecent: 'Recent',
    lpmThisWeek: 'this week',
    lpmLegDay: 'Leg Day',
    lpmSquats: 'Squats & Deadlifts',
    lpmTrail: 'Riverside Trail',
    lpmYesterday: 'Yesterday',
    lpm2days: '2 days ago',
    lpm3days: '3 days ago',
    lpmMuChest: 'Chest',
    lpmMuBack: 'Back',
    lpmMuLegs: 'Legs',
    lpmMuArms: 'Arms',
    lpmMuCore: 'Core',
    // Forgot-password page
    fpRecovery: 'Password recovery',
    fpForgotTitle: 'Forgot password?',
    fpEnterEmail: "Enter your email and we'll send you a reset link.",
    fpSendLink: 'Send reset link',
    fpSending: 'Sending…',
    fpRememberIt: 'Remember it?',
    fpError: 'Something went wrong. Please try again.',
    fpGoogleTitle: 'Google account',
    fpGoogleBody: "is linked to a Google account. You don't need a password — just sign in with Google.",
    fpCheckTitle: 'Check your email',
    fpCheckPre: 'If',
    fpCheckPost: "has a FitSched account, you'll receive a reset link shortly. The link expires in 1 hour.",
    fpDidntGet: "Didn't get it? Check your spam folder or",
    fpTryAgain: 'try again',
    fpBackSignin: 'Back to sign in',
    // Auth pages (login + register)
    authIncorrect: 'Email or password is incorrect',
    authGuestError: 'Could not start guest session. Please try again.',
    authSigningIn: 'Signing in…',
    regEmailTaken: 'Email already registered or password too weak',
    regNamePlaceholder: 'Your name',
    regPwPlaceholder: 'Min 8 characters',
    authAgreePre: 'I have read and agree to the',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    andLabel: 'and',
    authGoogleAgree: 'By continuing with Google you agree to our',
    termsShort: 'Terms',
    // Settings page
    setFtBalance: 'FitTokens balance',
    setEarnedFrom: 'Earned from workouts',
    setWithdraw: 'Withdraw',
    setGoogleCal: 'Google Calendar',
    setCalSub: 'Read-only · sync nightly',
    setConnecting: 'Connecting…',
    setOn: 'On',
    setOff: 'Off',
    setTapSync: 'Tap to sync',
    setLastPrefix: 'Last',
    setGoalLose: 'Lose Weight',
    setGoalBuild: 'Build Muscle',
    setGoalActive: 'Stay Active',
    setGoalEndurance: 'Endurance',
    setLvlBeginner: 'Beginner',
    setLvlBeginnerSub: 'Just starting',
    setLvlInter: 'Intermediate',
    setLvlInterSub: 'Some experience',
    setLvlAdv: 'Advanced',
    setLvlAdvSub: 'Well-trained',
    setHeight: 'Height',
    setWeight: 'Weight',
    setEnvHome: 'Home',
    setEnvHomeSub: 'Bodyweight',
    setEnvDbs: '+ DBs',
    setEnvDbsSub: 'Dumbbells',
    setEnvGym: 'Gym',
    setEnvGymSub: 'Full kit',
    setPerWeek: 'Workouts per week',
    setPerWeekUnit: '× / wk',
    setExLibrary: 'Exercise Library',
    setExLibrarySub: 'Browse & manage exercises',
    setNotifications: 'Notifications',
    setUpdating: 'Updating…',
    setAppearance: 'Appearance',
    setDarkMode: 'Dark mode',
    setLightMode: 'Light mode',
    setGuestBody: 'Guest accounts are not saved. Create a free account to keep your streak, workouts, and FitTokens.',
    setCreateFree: 'Create a free account',
    setDeleteTitle: 'Delete your account?',
    setDeleteBody: 'This permanently deletes your profile, workout history, streak, and FitTokens. There is no undo.',
    setDeleting: 'Deleting…',
    justNow: 'Just now',
    minsAgoSuffix: 'min ago',
    hoursAgoSuffix: 'h ago',
    // Profile page
    profTitle: 'Profile',
    profTapName: 'Tap to set name',
    profSaving: 'saving…',
    profJoined: 'Joined',
    profGuestCta: 'Create a free account to save your progress →',
    profOf: 'of',
    profSessions: 'sessions',
    profBody: 'Body',
    bmiUnder: 'Underweight',
    bmiNormal: 'Normal',
    bmiOver: 'Overweight',
    bmiObese: 'Obese',
    profWeightTrend: 'Weight trend',
    profNoChange: 'No change',
    profSinceFirst: 'since first entry',
    profEntries: 'entries',
    profWeightLog: 'Weight Log',
    profWeightLogSub: 'Track your body weight over time',
    profHikeLogs: 'Hike Logs',
    profHikes: 'hikes',
    profKmTotal: 'km total',
    profAchievements: 'Achievements',
    profUnlocked: 'Unlocked',
    profNotUnlocked: 'Not yet unlocked',
    // Muscle groups (shared)
    muAll: 'All',
    muChest: 'Chest',
    muBack: 'Back',
    muLegs: 'Legs',
    muShoulders: 'Shoulders',
    muArms: 'Arms',
    muCore: 'Core',
    // History page
    hPrs: 'PRs',
    hKgMax: 'kg max',
    hNotePlaceholder: 'Add a note about this session…',
    hSaveNote: 'Save note',
    hTapNote: 'Tap to add a note…',
    hDeleting: 'Deleting…',
    hDeleteLog: 'Delete log',
    hNoFilteredWorkouts: 'No workouts for this filter yet',
    hExPerSession: 'Exercises per session',
    hPrEmpty: 'Complete workouts with weights to track your PRs',
    hSessions: 'sessions',
    hReps: 'reps',
    hBest: 'BEST',
    hProgression: 'PROGRESSION',
    hRepsLabel: 'Reps',
    muFullBody: 'Full Body',
    muCardio: 'Cardio',
    // Report / Progress page
    rStreakBonus: 'Streak bonus',
    rWorkout: 'Workout',
    rBoostSuffix: '(2× boost)',
    rDay: 'day',
    rDays: 'days',
    rPersonalBest: 'Personal best',
    rMusclesHit: 'Muscles Hit',
    rRecovery: 'Recovery',
    rActivity: 'Activity',
    rFtEarnings: 'FitToken earnings',
    rFtEmpty: 'Complete a workout to earn your first FitToken.',
    rCaloriesBurned: 'CALORIES BURNED (8 WEEKS)',
    rKcalTotal: 'kcal total',
    rCalories: 'Calories',
    rHikeStats: 'HIKE STATS',
    rHikes: 'Hikes',
    rDistance: 'Distance',
    rTime: 'Time',
    rViewAllHikes: 'View all hikes',
    rTotal: 'total',
    rSearchWorkouts: 'Search workouts…',
    rNoMatching: 'No workouts matching',
    rLoadedToday: 'Loaded for today!',
    rLoading: 'Loading…',
    rRepeatToday: 'Repeat today',
    // Exercise descriptions
    descInclinePush: 'Beginner-friendly push-up using an elevated surface.',
    descPushup: 'A bodypress that trains chest, triceps, shoulders, and core.',
    descShoulderTap: 'A push-up followed by alternating shoulder taps.',
    descDiamond: 'Close-grip push-up targeting triceps and inner chest.',
    descTricepDip: 'Dip movement for tricep isolation and shoulder stability.',
    descPullup: 'Vertical pull targeting lats, biceps, and upper back.',
    descBicepCurl: 'Isolation movement for bicep peak and arm strength.',
    descSquat: 'Compound lower-body movement for quads, glutes, and hips.',
    descLunge: 'Unilateral leg exercise for balance and quad development.',
    descPlank: 'Isometric core hold building total trunk stability.',
    descBurpee: 'Full-body explosive movement combining squat, push-up, and jump.',
    descLateralRaise: 'Isolation movement for medial deltoid width.',
    descRussianTwist: 'Rotational core movement targeting obliques.',
    descMountainClimb: 'Dynamic core exercise with cardio benefit.',
    descDefault: 'Compound movement for strength and endurance.',
    // Workout + schedule
    wWeeklyGoal: 'Weekly goal',
    wComputing: 'Computing…',
    wMin: 'min',
    wMedium: 'medium',
    wTemplates: 'Templates',
    wTemplateActive: 'Template active —',
    wReset: 'Reset',
    wTrainAgain: 'Train again',
    scBestWindow: 'Best window',
    scOptimalWindow: 'Optimal energy window',
    scStart: 'Start',
    scStartArrow: 'Start →',
    scTodayOnly: 'Today only',
    scMorning: 'Morning',
    scMorningSub: 'Before noon',
    scAfternoon: 'Afternoon',
    scAfternoonSub: '12 – 5 PM',
    scEvening: 'Evening',
    scEveningSub: 'After 5 PM',
    scScheduleGroup: 'Schedule',
    scMinShort: 'min',
    // Exercise session
    exTodaysWorkout: "TODAY'S WORKOUT",
    exOneShot: 'One shot only — exit means no FitTokens today',
    exLetsGo: "Let's Go",
    exTrackTitle: 'Track your movement',
    exTrackBody: "FitSched uses your device's motion sensors to verify your workout and award full FitTokens. Your data never leaves your device.",
    exEnableMotion: 'Enable Motion Tracking',
    exSkip50: 'Skip — earn 50% FitTokens',
    exTodaysWorkoutLower: "Today's workout",
    exVerified: 'VERIFIED',
    exUnverified: 'UNVERIFIED',
    exSwap: 'Swap',
    exLast: 'Last:',
    exRound: 'ROUND',
    exOf: '/',
    exSet: 'Set',
    exAllSetsDone: 'All sets done',
    exCompleteSet: 'Complete set',
    exCamAuto: 'Count reps with camera',
    exCamBeta: 'Beta',
    exCamStarting: 'Starting camera…',
    exCamDenied: 'Camera unavailable — check permissions and try again.',
    exCamTip: 'Prop your phone up so your whole body is in view',
    exCamStop: 'Stop camera',
    exOfLower: 'of',
    exUpNext: 'Up next',
    exSwapHeader: 'SWAP',
    exNoAlts: 'No alternatives available',
    exQuitTitle: 'Quit workout?',
    exQuitPre: 'You only get',
    exQuitBold: 'one chance per day',
    exQuitPost: '. Leaving now means no FitTokens today and no re-entry until tomorrow.',
    exKeepGoing: 'Keep going',
    exQuitLose: 'Quit & lose it',
    exRest: 'Rest',
    exSec: 'sec',
    exSkip: 'Skip',
    exStatTime: 'Time',
    exStatExercises: 'Exercises',
    exStatSets: 'Sets',
    exStatReps: 'Reps',
    exEstCalories: 'EST. CALORIES',
    exYouReceived: 'YOU RECEIVED',
    exPartialReward: 'Partial reward — tap Verify next time for full +1.0 FT',
    exNoTokens: 'No tokens this session — workout was too fast to verify',
    exPersonalRecords: 'PERSONAL RECORDS',
    exWas: 'was',
    exFirstTime: 'First time logged!',
    exHowFeel: 'HOW DID IT FEEL?',
    exFbEasy: 'Too easy',
    exFbEasyD: 'Add challenge',
    exFbJust: 'Just right',
    exFbJustD: 'Keep pace',
    exFbHard: 'Too hard',
    exFbHardD: 'Scale back',
    exFbSaved: 'Feedback saved for future recommendations.',
    exSessionNotes: 'SESSION NOTES',
    exNotePlaceholder: 'How did it go? PR? Something to remember…',
    exSaved: 'Saved',
    exAchUnlocked: 'ACHIEVEMENT UNLOCKED',
    exExitedTitle: "You already exited today's session",
    exExitedBody: 'Come back tomorrow for a fresh workout and full FitToken reward.',
    exGoExercise: 'Go Exercise',
    exToday: 'today',
    exYesterday: 'yesterday',
    exDaysAgo: 'd ago',
    // Hike page
    hkLogs: 'Logs',
    hkHikes: 'hikes',
    hkPendingSync: 'pending sync',
    hkSavedOffline: 'Saved offline — will sync when connected',
    hkFtEarned: 'FT earned',
    hkKmExcluded: 'km excluded — speed too high for walking',
    hkSaveTitle: 'Save your hike',
    hkTrailName: 'Trail name',
    hkTrailPlaceholder: 'e.g. Bukit Timah Hill',
    hkLocation: 'Location',
    hkLocationPlaceholder: 'e.g. Bukit Timah Nature Reserve',
    hkNotes: 'Notes',
    hkNotesPlaceholder: 'How was it?',
    hkSaving: 'Saving…',
    hkSaveHike: 'Save hike',
    hkHikeLogs: 'Hike logs',
    hkChipHikes: 'Hikes',
    hkChipDistance: 'Distance',
    hkChipElevation: 'Elevation',
    hkChipTime: 'Time',
    hkLoading: 'Loading…',
    hkNoHikes: 'No hikes logged yet.',
    // Weight page
    wtGoal: 'Goal:',
    wtLogWeight: 'Log weight',
    wtSetGoalTitle: 'Set weight goal',
    wtGoalDesc: 'Set a target weight to track your progress toward your goal.',
    wtEg: 'e.g.',
    wtClearGoal: 'Clear goal',
    wtSetGoal: 'Set goal',
    wtNewEntry: 'NEW ENTRY',
    wtSave: 'Save',
    wtNotePlaceholder: 'Optional note (e.g. post-run)',
    wtLastLogged: 'Last logged',
    wtVsPrev: 'vs PREV',
    wtToGo: 'to go',
    wtReached: 'reached',
    wtGoalShort: 'Goal',
    wtNoEntries: 'No entries yet',
    wtEmptyHint: 'Tap "Log weight" to start tracking your progress.',
    wtEntry: 'entry',
    // Withdrawal page
    wdSubtitle: 'Earn FIT by working out. Claim to your Base wallet.',
    wdYourWallet: 'Your Wallet',
    wdBaseNetwork: 'Base network (EVM)',
    wdChange: 'Change',
    wdSaved: 'Saved',
    wdEnterNew: 'Enter a new Base wallet address:',
    wdPasteAddr: 'Paste your Base wallet address to receive FIT when you claim:',
    wdSave: 'Save',
    wdWalletHint: 'Only Base (chainId 8453) addresses are supported. Never share your private key.',
    wdFtBalance: 'FitToken Balance',
    wdLiveOnBase: 'Live on Base',
    wdOffchain: 'Off-chain · Launching on Base',
    wdLive: 'LIVE',
    wdClaimedExcl: 'claimed!',
    wdTokensSent: 'Tokens sent to your Base wallet.',
    wdOnchainBalance: 'On-chain balance:',
    wdViewBasescan: 'View on Basescan',
    wdClaimableBalance: 'Claimable balance',
    wdAlreadyClaimed: 'already claimed',
    wdTotalEarned: 'TOTAL EARNED',
    wdOnChain: 'ON-CHAIN',
    wdClaimedLabel: 'CLAIMED',
    wdProgressMin: 'Progress to minimum claim',
    wdMoreToGo: 'more FIT to go',
    wdHowEarn: 'How you earn',
    wdEarn1: 'Complete a workout',
    wdEarn1d: '+1.00 FT per session',
    wdEarn2: 'Streak bonus',
    wdEarn2d: 'Up to +0.20 FT extra',
    wdEarn3: 'Verification score',
    wdEarn3d: 'Full score = full reward',
    wdClaimHistory: 'Claim history',
    wdRecentEarnings: 'Recent earnings',
    wdActionWithdraw: 'withdraw FIT',
    wdActionWallet: 'change your wallet',
    wdReasonWorkout: 'Workout completed',
    wdSetWalletFirst: 'Set wallet address first',
    wdNoFitYet: 'No FIT to claim yet',
    wdNeedMinPre: 'Need',
    wdNeedMinPost: 'FIT minimum',
    wdClaim: 'Claim',
    wdLaunchingSoon: 'LAUNCHING SOON',
    wdClaiming: 'Claiming…',
    wdClaimedBtn: 'Claimed',
    wdLaunchNote1: 'The FitToken contract is not yet live on Base. Your balance is safe and will be claimable once it launches.',
    wdLaunchNote2pre: 'Your',
    wdLaunchNote2post: 'FIT is safe and will be claimable once the contract is live on Base.',
    wdErrGeneric: 'Something went wrong. Please try again.',
    wdErrNetwork: 'Network error — please try again',
    // Exercise library
    exLibEdit: 'Edit Exercise',
    eqBodyweight: 'Bodyweight',
    eqDumbbells: 'Dumbbells',
    eqBarbell: 'Barbell',
    eqMachine: 'Machine',
    eqCables: 'Cables',
    eqBands: 'Bands',
    eqKettlebell: 'Kettlebell',
    workoutNames: {
      'Chest & Triceps':  'Chest & Triceps',
      'Back & Biceps':    'Back & Biceps',
      'Shoulders & Core': 'Shoulders & Core',
      'Arms & Core':      'Arms & Core',
      'Legs':             'Legs',
      'Full Body':        'Full Body',
      'Rest':             'Rest',
    },
  },
  CN: {
    yourDay: '你的一天',
    days: {
      sun: '周日', mon: '周一', tue: '周二',
      wed: '周三', thu: '周四', fri: '周五', sat: '周六'
    },
    goodMorning: '早上好，',
    timeline: '时间线',
    noEvents: '今天没有活动',
    clearDay: '轻松的一天 \u2014 好好享受。',
    workout: '锻炼',
    todaysPlan: '今日计划',
    setReminder: '设置提醒',
    workoutIn: '15分钟后锻炼',
    settings: '设置',
    syncNow: '立即同步',
    disconnect: '断开连接',
    signOut: '退出登录',
    pushNotifications: '推送通知',
    workoutReminders: '锻炼提醒',
    version: '版本',
    stats: '统计',
    calendar: '日历',
    preferences: '偏好设置',
    workoutSetup: '\u8bad\u7ec3\u8bbe\u7f6e',
    workoutSetupDescription: '\u7528\u4e8e\u8fd0\u52a8\u63a8\u8350',
    homeWorkout: '\u5c45\u5bb6\u8bad\u7ec3',
    noEquipment: '\u65e0\u9700\u5668\u6750',
    homeDumbbells: '\u5c45\u5bb6 + \u54d1\u94c3',
    dumbbellAccess: '\u53ef\u4f7f\u7528\u54d1\u94c3',
    gym: '\u5065\u8eab\u623f',
    fullEquipment: '\u5b8c\u6574\u5668\u6750',
    hike: '\u5f92\u6b65',
    googleConnected: 'Google日历已连接',
    readOnly: '只读',
    schedule: '日程',
    synced: '已同步',
    welcomeBack: '欢迎回来',
    signInContinue: '登录以继续',
    email: '邮箱',
    password: '密码',
    signIn: '登录',
    orContinueWith: '或继续使用',
    continueGoogle: '使用Google继续',
    noAccount: '没有账号？',
    signUp: '注册',
    forgotPassword: '忘记密码？',
    continueGuest: '以访客身份继续',
    startingGuest: '正在启动访客会话…',
    connect: '连接',

    enabled: '已启用',
    user: '用户',
    nameLabel: '名称',
    creatingAccount: '正在创建账户...',
    cancel: '取消',
    restDay: '休息日',
    restBody: '休息是身体重建的时候。建议轻度散步。',
    lightWorkoutBtn: '试试轻度锻炼 →',
    saveToSchedule: '保存到日程',
    savedToSchedule: '已保存到日程！',
    reminder: '提醒',
    reminderSet: '已设置提醒',
    fitSched: 'FitSched',
    connectCalendar: '连接日历',
    syncDescription: '只读同步以查找锻炼窗口。',
    signInWithGoogle: '使用Google登录',
    syncing: '同步中...',
    connecting: '连接中...',
    autoScheduled: '自动安排',
    avgWorkout: '平均锻炼',
    decisions: '决策',
    daysLabel: '天',
    tagline: '你的日程。你的节奏。',
    startJourney: '开始你的旅程。',
    createAccount: '创建账户',
    itsFree: '永久免费。',
    hasAccount: '已有账号？',
    exercises: '动作库',
    add: '添加',
    searchExercises: '搜索动作...',
    all: '全部',
    defaultLabel: '默认',
    noExercises: '未找到动作',
    addExercise: '添加动作',
    name: '名称',
    description: '描述',
    optionalDescription: '可选描述',
    muscle: '肌肉',
    equipment: '器材',
    difficulty: '难度',
    exerciseName: '动作名称',
    history: '历史',
    progress: '进度',
    trackJourney: '跟踪你的锻炼旅程',
    overview: '概览',
    charts: '图表',
    totalWorkouts: '总锻炼',
    totalSets: '总组数',
    avgRating: '平均评分',
    thisWeek: '本周',
    recentActivity: '最近活动',
    noWorkouts: '尚无锻炼记录',
    setsPerSession: '每组组数',
    noData: '暂无数据',
    ratingTrend: '评分趋势',
    language: '语言',
    workoutLabel: '锻炼',
    markAsDone: '✓ 标记完成',
    workoutCompleted: '✓ 锻炼完成！',
    logWorkout: '记录锻炼',
    adjustReps: '调整实际完成的组数和次数',
    saveWorkoutLog: '保存锻炼记录',
    sets: '组数',
    reps: '次数',
    currentStreak: '当前连续',
    totalExercises: '总动作数',
    last8Weeks: '最近8周',
    mostTrained: '最常训练',
    workoutHistory: '锻炼历史',
    alreadyHaveAccount: '已有账号？',
    addSchedule: '添加日程',
    editSchedule: '编辑日程',
    addToSchedule: '添加到日程',
    saveChanges: '保存更改',
    adding: '添加中...',
    saving: '保存中...',
    manual: '手动',
    edit: '编辑',
    delete: '删除',
    deleting: '...',
    goExercise: '开始锻炼',
    exercisesCount: '个动作',
    title: '标题',
    time: '时间',
    optionalNotes: '可选备注',
    classWorkAppointment: '课程、工作、约会...',
    workoutLockedTitle: '今天的锻炼已锁定',
    workoutLockedBody: '你已经完成了这次锻炼，所以 FitToken 会保护到下一个锻炼日。',
    todayWorkoutOnlyTitle: '只能完成今天的锻炼',
    todayWorkoutOnlyBody: 'FitToken 只能通过当天锻炼获得，其他日期只能预览。',
    todayOnly: '仅限今天',
    checkingWorkout: '正在检查锻炼',
    workoutAlreadyComplete: '锻炼已完成',
    workoutAlreadyCompleteBody: '这一天已锁定，确保 FitToken 公平。下一个锻炼日再回来吧。',
    noWorkoutLoaded: '没有载入锻炼',
    noWorkoutLoadedBody: '请从“锻炼”页面开始一次训练。',
    backToWorkout: '返回锻炼',
    back: '返回',
    exercisesDone: '个动作已完成',
    restTime: '休息时间',
    nowTraining: '正在训练',
    resting: '休息中...',
    pauseTimer: '暂停计时',
    resumeTimer: '继续计时',
    exerciseLabel: '动作',
    setLabel: '组',
    ofLabel: '共',
    repsThisSet: '次本组',
    setsDone: '组已完成',
    skipRest: '跳过休息',
    doneSet: '完成本组',
    finishWorkout: '完成锻炼',
    workoutCompleteTitle: '锻炼完成',
    workoutCompleteBody: '你今天坚持了。继续保持这个节奏。',
    streakLabel: '连续',
    dayStreak: '天连续',
    receiveFitToken: '领取 FITTOKEN',
    continueLabel: '继续',
    lpHeroLine1: '更智慧地规划。',
    lpHeroLine2: '更努力地训练。',
    lpHeroBody: '围绕你的运动、器材和日程，制定完整的每周训练计划——然后跟踪每次训练、连续打卡和徒步。',
    lpSeeHow: '了解更多',
    lpCheck1: '用80+个动作定制7天计划',
    lpCheck2: '跟踪每次训练、连续打卡和休息日',
    lpCheck3: '内置GPS徒步追踪',
    lpCtaTitle: '两分钟内生成你的第一份训练计划。',
    lpCtaBody: '无需信用卡。只需设置你的计划并开始训练。',
    lpGetStartedFree: '免费开始',
    setsCount: '组',
    showLess: '收起',
    showAll: '显示全部 {n} 次训练',
    completeFirstWorkout: '完成第一次训练后，你的进度将显示在这里。',
    goToSchedule: '前往日程',
    freeWindow: '空闲时间',
    classLabel: '课程',
    clearDayTitle: '轻松一天',
    clearDayHint: '没有安排 — 点击 + 添加，或好好休息。',
    byTheNumbers: '数据统计',
    workoutsDone: '已完成锻炼',
    exercisesDoneLabel: '已完成动作',
    bestStreakLabel: '最佳连续',
    lifetimeLabel: '总计',
    // Landing page specific
    lpFitnessScheduler: '健身计划助手',
    lpPlanGenerator: '智能计划',
    lpPlanLine1: '一句话，',
    lpPlanLine2: '生成完整周计划。',
    lpSessionPush: '推胸日',
    lpSessionRest: '休息',
    lpSessionLower: '下肢日',
    lpSessionPushTime: '周一 · 3组 · 6个动作',
    lpSessionRestTime: '周三 · 恢复',
    lpSessionLowerTime: '周五 · 4组 · 5个动作',
    lpStreakTitle: '连续',
    lpDaysInARow: '天连续',
    lpLongestRun: '最长连续：31天',
    lpProgressLabel: '进度',
    lpLast10Days: '最近10天',
    lpSessionsCompleted: '次训练完成',
    lpVsLastWeek: '+12% vs 上周',
    lpBuiltDifferent: '与众不同',
    lpEveryTool: '你所需要的一切工具。',
    lpNothingYouDont: '没有多余的。',
    lpStatExercises: '个动作库',
    lpStatPlans: '定制训练计划',
    lpStatHike: '徒步路线追踪',
    lpStatStreak: '平均连续天数',
    lpStartToday: '今天开始',
    lpFooterTagline: '你的健身，已规划。',
    lpMarqueeItems: [
      '智能计划', '连续追踪', 'GPS徒步追踪',
      '动作库', '进度报告', 'FitTokens',
      '训练计划', '80+个动作', 'Google日历同步',
      '训练历史', '休息日管理', '习惯追踪',
    ],
    fitnessProfile: '健身档案',
    earnings: '收益',
    goalLabel: '目标',
    experienceLevelLabel: '经验等级',
    bodyStats: '身体数据',
    deleteAccount: '删除账户',
    typeDeleteToConfirm: '输入 DELETE 以确认',
    temporaryAccount: '临时账户',
    yourProgressIsTemporary: '您的进度是临时的',
    profileUpdated: '档案已更新',
    todayLabel: '今天',
    lastWorkoutLabel: '上次锻炼',
    noMuscleMapYet: '尚未记录锻炼 — 完成首次训练后将显示肌肉图。',
    primaryLabel: '主要',
    secondaryLabel: '次要',
    lightLabel: '轻微',
    targetLabel: '目标',
    // Landing page — hero + sections
    lpEyebrow: '健身 · 代币 · 习惯',
    lpHead1: '训练。',
    lpHead2: '赢得',
    lpHead3: '奖励。',
    lpPerWorkout: '每次完成的锻炼',
    lpBaseNetwork: 'Base 网络 · EVM',
    lpStatExercisesLabel: '动作',
    lpStatPerSession: '每次训练',
    lpStatHikeTracking: '徒步追踪',
    lpStatNoCard: '无需银行卡',
    lpStatFree: '免费',
    lpHowItWorks: '如何运作',
    lpSteps: '3 步',
    lpStepSchedule: '安排',
    lpStepScheduleDesc: '设定每周训练目标。FitSched 从第一天起为你制定计划——不浪费任何休息日——并根据你的肌肉恢复、状态和可用器材调整每次训练。',
    lpStepTrain: '训练',
    lpStepTrainDesc: '跟随引导式训练。设备的运动传感器会验证每个动作，让每一次重复都能获得完整的代币奖励。',
    lpStepEarn: '赚取',
    lpStepEarnDesc: '完成训练即可赚取 FitToken——链下记录，可领取到你的 Base 钱包。连续打卡奖励还会叠加。',
    lpFtPerCompleted: '每次完成的锻炼',
    lpFtTitle: '真实的努力，真实的加密奖励。',
    lpFtBody: '每次锻炼都能赚取 FitToken——链下记录，可领取到你的 Base 钱包。连续打卡奖励和验证倍数意味着你越努力，赚得越多。',
    lpRewardBase: '基础锻炼',
    lpRewardStreak: '7天连续奖励',
    lpRewardVerified: '运动已验证',
    lpFullReward: '完整奖励',
    lpFeatSmartSched: '智能安排',
    lpFeatSmartSchedDesc: '从你加入当天开始的计划，并根据你的恢复和目标调整——想加练时还能为你挑选最有活力的肌群。',
    lpFeatStreak: '连续打卡系统',
    lpFeatStreakDesc: '每日连续打卡，休息日不会中断你的纪录。',
    lpFeatGps: 'GPS 徒步追踪',
    lpFeatGpsDesc: '记录户外徒步，实时 GPS 路线记录与海拔数据。',
    lpFeatMotion: '运动验证',
    lpFeatMotionDesc: '设备传感器确认每个动作，给予完整代币奖励。',
    lpFeatAchieve: '成就',
    lpFeatAchieveDesc: '解锁徽章，记录每个肌群的个人最佳。',
    lpFeatCalSync: '日历同步',
    lpFeatCalSyncDesc: '将你的训练日程直接推送到 Google 日历。',
    lpCtaTitle1: '今天就开始',
    lpCtaTitle2: '训练。',
    lpFreeNoCard: '免费 · 无需信用卡',
    // Schedule — smart workout time
    smartTime: '智能选择',
    pickWorkoutTime: '什么时间？',
    smartTimeHint: '根据你平时训练的时间',
    // Landing page phone mockups
    lpmPushDay: '推胸日',
    lpmChestShoulders: '胸部 & 肩部',
    lpmRecovery: '恢复',
    lpmSetsReps: '共4组 · 8次',
    lpmRest: '休息 · 00:48',
    lpmCompleteSet: '完成本组',
    lpmRecent: '最近',
    lpmThisWeek: '本周',
    lpmLegDay: '腿部日',
    lpmSquats: '深蹲 & 硬拉',
    lpmTrail: '河滨步道',
    lpmYesterday: '昨天',
    lpm2days: '2天前',
    lpm3days: '3天前',
    lpmMuChest: '胸',
    lpmMuBack: '背',
    lpmMuLegs: '腿',
    lpmMuArms: '臂',
    lpmMuCore: '核心',
    // Forgot-password page
    fpRecovery: '找回密码',
    fpForgotTitle: '忘记密码？',
    fpEnterEmail: '输入你的邮箱，我们会发送重置链接给你。',
    fpSendLink: '发送重置链接',
    fpSending: '发送中…',
    fpRememberIt: '想起来了？',
    fpError: '出错了，请重试。',
    fpGoogleTitle: 'Google 账户',
    fpGoogleBody: '已关联到 Google 账户。你无需密码——直接用 Google 登录即可。',
    fpCheckTitle: '请查收邮件',
    fpCheckPre: '若',
    fpCheckPost: '拥有 FitSched 账户，你将很快收到重置链接。链接将在 1 小时后失效。',
    fpDidntGet: '没有收到？请检查垃圾邮件文件夹，或',
    fpTryAgain: '重试',
    fpBackSignin: '返回登录',
    // Auth pages (login + register)
    authIncorrect: '邮箱或密码不正确',
    authGuestError: '无法开始访客会话，请重试。',
    authSigningIn: '登录中…',
    regEmailTaken: '邮箱已注册或密码强度不足',
    regNamePlaceholder: '你的名字',
    regPwPlaceholder: '至少8个字符',
    authAgreePre: '我已阅读并同意',
    termsOfService: '服务条款',
    privacyPolicy: '隐私政策',
    andLabel: '和',
    authGoogleAgree: '继续使用 Google 即表示你同意我们的',
    termsShort: '条款',
    // Settings page
    setFtBalance: 'FitToken 余额',
    setEarnedFrom: '通过锻炼获得',
    setWithdraw: '提现',
    setGoogleCal: 'Google 日历',
    setCalSub: '只读 · 每晚同步',
    setConnecting: '连接中…',
    setOn: '开',
    setOff: '关',
    setTapSync: '点击同步',
    setLastPrefix: '上次',
    setGoalLose: '减脂',
    setGoalBuild: '增肌',
    setGoalActive: '保持活力',
    setGoalEndurance: '耐力',
    setLvlBeginner: '初学者',
    setLvlBeginnerSub: '刚刚开始',
    setLvlInter: '中级',
    setLvlInterSub: '有些经验',
    setLvlAdv: '高级',
    setLvlAdvSub: '训练有素',
    setHeight: '身高',
    setWeight: '体重',
    setEnvHome: '居家',
    setEnvHomeSub: '徒手',
    setEnvDbs: '+ 哑铃',
    setEnvDbsSub: '哑铃',
    setEnvGym: '健身房',
    setEnvGymSub: '全套器材',
    setPerWeek: '每周锻炼次数',
    setPerWeekUnit: '次 / 周',
    setExLibrary: '动作库',
    setExLibrarySub: '浏览和管理动作',
    setNotifications: '通知',
    setUpdating: '更新中…',
    setAppearance: '外观',
    setDarkMode: '深色模式',
    setLightMode: '浅色模式',
    setGuestBody: '访客账户不会被保存。创建免费账户以保留你的连续打卡、锻炼记录和 FitToken。',
    setCreateFree: '创建免费账户',
    setDeleteTitle: '删除你的账户？',
    setDeleteBody: '这将永久删除你的档案、锻炼历史、连续打卡和 FitToken。无法撤销。',
    setDeleting: '删除中…',
    justNow: '刚刚',
    minsAgoSuffix: '分钟前',
    hoursAgoSuffix: '小时前',
    // Profile page
    profTitle: '个人',
    profTapName: '点击设置名称',
    profSaving: '保存中…',
    profJoined: '加入于',
    profGuestCta: '创建免费账户以保存你的进度 →',
    profOf: '/',
    profSessions: '次',
    profBody: '身体',
    bmiUnder: '偏瘦',
    bmiNormal: '正常',
    bmiOver: '偏重',
    bmiObese: '肥胖',
    profWeightTrend: '体重趋势',
    profNoChange: '无变化',
    profSinceFirst: '自首次记录',
    profEntries: '条记录',
    profWeightLog: '体重记录',
    profWeightLogSub: '长期追踪你的体重',
    profHikeLogs: '徒步记录',
    profHikes: '次徒步',
    profKmTotal: '公里 总计',
    profAchievements: '成就',
    profUnlocked: '已解锁',
    profNotUnlocked: '尚未解锁',
    // Muscle groups (shared)
    muAll: '全部',
    muChest: '胸部',
    muBack: '背部',
    muLegs: '腿部',
    muShoulders: '肩部',
    muArms: '手臂',
    muCore: '核心',
    // History page
    hPrs: '纪录',
    hKgMax: '公斤 最大',
    hNotePlaceholder: '为这次训练添加备注…',
    hSaveNote: '保存备注',
    hTapNote: '点击添加备注…',
    hDeleting: '删除中…',
    hDeleteLog: '删除记录',
    hNoFilteredWorkouts: '该筛选下暂无锻炼',
    hExPerSession: '每次训练的动作数',
    hPrEmpty: '完成带重量的锻炼以追踪你的纪录',
    hSessions: '次训练',
    hReps: '次',
    hBest: '最佳',
    hProgression: '进展',
    hRepsLabel: '次数',
    muFullBody: '全身',
    muCardio: '有氧',
    // Report / Progress page
    rStreakBonus: '连续奖励',
    rWorkout: '锻炼',
    rBoostSuffix: '(2× 加成)',
    rDay: '天',
    rDays: '天',
    rPersonalBest: '个人最佳',
    rMusclesHit: '锻炼部位',
    rRecovery: '恢复',
    rActivity: '活动',
    rFtEarnings: 'FitToken 收益',
    rFtEmpty: '完成一次锻炼即可获得你的第一个 FitToken。',
    rCaloriesBurned: '消耗热量（8 周）',
    rKcalTotal: '千卡 总计',
    rCalories: '热量',
    rHikeStats: '徒步统计',
    rHikes: '徒步',
    rDistance: '距离',
    rTime: '时间',
    rViewAllHikes: '查看全部徒步',
    rTotal: '总计',
    rSearchWorkouts: '搜索锻炼…',
    rNoMatching: '没有匹配的锻炼',
    rLoadedToday: '已载入到今天！',
    rLoading: '载入中…',
    rRepeatToday: '今天重复',
    // Exercise descriptions
    descInclinePush: '利用高处支撑的初学者友好俯卧撑。',
    descPushup: '锻炼胸部、三头肌、肩部和核心的推压动作。',
    descShoulderTap: '俯卧撑后交替拍肩。',
    descDiamond: '窄距俯卧撑，针对三头肌和内侧胸肌。',
    descTricepDip: '臂屈伸动作，孤立三头肌并稳定肩部。',
    descPullup: '垂直拉起，针对背阔肌、二头肌和上背。',
    descBicepCurl: '孤立动作，塑造二头肌峰和手臂力量。',
    descSquat: '下肢复合动作，针对股四头肌、臀部和髋部。',
    descLunge: '单侧腿部动作，提升平衡和股四头肌。',
    descPlank: '等长核心保持，建立整体躯干稳定。',
    descBurpee: '全身爆发动作，结合深蹲、俯卧撑和跳跃。',
    descLateralRaise: '孤立动作，增加中束三角肌宽度。',
    descRussianTwist: '旋转核心动作，针对腹斜肌。',
    descMountainClimb: '动态核心动作，兼具有氧效果。',
    descDefault: '力量与耐力的复合动作。',
    // Workout + schedule
    wWeeklyGoal: '每周目标',
    wComputing: '计算中…',
    wMin: '分钟',
    wMedium: '中等',
    wTemplates: '模板',
    wTemplateActive: '已启用模板 —',
    wReset: '重置',
    wTrainAgain: '再次训练',
    scBestWindow: '最佳时段',
    scOptimalWindow: '最佳能量时段',
    scStart: '开始',
    scStartArrow: '开始 →',
    scTodayOnly: '仅限今天',
    scMorning: '上午',
    scMorningSub: '中午前',
    scAfternoon: '下午',
    scAfternoonSub: '12 – 5 点',
    scEvening: '晚上',
    scEveningSub: '5 点后',
    scScheduleGroup: '日程',
    scMinShort: '分钟',
    // Exercise session
    exTodaysWorkout: '今日锻炼',
    exOneShot: '仅此一次——退出即今天无 FitToken',
    exLetsGo: '开始吧',
    exTrackTitle: '追踪你的动作',
    exTrackBody: 'FitSched 使用设备的运动传感器来验证你的锻炼并发放完整 FitToken。你的数据绝不离开设备。',
    exEnableMotion: '启用运动追踪',
    exSkip50: '跳过——获得 50% FitToken',
    exTodaysWorkoutLower: '今日锻炼',
    exVerified: '已验证',
    exUnverified: '未验证',
    exSwap: '替换',
    exLast: '上次：',
    exRound: '轮次',
    exOf: '/',
    exSet: '组',
    exAllSetsDone: '所有组已完成',
    exCompleteSet: '完成',
    exCamAuto: '用相机计数',
    exCamBeta: '测试版',
    exCamStarting: '正在启动相机…',
    exCamDenied: '无法使用相机，请检查权限后重试。',
    exCamTip: '将手机立稳，让全身入镜',
    exCamStop: '关闭相机',
    exOfLower: '/',
    exUpNext: '下一个',
    exSwapHeader: '替换',
    exNoAlts: '没有可替换的动作',
    exQuitTitle: '退出锻炼？',
    exQuitPre: '你每天只有',
    exQuitBold: '一次机会',
    exQuitPost: '。现在离开意味着今天没有 FitToken，并且明天之前无法重新进入。',
    exKeepGoing: '继续',
    exQuitLose: '退出并放弃',
    exRest: '休息',
    exSec: '秒',
    exSkip: '跳过',
    exStatTime: '时间',
    exStatExercises: '动作',
    exStatSets: '组数',
    exStatReps: '次数',
    exEstCalories: '预计热量',
    exYouReceived: '你获得了',
    exPartialReward: '部分奖励——下次点击验证可获得完整 +1.0 FT',
    exNoTokens: '本次无代币——锻炼太快无法验证',
    exPersonalRecords: '个人纪录',
    exWas: '原为',
    exFirstTime: '首次记录！',
    exHowFeel: '感觉如何？',
    exFbEasy: '太简单',
    exFbEasyD: '增加挑战',
    exFbJust: '刚刚好',
    exFbJustD: '保持节奏',
    exFbHard: '太难',
    exFbHardD: '降低强度',
    exFbSaved: '反馈已保存，用于未来推荐。',
    exSessionNotes: '训练备注',
    exNotePlaceholder: '今天怎么样？破纪录了吗？想记住什么…',
    exSaved: '已保存',
    exAchUnlocked: '成就解锁',
    exExitedTitle: '你今天已退出本次训练',
    exExitedBody: '明天回来进行全新锻炼并获得完整 FitToken 奖励。',
    exGoExercise: '开始锻炼',
    exToday: '今天',
    exYesterday: '昨天',
    exDaysAgo: '天前',
    // Hike page
    hkLogs: '记录',
    hkHikes: '次徒步',
    hkPendingSync: '待同步',
    hkSavedOffline: '已离线保存——联网后将同步',
    hkFtEarned: 'FT 已获得',
    hkKmExcluded: '公里被排除——速度过快不算步行',
    hkSaveTitle: '保存你的徒步',
    hkTrailName: '路线名称',
    hkTrailPlaceholder: '例如 武吉知马山',
    hkLocation: '地点',
    hkLocationPlaceholder: '例如 武吉知马自然保护区',
    hkNotes: '备注',
    hkNotesPlaceholder: '感觉如何？',
    hkSaving: '保存中…',
    hkSaveHike: '保存徒步',
    hkHikeLogs: '徒步记录',
    hkChipHikes: '徒步',
    hkChipDistance: '距离',
    hkChipElevation: '海拔',
    hkChipTime: '时间',
    hkLoading: '加载中…',
    hkNoHikes: '尚无徒步记录。',
    // Weight page
    wtGoal: '目标：',
    wtLogWeight: '记录体重',
    wtSetGoalTitle: '设置体重目标',
    wtGoalDesc: '设置目标体重以追踪你的进度。',
    wtEg: '例如',
    wtClearGoal: '清除目标',
    wtSetGoal: '设置目标',
    wtNewEntry: '新记录',
    wtSave: '保存',
    wtNotePlaceholder: '可选备注（例如 跑步后）',
    wtLastLogged: '上次记录',
    wtVsPrev: '对比上次',
    wtToGo: '距目标',
    wtReached: '已达成',
    wtGoalShort: '目标',
    wtNoEntries: '尚无记录',
    wtEmptyHint: '点击“记录体重”开始追踪你的进度。',
    wtEntry: '条记录',
    // Withdrawal page
    wdSubtitle: '锻炼即可赚取 FIT，领取到你的 Base 钱包。',
    wdYourWallet: '你的钱包',
    wdBaseNetwork: 'Base 网络 (EVM)',
    wdChange: '更改',
    wdSaved: '已保存',
    wdEnterNew: '输入新的 Base 钱包地址：',
    wdPasteAddr: '粘贴你的 Base 钱包地址以在领取时接收 FIT：',
    wdSave: '保存',
    wdWalletHint: '仅支持 Base（chainId 8453）地址。切勿分享你的私钥。',
    wdFtBalance: 'FitToken 余额',
    wdLiveOnBase: '已在 Base 上线',
    wdOffchain: '链下 · 即将在 Base 上线',
    wdLive: '已上线',
    wdClaimedExcl: '已领取！',
    wdTokensSent: '代币已发送到你的 Base 钱包。',
    wdOnchainBalance: '链上余额：',
    wdViewBasescan: '在 Basescan 查看',
    wdClaimableBalance: '可领取余额',
    wdAlreadyClaimed: '已领取',
    wdTotalEarned: '累计获得',
    wdOnChain: '链上',
    wdClaimedLabel: '已领取',
    wdProgressMin: '距最低领取进度',
    wdMoreToGo: 'FIT 才能领取',
    wdHowEarn: '如何赚取',
    wdEarn1: '完成一次锻炼',
    wdEarn1d: '每次 +1.00 FT',
    wdEarn2: '连续打卡奖励',
    wdEarn2d: '最多额外 +0.20 FT',
    wdEarn3: '验证得分',
    wdEarn3d: '满分 = 全额奖励',
    wdClaimHistory: '领取记录',
    wdRecentEarnings: '最近收益',
    wdActionWithdraw: '提取 FIT',
    wdActionWallet: '更改你的钱包',
    wdReasonWorkout: '锻炼已完成',
    wdSetWalletFirst: '请先设置钱包地址',
    wdNoFitYet: '暂无可领取的 FIT',
    wdNeedMinPre: '至少需要',
    wdNeedMinPost: 'FIT',
    wdClaim: '领取',
    wdLaunchingSoon: '即将上线',
    wdClaiming: '领取中…',
    wdClaimedBtn: '已领取',
    wdLaunchNote1: 'FitToken 合约尚未在 Base 上线。你的余额是安全的，上线后即可领取。',
    wdLaunchNote2pre: '你的',
    wdLaunchNote2post: 'FIT 是安全的，合约在 Base 上线后即可领取。',
    wdErrGeneric: '出错了，请重试。',
    wdErrNetwork: '网络错误——请重试',
    // Exercise library
    exLibEdit: '编辑动作',
    eqBodyweight: '徒手',
    eqDumbbells: '哑铃',
    eqBarbell: '杠铃',
    eqMachine: '器械',
    eqCables: '拉索',
    eqBands: '弹力带',
    eqKettlebell: '壶铃',
    workoutNames: {
      'Chest & Triceps':  '胸部 & 三头肌',
      'Back & Biceps':    '背部 & 二头肌',
      'Shoulders & Core': '肩部 & 核心',
      'Arms & Core':      '手臂 & 核心',
      'Legs':             '腿部',
      'Full Body':        '全身',
      'Rest':             '休息',
    },
  },
  JP: {
    yourDay: '今日の予定',
    days: {
      sun: '日曜', mon: '月曜', tue: '火曜',
      wed: '水曜', thu: '木曜', fri: '金曜', sat: '土曜'
    },
    goodMorning: 'おはようございます、',
    timeline: 'タイムライン',
    noEvents: '今日の予定はありません',
    clearDay: '予定なし \u2014 ゆっくり過ごしてください。',
    workout: 'ワークアウト',
    todaysPlan: '今日のプラン',
    setReminder: 'リマインダーを設定',
    workoutIn: '15分後にワークアウト',
    settings: '設定',
    syncNow: '今すぐ同期',
    disconnect: '切断',
    signOut: 'サインアウト',
    pushNotifications: 'プッシュ通知',
    workoutReminders: 'ワークアウトリマインダー',
    version: 'バージョン',
    stats: '統計',
    calendar: 'カレンダー',
    preferences: '設定',
    workoutSetup: '\u30c8\u30ec\u30fc\u30cb\u30f3\u30b0\u74b0\u5883',
    workoutSetupDescription: '\u7a2e\u76ee\u306e\u304a\u3059\u3059\u3081\u306b\u4f7f\u7528',
    homeWorkout: '\u81ea\u5b85\u30c8\u30ec',
    noEquipment: '\u5668\u5177\u306a\u3057',
    homeDumbbells: '\u81ea\u5b85 + \u30c0\u30f3\u30d9\u30eb',
    dumbbellAccess: '\u30c0\u30f3\u30d9\u30eb\u3042\u308a',
    gym: '\u30b8\u30e0',
    fullEquipment: '\u5168\u5668\u5177\u3042\u308a',
    hike: '\u30cf\u30a4\u30af',
    googleConnected: 'Googleカレンダー接続済み',
    readOnly: '読み取り専用',
    schedule: 'スケジュール',
    synced: '同期済み',
    welcomeBack: 'おかえりなさい',
    signInContinue: '続けるにはサインインしてください',
    email: 'メール',
    password: 'パスワード',
    signIn: 'サインイン',
    orContinueWith: 'または続ける',
    continueGoogle: 'Googleで続ける',
    noAccount: 'アカウントをお持ちでないですか？',
    signUp: '登録',
    forgotPassword: 'パスワードをお忘れですか？',
    continueGuest: 'ゲストとして続ける',
    startingGuest: 'ゲストセッションを開始中…',
    connect: '接続',

    enabled: '有効',
    user: 'ユーザー',
    nameLabel: '名前',
    creatingAccount: 'アカウント作成中...',
    cancel: 'キャンセル',
    restDay: '休息日',
    restBody: '休息は体が回復する時間です。軽い散歩をおすすめします。',
    lightWorkoutBtn: '軽めのワークアウトを試す →',
    saveToSchedule: 'スケジュールに保存',
    savedToSchedule: 'スケジュールに保存しました！',
    reminder: 'リマインダー',
    reminderSet: 'リマインダー設定済み',
    fitSched: 'FitSched',
    connectCalendar: 'カレンダーを接続',
    syncDescription: 'ワークアウトの時間帯を見つけるための読み取り専用同期。',
    signInWithGoogle: 'Googleでサインイン',
    syncing: '同期中...',
    connecting: '接続中...',
    autoScheduled: '自動スケジュール',
    avgWorkout: '平均ワークアウト',
    decisions: '決定',
    daysLabel: '日',
    tagline: 'あなたのスケジュール。あなたのペース。',
    startJourney: '旅を始めましょう。',
    createAccount: 'アカウント作成',
    itsFree: 'いつでも無料です。',
    hasAccount: 'すでにアカウントをお持ちですか？',
    exercises: 'エクササイズ',
    add: '追加',
    searchExercises: 'エクササイズを検索...',
    all: 'すべて',
    defaultLabel: 'デフォルト',
    noExercises: 'エクササイズが見つかりません',
    addExercise: 'エクササイズを追加',
    name: '名前',
    description: '説明',
    optionalDescription: '任意の説明',
    muscle: '筋肉',
    equipment: '器具',
    difficulty: '難易度',
    exerciseName: 'エクササイズ名',
    history: '履歴',
    progress: '進捗',
    trackJourney: 'ワークアウトの旅を記録',
    overview: '概要',
    charts: 'チャート',
    totalWorkouts: '総ワークアウト',
    totalSets: '総セット数',
    avgRating: '平均評価',
    thisWeek: '今週',
    recentActivity: '最近の活動',
    noWorkouts: 'まだワークアウトが記録されていません',
    setsPerSession: 'セッションあたりのセット数',
    noData: 'データがまだありません',
    ratingTrend: '評価の傾向',
    language: '言語',
    workoutLabel: 'ワークアウト',
    markAsDone: '✓ 完了としてマーク',
    workoutCompleted: '✓ ワークアウト完了！',
    logWorkout: 'ワークアウトを記録',
    adjustReps: '実際に完了したセット数とレップ数を調整',
    saveWorkoutLog: 'ワークアウトログを保存',
    sets: 'セット',
    reps: 'レップ',
    currentStreak: '現在の連続',
    totalExercises: '総エクササイズ数',
    last8Weeks: '最近8週間',
    mostTrained: '最も鍛えた部位',
    workoutHistory: 'ワークアウト履歴',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    addSchedule: '予定を追加',
    editSchedule: '予定を編集',
    addToSchedule: '予定に追加',
    saveChanges: '変更を保存',
    adding: '追加中...',
    saving: '保存中...',
    manual: '手動',
    edit: '編集',
    delete: '削除',
    deleting: '...',
    goExercise: '運動を開始',
    exercisesCount: '種目',
    title: 'タイトル',
    time: '時間',
    optionalNotes: '任意のメモ',
    classWorkAppointment: '授業、仕事、予定...',
    workoutLockedTitle: 'この日のワークアウトはロック済み',
    workoutLockedBody: 'このワークアウトは完了済みのため、次のワークアウト日までFitTokenを保護します。',
    todayWorkoutOnlyTitle: '今日のワークアウトのみ',
    todayWorkoutOnlyBody: 'FitTokenは当日のワークアウトでのみ獲得できます。他の日はプレビュー専用です。',
    todayOnly: '今日のみ',
    checkingWorkout: 'ワークアウトを確認中',
    workoutAlreadyComplete: 'ワークアウトは完了済み',
    workoutAlreadyCompleteBody: 'FitTokenの公平性を守るため、この日はロックされています。次のワークアウト日に戻ってきてください。',
    noWorkoutLoaded: 'ワークアウトが読み込まれていません',
    noWorkoutLoadedBody: 'ワークアウトタブから運動セッションを開始してください。',
    backToWorkout: 'ワークアウトへ戻る',
    back: '戻る',
    exercisesDone: '種目完了',
    restTime: '休憩時間',
    nowTraining: 'トレーニング中',
    resting: '休憩中...',
    pauseTimer: 'タイマーを一時停止',
    resumeTimer: 'タイマーを再開',
    exerciseLabel: '種目',
    setLabel: 'セット',
    ofLabel: '中',
    repsThisSet: '回このセット',
    setsDone: 'セット完了',
    skipRest: '休憩をスキップ',
    doneSet: 'セット完了',
    finishWorkout: 'ワークアウトを完了',
    workoutCompleteTitle: 'ワークアウト完了',
    workoutCompleteBody: '今日もやり切りました。このリズムを続けましょう。',
    streakLabel: '連続',
    dayStreak: '日連続',
    receiveFitToken: 'FITTOKENを受け取る',
    continueLabel: '続ける',
    lpHeroLine1: '賢くプランを。',
    lpHeroLine2: 'ハードに鍛える。',
    lpHeroBody: 'あなたの種目・器具・スケジュールに合わせた週間トレーニングプランを作成し、すべてのセッション、ストリーク、ハイクを記録します。',
    lpSeeHow: '詳しく見る',
    lpCheck1: '80種目以上で7日間のカスタムプランを作成',
    lpCheck2: 'すべてのセッション・ストリーク・休息日を記録',
    lpCheck3: 'GPSハイクトラッキング内蔵',
    lpCtaTitle: '2分以内に最初のワークアウトプランを作成。',
    lpCtaBody: 'クレジットカード不要。プランを設定してトレーニング開始。',
    lpGetStartedFree: '無料で始める',
    setsCount: 'セット',
    showLess: '折りたたむ',
    showAll: '全 {n} 件を表示',
    completeFirstWorkout: '最初のワークアウトを完了すると、進捗がここに表示されます。',
    goToSchedule: 'スケジュールへ',
    freeWindow: '空き時間',
    classLabel: '授業',
    clearDayTitle: '空き日',
    clearDayHint: '予定なし — + をタップして追加するか、ゆっくり過ごしてください。',
    byTheNumbers: '記録',
    workoutsDone: '完了したワークアウト',
    exercisesDoneLabel: '完了した種目',
    bestStreakLabel: '最長連続',
    lifetimeLabel: '累計',
    // Landing page specific
    lpFitnessScheduler: 'フィットネス管理',
    lpPlanGenerator: 'プラン生成',
    lpPlanLine1: '一言で、',
    lpPlanLine2: '一週間のプランが完成。',
    lpSessionPush: 'プッシュ日',
    lpSessionRest: '休息',
    lpSessionLower: '下半身',
    lpSessionPushTime: '月曜 · 3セット · 6種目',
    lpSessionRestTime: '水曜 · 回復',
    lpSessionLowerTime: '金曜 · 4セット · 5種目',
    lpStreakTitle: 'ストリーク',
    lpDaysInARow: '日連続',
    lpLongestRun: '最長記録：31日',
    lpProgressLabel: '進捗',
    lpLast10Days: '直近10日',
    lpSessionsCompleted: 'セッション完了',
    lpVsLastWeek: '+12% 先週比',
    lpBuiltDifferent: '他とは違う',
    lpEveryTool: '必要なツール、すべて。',
    lpNothingYouDont: '余計なものは何もない。',
    lpStatExercises: '種目ライブラリ',
    lpStatPlans: 'カスタムトレーニング',
    lpStatHike: 'ハイク追跡',
    lpStatStreak: '平均連続日数',
    lpStartToday: '今日から始める',
    lpFooterTagline: 'あなたのフィットネス、予定通りに。',
    lpMarqueeItems: [
      'プラン生成', 'ストリーク記録', 'GPSハイク追跡',
      '種目ライブラリ', '進捗レポート', 'FitTokens',
      'トレーニング計画', '80種目以上', 'Googleカレンダー同期',
      'セッション履歴', '休息日管理', '習慣記録',
    ],
    fitnessProfile: 'フィットネスプロフィール',
    earnings: '収益',
    goalLabel: '目標',
    experienceLevelLabel: '経験レベル',
    bodyStats: '身体測定値',
    deleteAccount: 'アカウント削除',
    typeDeleteToConfirm: '確認のため DELETE と入力',
    temporaryAccount: '一時アカウント',
    yourProgressIsTemporary: 'あなたの進捗は一時的です',
    profileUpdated: 'プロフィールを更新しました',
    todayLabel: '今日',
    lastWorkoutLabel: '前回のワークアウト',
    noMuscleMapYet: 'まだワークアウトの記録がありません — 初回セッション後に筋肉マップが表示されます。',
    primaryLabel: '主要',
    secondaryLabel: '副次',
    lightLabel: '軽度',
    targetLabel: '集中',
    // Landing page — hero + sections
    lpEyebrow: 'フィットネス · トークン · 習慣',
    lpHead1: '鍛えろ。',
    lpHead2: '報酬を',
    lpHead3: '獲得。',
    lpPerWorkout: 'ワークアウト完了ごとに',
    lpBaseNetwork: 'Base ネットワーク · EVM',
    lpStatExercisesLabel: '種目',
    lpStatPerSession: '1セッションごと',
    lpStatHikeTracking: 'ハイク追跡',
    lpStatNoCard: 'カード不要',
    lpStatFree: '無料',
    lpHowItWorks: '使い方',
    lpSteps: '3ステップ',
    lpStepSchedule: 'スケジュール',
    lpStepScheduleDesc: '週間トレーニング目標を設定。FitSched は初日からプランを作成し——無駄な休息日なし——筋肉の回復、コンディション、利用できる器具に合わせて毎回調整します。',
    lpStepTrain: 'トレーニング',
    lpStepTrainDesc: 'ガイド付きセッションに従うだけ。デバイスのモーションセンサーが各動作を検証し、すべてのレップで満額のトークン報酬を獲得できます。',
    lpStepEarn: '獲得',
    lpStepEarnDesc: 'セッションを完了して FitToken を獲得——オフチェーンで記録され、Base ウォレットに請求可能。ストリークボーナスも上乗せされます。',
    lpFtPerCompleted: 'ワークアウト完了ごと',
    lpFtTitle: '本物の努力に、本物の暗号報酬。',
    lpFtBody: 'ワークアウトごとに FitToken を獲得——オフチェーンで記録され、Base ウォレットに請求可能。ストリークボーナスと検証倍率で、頑張るほど多く稼げます。',
    lpRewardBase: '基本ワークアウト',
    lpRewardStreak: '7日ストリークボーナス',
    lpRewardVerified: 'モーション検証済み',
    lpFullReward: '満額報酬',
    lpFeatSmartSched: 'スマートスケジューリング',
    lpFeatSmartSchedDesc: '参加した日から始まり、回復と目標に合わせて調整されるプラン——追加セッションが欲しいときは最も元気な部位を選びます。',
    lpFeatStreak: 'ストリークシステム',
    lpFeatStreakDesc: '休息日でも記録が途切れない毎日のストリーク。',
    lpFeatGps: 'GPSハイク追跡',
    lpFeatGpsDesc: 'リアルタイムGPSルート記録と標高データで屋外ハイクを記録。',
    lpFeatMotion: 'モーション検証',
    lpFeatMotionDesc: 'デバイスのセンサーが各レップを確認し、満額のトークン報酬を付与。',
    lpFeatAchieve: 'アチーブメント',
    lpFeatAchieveDesc: 'バッジを解除し、すべての部位で自己記録を追跡。',
    lpFeatCalSync: 'カレンダー同期',
    lpFeatCalSyncDesc: 'ワークアウトのスケジュールを Google カレンダーに直接送信。',
    lpCtaTitle1: '今日から',
    lpCtaTitle2: '始めよう。',
    lpFreeNoCard: '無料 · クレジットカード不要',
    // Schedule — smart workout time
    smartTime: 'スマート選択',
    pickWorkoutTime: '何時に？',
    smartTimeHint: 'いつも鍛える時間帯に基づきます',
    // Landing page phone mockups
    lpmPushDay: 'プッシュ日',
    lpmChestShoulders: '胸 & 肩',
    lpmRecovery: '回復',
    lpmSetsReps: '4セット · 8回',
    lpmRest: '休憩 · 00:48',
    lpmCompleteSet: 'セット完了',
    lpmRecent: '最近',
    lpmThisWeek: '今週',
    lpmLegDay: '脚の日',
    lpmSquats: 'スクワット & デッドリフト',
    lpmTrail: 'リバーサイドトレイル',
    lpmYesterday: '昨日',
    lpm2days: '2日前',
    lpm3days: '3日前',
    lpmMuChest: '胸',
    lpmMuBack: '背',
    lpmMuLegs: '脚',
    lpmMuArms: '腕',
    lpmMuCore: '体幹',
    // Forgot-password page
    fpRecovery: 'パスワードの再設定',
    fpForgotTitle: 'パスワードをお忘れですか？',
    fpEnterEmail: 'メールアドレスを入力すると、リセットリンクをお送りします。',
    fpSendLink: 'リセットリンクを送信',
    fpSending: '送信中…',
    fpRememberIt: '思い出しましたか？',
    fpError: '問題が発生しました。もう一度お試しください。',
    fpGoogleTitle: 'Google アカウント',
    fpGoogleBody: 'は Google アカウントにリンクされています。パスワードは不要です——Google でサインインしてください。',
    fpCheckTitle: 'メールをご確認ください',
    fpCheckPre: 'もし',
    fpCheckPost: 'に FitSched アカウントがあれば、まもなくリセットリンクが届きます。リンクは1時間で失効します。',
    fpDidntGet: '届きませんか？迷惑メールフォルダをご確認いただくか、',
    fpTryAgain: 'もう一度試す',
    fpBackSignin: 'サインインに戻る',
    // Auth pages (login + register)
    authIncorrect: 'メールアドレスまたはパスワードが正しくありません',
    authGuestError: 'ゲストセッションを開始できませんでした。もう一度お試しください。',
    authSigningIn: 'サインイン中…',
    regEmailTaken: 'メールアドレスは登録済みか、パスワードが弱すぎます',
    regNamePlaceholder: 'お名前',
    regPwPlaceholder: '8文字以上',
    authAgreePre: '以下に同意します：',
    termsOfService: '利用規約',
    privacyPolicy: 'プライバシーポリシー',
    andLabel: 'および',
    authGoogleAgree: 'Google で続行すると、以下に同意したことになります：',
    termsShort: '規約',
    // Settings page
    setFtBalance: 'FitToken 残高',
    setEarnedFrom: 'ワークアウトで獲得',
    setWithdraw: '出金',
    setGoogleCal: 'Google カレンダー',
    setCalSub: '読み取り専用 · 毎晩同期',
    setConnecting: '接続中…',
    setOn: 'オン',
    setOff: 'オフ',
    setTapSync: 'タップして同期',
    setLastPrefix: '前回',
    setGoalLose: '減量',
    setGoalBuild: '筋肉増強',
    setGoalActive: '健康維持',
    setGoalEndurance: '持久力',
    setLvlBeginner: '初心者',
    setLvlBeginnerSub: '始めたばかり',
    setLvlInter: '中級',
    setLvlInterSub: '少し経験あり',
    setLvlAdv: '上級',
    setLvlAdvSub: '十分な経験',
    setHeight: '身長',
    setWeight: '体重',
    setEnvHome: '自宅',
    setEnvHomeSub: '自重',
    setEnvDbs: '+ ダンベル',
    setEnvDbsSub: 'ダンベル',
    setEnvGym: 'ジム',
    setEnvGymSub: 'フル装備',
    setPerWeek: '週あたりの回数',
    setPerWeekUnit: '回 / 週',
    setExLibrary: '種目ライブラリ',
    setExLibrarySub: '種目を閲覧・管理',
    setNotifications: '通知',
    setUpdating: '更新中…',
    setAppearance: '外観',
    setDarkMode: 'ダークモード',
    setLightMode: 'ライトモード',
    setGuestBody: 'ゲストアカウントは保存されません。無料アカウントを作成して、ストリーク、ワークアウト、FitToken を保持しましょう。',
    setCreateFree: '無料アカウントを作成',
    setDeleteTitle: 'アカウントを削除しますか？',
    setDeleteBody: 'プロフィール、ワークアウト履歴、ストリーク、FitToken が完全に削除されます。元に戻せません。',
    setDeleting: '削除中…',
    justNow: 'たった今',
    minsAgoSuffix: '分前',
    hoursAgoSuffix: '時間前',
    // Profile page
    profTitle: 'プロフィール',
    profTapName: 'タップして名前を設定',
    profSaving: '保存中…',
    profJoined: '登録',
    profGuestCta: '無料アカウントを作成して進捗を保存 →',
    profOf: '/',
    profSessions: '回',
    profBody: '身体',
    bmiUnder: '低体重',
    bmiNormal: '標準',
    bmiOver: '過体重',
    bmiObese: '肥満',
    profWeightTrend: '体重の推移',
    profNoChange: '変化なし',
    profSinceFirst: '最初の記録から',
    profEntries: '件',
    profWeightLog: '体重ログ',
    profWeightLogSub: '体重を長期的に記録',
    profHikeLogs: 'ハイクログ',
    profHikes: '回のハイク',
    profKmTotal: 'km 合計',
    profAchievements: 'アチーブメント',
    profUnlocked: '解除',
    profNotUnlocked: '未解除',
    // Muscle groups (shared)
    muAll: 'すべて',
    muChest: '胸',
    muBack: '背中',
    muLegs: '脚',
    muShoulders: '肩',
    muArms: '腕',
    muCore: '体幹',
    // History page
    hPrs: '記録',
    hKgMax: 'kg 最大',
    hNotePlaceholder: 'このセッションのメモを追加…',
    hSaveNote: 'メモを保存',
    hTapNote: 'タップしてメモを追加…',
    hDeleting: '削除中…',
    hDeleteLog: 'ログを削除',
    hNoFilteredWorkouts: 'このフィルターのワークアウトはまだありません',
    hExPerSession: 'セッションあたりの種目数',
    hPrEmpty: '重量付きのワークアウトを完了して記録を追跡',
    hSessions: 'セッション',
    hReps: '回',
    hBest: 'ベスト',
    hProgression: '推移',
    hRepsLabel: 'レップ',
    muFullBody: '全身',
    muCardio: '有酸素',
    // Report / Progress page
    rStreakBonus: 'ストリークボーナス',
    rWorkout: 'ワークアウト',
    rBoostSuffix: '(2× ブースト)',
    rDay: '日',
    rDays: '日',
    rPersonalBest: '自己ベスト',
    rMusclesHit: '鍛えた部位',
    rRecovery: '回復',
    rActivity: 'アクティビティ',
    rFtEarnings: 'FitToken 収益',
    rFtEmpty: 'ワークアウトを完了して最初の FitToken を獲得しましょう。',
    rCaloriesBurned: '消費カロリー（8週間）',
    rKcalTotal: 'kcal 合計',
    rCalories: 'カロリー',
    rHikeStats: 'ハイク統計',
    rHikes: 'ハイク',
    rDistance: '距離',
    rTime: '時間',
    rViewAllHikes: 'すべてのハイクを見る',
    rTotal: '合計',
    rSearchWorkouts: 'ワークアウトを検索…',
    rNoMatching: '一致するワークアウトがありません',
    rLoadedToday: '今日に読み込みました！',
    rLoading: '読み込み中…',
    rRepeatToday: '今日繰り返す',
    // Exercise descriptions
    descInclinePush: '高い場所を使う初心者向けの腕立て伏せ。',
    descPushup: '胸・三頭筋・肩・体幹を鍛えるプッシュ動作。',
    descShoulderTap: '腕立て伏せの後に肩を交互にタッチ。',
    descDiamond: '三頭筋と内側の胸を狙う狭い手幅の腕立て。',
    descTricepDip: '三頭筋を孤立させ肩を安定させるディップ。',
    descPullup: '広背筋・二頭筋・上背を狙う垂直プル。',
    descBicepCurl: '二頭筋のピークと腕の力を鍛える単関節種目。',
    descSquat: '大腿四頭筋・臀部・股関節の複合下半身種目。',
    descLunge: 'バランスと大腿四頭筋を鍛える片脚種目。',
    descPlank: '体幹全体を安定させる等尺性ホールド。',
    descBurpee: 'スクワット・腕立て・ジャンプを組み合わせた全身種目。',
    descLateralRaise: '三角筋中部の幅を狙う単関節種目。',
    descRussianTwist: '腹斜筋を狙う回旋系の体幹種目。',
    descMountainClimb: '有酸素効果のある動的な体幹種目。',
    descDefault: '筋力と持久力のための複合種目。',
    // Workout + schedule
    wWeeklyGoal: '週間目標',
    wComputing: '計算中…',
    wMin: '分',
    wMedium: '中',
    wTemplates: 'テンプレート',
    wTemplateActive: 'テンプレート適用中 —',
    wReset: 'リセット',
    wTrainAgain: 'もう一度',
    scBestWindow: 'ベスト時間帯',
    scOptimalWindow: '最適なエネルギー時間帯',
    scStart: '開始',
    scStartArrow: '開始 →',
    scTodayOnly: '今日のみ',
    scMorning: '午前',
    scMorningSub: '正午前',
    scAfternoon: '午後',
    scAfternoonSub: '12 – 17時',
    scEvening: '夜',
    scEveningSub: '17時以降',
    scScheduleGroup: 'スケジュール',
    scMinShort: '分',
    // Exercise session
    exTodaysWorkout: '今日のワークアウト',
    exOneShot: '一回限り——退出すると今日は FitToken なし',
    exLetsGo: 'はじめる',
    exTrackTitle: '動きを記録',
    exTrackBody: 'FitSched はデバイスのモーションセンサーでワークアウトを確認し、満額の FitToken を付与します。データはデバイスから出ません。',
    exEnableMotion: 'モーション追跡を有効化',
    exSkip50: 'スキップ——FitToken 50% 獲得',
    exTodaysWorkoutLower: '今日のワークアウト',
    exVerified: '確認済み',
    exUnverified: '未確認',
    exSwap: '交換',
    exLast: '前回：',
    exRound: 'ラウンド',
    exOf: '/',
    exSet: 'セット',
    exAllSetsDone: '全セット完了',
    exCompleteSet: 'セット完了',
    exCamAuto: 'カメラでレップを数える',
    exCamBeta: 'ベータ',
    exCamStarting: 'カメラを起動中…',
    exCamDenied: 'カメラを使用できません。権限を確認してください。',
    exCamTip: '全身が映るようにスマホを立ててください',
    exCamStop: 'カメラを停止',
    exOfLower: '/',
    exUpNext: '次は',
    exSwapHeader: '交換',
    exNoAlts: '代替種目がありません',
    exQuitTitle: 'ワークアウトをやめますか？',
    exQuitPre: '1日に',
    exQuitBold: '1回だけ',
    exQuitPost: 'のチャンスです。今やめると今日は FitToken がなく、明日まで再入場できません。',
    exKeepGoing: '続ける',
    exQuitLose: 'やめて失う',
    exRest: '休憩',
    exSec: '秒',
    exSkip: 'スキップ',
    exStatTime: '時間',
    exStatExercises: '種目',
    exStatSets: 'セット',
    exStatReps: 'レップ',
    exEstCalories: '推定カロリー',
    exYouReceived: '獲得しました',
    exPartialReward: '部分報酬——次回は確認をタップで満額 +1.0 FT',
    exNoTokens: '今回はトークンなし——速すぎて確認できませんでした',
    exPersonalRecords: '自己記録',
    exWas: '前回は',
    exFirstTime: '初記録！',
    exHowFeel: 'どうでしたか？',
    exFbEasy: '簡単すぎ',
    exFbEasyD: '負荷を上げる',
    exFbJust: 'ちょうど良い',
    exFbJustD: 'ペース維持',
    exFbHard: 'きつすぎ',
    exFbHardD: '負荷を下げる',
    exFbSaved: 'フィードバックを今後の提案に保存しました。',
    exSessionNotes: 'セッションメモ',
    exNotePlaceholder: 'どうでしたか？自己ベスト？覚えておきたいこと…',
    exSaved: '保存しました',
    exAchUnlocked: 'アチーブメント解除',
    exExitedTitle: '今日のセッションは既に退出済みです',
    exExitedBody: '明日また新しいワークアウトと満額の FitToken 報酬を。',
    exGoExercise: '運動を開始',
    exToday: '今日',
    exYesterday: '昨日',
    exDaysAgo: '日前',
    // Hike page
    hkLogs: 'ログ',
    hkHikes: '回のハイク',
    hkPendingSync: '同期待ち',
    hkSavedOffline: 'オフライン保存——接続時に同期します',
    hkFtEarned: 'FT 獲得',
    hkKmExcluded: 'km 除外——歩行には速すぎます',
    hkSaveTitle: 'ハイクを保存',
    hkTrailName: 'コース名',
    hkTrailPlaceholder: '例：武吉知馬ヒル',
    hkLocation: '場所',
    hkLocationPlaceholder: '例：武吉知馬自然保護区',
    hkNotes: 'メモ',
    hkNotesPlaceholder: 'どうでしたか？',
    hkSaving: '保存中…',
    hkSaveHike: 'ハイクを保存',
    hkHikeLogs: 'ハイクログ',
    hkChipHikes: 'ハイク',
    hkChipDistance: '距離',
    hkChipElevation: '標高',
    hkChipTime: '時間',
    hkLoading: '読み込み中…',
    hkNoHikes: 'まだハイクの記録がありません。',
    // Weight page
    wtGoal: '目標：',
    wtLogWeight: '体重を記録',
    wtSetGoalTitle: '体重目標を設定',
    wtGoalDesc: '目標体重を設定して進捗を追跡しましょう。',
    wtEg: '例：',
    wtClearGoal: '目標を消去',
    wtSetGoal: '目標を設定',
    wtNewEntry: '新規記録',
    wtSave: '保存',
    wtNotePlaceholder: '任意のメモ（例：ランニング後）',
    wtLastLogged: '最終記録',
    wtVsPrev: '前回比',
    wtToGo: 'まで',
    wtReached: '達成',
    wtGoalShort: '目標',
    wtNoEntries: 'まだ記録がありません',
    wtEmptyHint: '「体重を記録」をタップして進捗の記録を始めましょう。',
    wtEntry: '件',
    // Withdrawal page
    wdSubtitle: 'ワークアウトで FIT を獲得。Base ウォレットに請求できます。',
    wdYourWallet: 'あなたのウォレット',
    wdBaseNetwork: 'Base ネットワーク (EVM)',
    wdChange: '変更',
    wdSaved: '保存しました',
    wdEnterNew: '新しい Base ウォレットアドレスを入力：',
    wdPasteAddr: '請求時に FIT を受け取る Base ウォレットアドレスを貼り付け：',
    wdSave: '保存',
    wdWalletHint: 'Base（chainId 8453）アドレスのみ対応。秘密鍵は絶対に共有しないでください。',
    wdFtBalance: 'FitToken 残高',
    wdLiveOnBase: 'Base で稼働中',
    wdOffchain: 'オフチェーン · Base で開始予定',
    wdLive: '稼働中',
    wdClaimedExcl: '請求しました！',
    wdTokensSent: 'トークンを Base ウォレットに送信しました。',
    wdOnchainBalance: 'オンチェーン残高：',
    wdViewBasescan: 'Basescan で見る',
    wdClaimableBalance: '請求可能残高',
    wdAlreadyClaimed: '請求済み',
    wdTotalEarned: '累計獲得',
    wdOnChain: 'オンチェーン',
    wdClaimedLabel: '請求済み',
    wdProgressMin: '最低請求額までの進捗',
    wdMoreToGo: 'FIT 必要です',
    wdHowEarn: '獲得方法',
    wdEarn1: 'ワークアウトを完了',
    wdEarn1d: '1回ごとに +1.00 FT',
    wdEarn2: 'ストリークボーナス',
    wdEarn2d: '最大 +0.20 FT 追加',
    wdEarn3: '検証スコア',
    wdEarn3d: '満点 = 満額報酬',
    wdClaimHistory: '請求履歴',
    wdRecentEarnings: '最近の獲得',
    wdActionWithdraw: 'FIT を引き出す',
    wdActionWallet: 'ウォレットを変更',
    wdReasonWorkout: 'ワークアウト完了',
    wdSetWalletFirst: '先にウォレットアドレスを設定',
    wdNoFitYet: '請求できる FIT がまだありません',
    wdNeedMinPre: '最低',
    wdNeedMinPost: 'FIT 必要',
    wdClaim: '請求',
    wdLaunchingSoon: '近日公開',
    wdClaiming: '請求中…',
    wdClaimedBtn: '請求済み',
    wdLaunchNote1: 'FitToken コントラクトはまだ Base で稼働していません。残高は安全で、公開後に請求できます。',
    wdLaunchNote2pre: 'あなたの',
    wdLaunchNote2post: 'FIT は安全で、コントラクトが Base で稼働すると請求できます。',
    wdErrGeneric: '問題が発生しました。もう一度お試しください。',
    wdErrNetwork: 'ネットワークエラー——もう一度お試しください',
    // Exercise library
    exLibEdit: '種目を編集',
    eqBodyweight: '自重',
    eqDumbbells: 'ダンベル',
    eqBarbell: 'バーベル',
    eqMachine: 'マシン',
    eqCables: 'ケーブル',
    eqBands: 'バンド',
    eqKettlebell: 'ケトルベル',
    workoutNames: {
      'Chest & Triceps':  '胸 & 三頭筋',
      'Back & Biceps':    '背 & 二頭筋',
      'Shoulders & Core': '肩 & 体幹',
      'Arms & Core':      '腕 & 体幹',
      'Legs':             '脚',
      'Full Body':        '全身',
      'Rest':             '休息',
    },
  },
  VI: {
    yourDay: 'Ngày của bạn',
    days: {
      sun: 'CN', mon: 'T2', tue: 'T3',
      wed: 'T4', thu: 'T5', fri: 'T6', sat: 'T7'
    },
    goodMorning: 'Chào buổi sáng,',
    timeline: 'THỜI GIAN BIỂU',
    noEvents: 'Không có sự kiện hôm nay',
    clearDay: 'Ngày trống \u2014 hãy tận hưởng.',
    workout: 'Tập luyện',
    todaysPlan: 'KẾ HOẠCH HÔM NAY',
    setReminder: 'Đặt nhắc nhở',
    workoutIn: 'Tập luyện sau 15 phút',
    settings: 'Cài đặt',
    syncNow: 'Đồng bộ ngay',
    disconnect: 'Ngắt kết nối',
    signOut: 'Đăng xuất',
    pushNotifications: 'Thông báo đẩy',
    workoutReminders: 'Nhắc nhở tập luyện',
    version: 'Phiên bản',
    stats: 'THỐNG KÊ',
    calendar: 'LỊCH',
    preferences: 'TÙY CHỌN',
    workoutSetup: 'Thi\u1ebft l\u1eadp t\u1eadp luy\u1ec7n',
    workoutSetupDescription: 'D\u00f9ng \u0111\u1ec3 g\u1ee3i \u00fd b\u00e0i t\u1eadp',
    homeWorkout: 'T\u1eadp \u1edf nh\u00e0',
    noEquipment: 'Kh\u00f4ng c\u1ea7n d\u1ee5ng c\u1ee5',
    homeDumbbells: 'Nh\u00e0 + t\u1ea1 \u0111\u01a1n',
    dumbbellAccess: 'C\u00f3 t\u1ea1 \u0111\u01a1n',
    gym: 'Ph\u00f2ng gym',
    fullEquipment: '\u0110\u1ea7y \u0111\u1ee7 d\u1ee5ng c\u1ee5',
    hike: 'Leo n\u00fai',
    googleConnected: 'Google Calendar đã kết nối',
    readOnly: 'Chỉ đọc',
    schedule: 'Lịch trình',
    synced: 'Đã đồng bộ',
    welcomeBack: 'Chào mừng trở lại',
    signInContinue: 'Đăng nhập để tiếp tục',
    email: 'EMAIL',
    password: 'MẬT KHẨU',
    signIn: 'Đăng nhập',
    orContinueWith: 'hoặc tiếp tục với',
    continueGoogle: 'Tiếp tục với Google',
    noAccount: 'Chưa có tài khoản?',
    signUp: 'Đăng ký',
    forgotPassword: 'Quên mật khẩu?',
    continueGuest: 'Tiếp tục với tư cách khách',
    startingGuest: 'Đang bắt đầu phiên khách…',
    connect: 'Kết nối',

    enabled: 'Đã bật',
    user: 'Người dùng',
    nameLabel: 'TÊN',
    creatingAccount: 'Đang tạo tài khoản...',
    cancel: 'Hủy',
    restDay: 'Ngày nghỉ',
    restBody: 'Nghỉ ngơi là lúc cơ thể phục hồi. Đi bộ nhẹ được khuyến khích.',
    lightWorkoutBtn: 'Thử bài tập nhẹ →',
    saveToSchedule: 'Lưu vào Lịch trình',
    savedToSchedule: 'Đã lưu vào lịch trình!',
    reminder: 'NHẮC NHỞ',
    reminderSet: 'Đã đặt nhắc nhở',
    fitSched: 'FitSched',
    connectCalendar: 'Kết nối Lịch',
    syncDescription: 'Đồng bộ chỉ đọc để tìm khung giờ tập luyện.',
    signInWithGoogle: 'Đăng nhập bằng Google',
    syncing: 'Đang đồng bộ...',
    connecting: 'Đang kết nối...',
    autoScheduled: 'Tự động lên lịch',
    avgWorkout: 'TB tập luyện',
    decisions: 'Quyết định',
    daysLabel: 'Ngày',
    tagline: 'Lịch trình của bạn. Nhịp độ của bạn.',
    startJourney: 'Bắt đầu hành trình của bạn.',
    createAccount: 'Tạo tài khoản',
    itsFree: 'Hoàn toàn miễn phí.',
    hasAccount: 'Đã có tài khoản?',
    exercises: 'Bài tập',
    add: 'Thêm',
    searchExercises: 'Tìm kiếm bài tập...',
    all: 'Tất cả',
    defaultLabel: 'Mặc định',
    noExercises: 'Không tìm thấy bài tập',
    addExercise: 'Thêm bài tập',
    name: 'Tên',
    description: 'Mô tả',
    optionalDescription: 'Mô tả tùy chọn',
    muscle: 'Cơ',
    equipment: 'Thiết bị',
    difficulty: 'Độ khó',
    exerciseName: 'Tên bài tập',
    history: 'Lịch sử',
    progress: 'Tiến độ',
    trackJourney: 'Theo dõi hành trình tập luyện của bạn',
    overview: 'Tổng quan',
    charts: 'Biểu đồ',
    totalWorkouts: 'Tổng số buổi tập',
    totalSets: 'Tổng số hiệp',
    avgRating: 'Đánh giá TB',
    thisWeek: 'Tuần này',
    recentActivity: 'Hoạt động gần đây',
    noWorkouts: 'Chưa có buổi tập nào',
    setsPerSession: 'Số hiệp mỗi buổi',
    noData: 'Chưa có dữ liệu',
    ratingTrend: 'Xu hướng đánh giá',
    language: 'Ngôn ngữ',
    workoutLabel: 'TẬP LUYỆN',
    markAsDone: '✓ Đánh dấu hoàn thành',
    workoutCompleted: '✓ Hoàn thành bài tập!',
    logWorkout: 'Ghi lại bài tập',
    adjustReps: 'Điều chỉnh số hiệp và số lần thực tế',
    saveWorkoutLog: 'Lưu nhật ký tập luyện',
    sets: 'HIỆP',
    reps: 'LẦN',
    currentStreak: 'Chuỗi hiện tại',
    totalExercises: 'Tổng bài tập',
    last8Weeks: '8 tuần qua',
    mostTrained: 'Nhóm cơ tập nhiều nhất',
    workoutHistory: 'LỊCH SỬ TẬP LUYỆN',
    alreadyHaveAccount: 'Đã có tài khoản？',
    addSchedule: 'Thêm lịch',
    editSchedule: 'Sửa lịch',
    addToSchedule: 'Thêm vào lịch',
    saveChanges: 'Lưu thay đổi',
    adding: 'Đang thêm...',
    saving: 'Đang lưu...',
    manual: 'Thủ công',
    edit: 'Sửa',
    delete: 'Xóa',
    deleting: '...',
    goExercise: 'Bắt đầu tập',
    exercisesCount: 'bài tập',
    title: 'TIÊU ĐỀ',
    time: 'THỜI GIAN',
    optionalNotes: 'Ghi chú tùy chọn',
    classWorkAppointment: 'Lớp học, công việc, cuộc hẹn...',
    workoutLockedTitle: 'Bài tập hôm nay đã khóa',
    workoutLockedBody: 'Bạn đã hoàn thành bài tập này, nên FitTokens được bảo vệ đến ngày tập tiếp theo.',
    todayWorkoutOnlyTitle: 'Chỉ bài tập hôm nay',
    todayWorkoutOnlyBody: 'FitTokens chỉ nhận được từ ngày hiện tại, các ngày khác chỉ để xem trước.',
    todayOnly: 'Chỉ hôm nay',
    checkingWorkout: 'ĐANG KIỂM TRA BÀI TẬP',
    workoutAlreadyComplete: 'Bài tập đã hoàn thành',
    workoutAlreadyCompleteBody: 'Ngày này đã khóa để giữ FitTokens công bằng. Hãy quay lại vào ngày tập tiếp theo.',
    noWorkoutLoaded: 'Chưa tải bài tập',
    noWorkoutLoadedBody: 'Bắt đầu từ tab Tập luyện để vào buổi tập.',
    backToWorkout: 'Quay lại Tập luyện',
    back: 'Quay lại',
    exercisesDone: 'BÀI TẬP ĐÃ XONG',
    restTime: 'Thời gian nghỉ',
    nowTraining: 'Đang tập',
    resting: 'Đang nghỉ...',
    pauseTimer: 'Tạm dừng giờ',
    resumeTimer: 'Tiếp tục giờ',
    exerciseLabel: 'BÀI TẬP',
    setLabel: 'HIỆP',
    ofLabel: 'TRÊN',
    repsThisSet: 'lần hiệp này',
    setsDone: 'hiệp đã xong',
    skipRest: 'Bỏ qua nghỉ',
    doneSet: 'Xong hiệp',
    finishWorkout: 'Hoàn thành bài tập',
    workoutCompleteTitle: 'Hoàn thành bài tập',
    workoutCompleteBody: 'Hôm nay bạn đã xuất hiện. Hãy giữ nhịp này.',
    streakLabel: 'CHUỖI',
    dayStreak: 'ngày liên tiếp',
    receiveFitToken: 'NHẬN FITTOKEN',
    continueLabel: 'Tiếp tục',
    lpHeroLine1: 'Lên kế hoạch thông minh hơn.',
    lpHeroLine2: 'Tập luyện chăm chỉ hơn.',
    lpHeroBody: 'Xây dựng kế hoạch tập luyện hàng tuần xung quanh bài tập, thiết bị và lịch trình của bạn — sau đó theo dõi mọi buổi tập, chuỗi và chuyến đi bộ.',
    lpSeeHow: 'Xem cách hoạt động',
    lpCheck1: 'Tạo kế hoạch 7 ngày tùy chỉnh với 80+ bài tập',
    lpCheck2: 'Theo dõi mọi buổi tập, chuỗi và ngày nghỉ',
    lpCheck3: 'Tích hợp theo dõi GPS đi bộ',
    lpCtaTitle: 'Kế hoạch tập luyện đầu tiên của bạn chỉ trong hai phút.',
    lpCtaBody: 'Không cần thẻ tín dụng. Chỉ cần thiết lập kế hoạch và bắt đầu tập luyện.',
    lpGetStartedFree: 'Bắt đầu miễn phí',
    setsCount: 'hiệp',
    showLess: 'Thu gọn',
    showAll: 'Xem tất cả {n} buổi tập',
    completeFirstWorkout: 'Hoàn thành buổi tập đầu tiên và tiến độ của bạn sẽ hiển thị ở đây.',
    goToSchedule: 'Đến Lịch trình',
    freeWindow: 'Khung giờ rảnh',
    classLabel: 'Lớp học',
    clearDayTitle: 'Ngày rảnh',
    clearDayHint: 'Chưa có lịch — nhấn + để thêm hoặc tận hưởng ngày nghỉ.',
    byTheNumbers: 'THỐNG KÊ',
    workoutsDone: 'Buổi tập đã xong',
    exercisesDoneLabel: 'Bài tập đã xong',
    bestStreakLabel: 'Chuỗi dài nhất',
    lifetimeLabel: 'tổng cộng',
    // Landing page specific
    lpFitnessScheduler: 'Lên lịch thể dục',
    lpPlanGenerator: 'Tạo kế hoạch',
    lpPlanLine1: 'Một câu lệnh.',
    lpPlanLine2: 'Kế hoạch cả tuần.',
    lpSessionPush: 'Ngày đẩy',
    lpSessionRest: 'Nghỉ',
    lpSessionLower: 'Ngày chân',
    lpSessionPushTime: 'T2 · 3 hiệp · 6 bài',
    lpSessionRestTime: 'T4 · Hồi phục',
    lpSessionLowerTime: 'T6 · 4 hiệp · 5 bài',
    lpStreakTitle: 'Chuỗi',
    lpDaysInARow: 'ngày liên tiếp',
    lpLongestRun: 'Kỷ lục của bạn: 31 ngày',
    lpProgressLabel: 'Tiến độ',
    lpLast10Days: '10 ngày qua',
    lpSessionsCompleted: 'buổi tập hoàn thành',
    lpVsLastWeek: '+12% so tuần trước',
    lpBuiltDifferent: 'Khác biệt',
    lpEveryTool: 'Mọi công cụ bạn cần.',
    lpNothingYouDont: 'Không có gì thừa.',
    lpStatExercises: 'bài tập trong thư viện',
    lpStatPlans: 'kế hoạch tập tùy chỉnh',
    lpStatHike: 'theo dõi hành trình',
    lpStatStreak: 'ngày chuỗi trung bình',
    lpStartToday: 'Bắt đầu hôm nay',
    lpFooterTagline: 'Sức khỏe của bạn, được lên lịch.',
    lpMarqueeItems: [
      'Tạo kế hoạch', 'Theo dõi chuỗi', 'Theo dõi GPS',
      'Thư viện bài tập', 'Báo cáo tiến độ', 'FitTokens',
      'Kế hoạch tập', '80+ bài tập', 'Đồng bộ Google',
      'Lịch sử tập', 'Quản lý nghỉ', 'Theo dõi thói quen',
    ],
    fitnessProfile: 'HỒ SƠ THỂ DỤC',
    earnings: 'THU NHẬP',
    goalLabel: 'Mục tiêu',
    experienceLevelLabel: 'Mức kinh nghiệm',
    bodyStats: 'Số đo cơ thể',
    deleteAccount: 'Xóa tài khoản',
    typeDeleteToConfirm: 'Nhập DELETE để xác nhận',
    temporaryAccount: 'Tài khoản tạm thời',
    yourProgressIsTemporary: 'Tiến độ của bạn là tạm thời',
    profileUpdated: 'Hồ sơ đã cập nhật',
    todayLabel: 'Hôm nay',
    lastWorkoutLabel: 'Lần tập gần nhất',
    noMuscleMapYet: 'Chưa có buổi tập nào — bản đồ cơ sẽ xuất hiện sau buổi tập đầu tiên.',
    primaryLabel: 'Chính',
    secondaryLabel: 'Phụ',
    lightLabel: 'Nhẹ',
    targetLabel: 'Trọng tâm',
    // Landing page — hero + sections
    lpEyebrow: 'Thể hình · Token · Thói quen',
    lpHead1: 'TẬP LUYỆN.',
    lpHead2: 'NHẬN',
    lpHead3: 'THƯỞNG.',
    lpPerWorkout: 'mỗi buổi tập hoàn thành',
    lpBaseNetwork: 'Mạng Base · EVM',
    lpStatExercisesLabel: 'Bài tập',
    lpStatPerSession: 'Mỗi buổi',
    lpStatHikeTracking: 'Theo dõi đi bộ',
    lpStatNoCard: 'Không cần thẻ',
    lpStatFree: 'Miễn phí',
    lpHowItWorks: 'Cách hoạt động',
    lpSteps: '3 bước',
    lpStepSchedule: 'Lên lịch',
    lpStepScheduleDesc: 'Đặt mục tiêu tập luyện hàng tuần. FitSched xây dựng kế hoạch của bạn ngay từ ngày đầu — không lãng phí ngày nghỉ — và điều chỉnh mỗi buổi theo sự phục hồi cơ, trạng thái và thiết bị sẵn có.',
    lpStepTrain: 'Tập luyện',
    lpStepTrainDesc: 'Làm theo buổi tập có hướng dẫn. Cảm biến chuyển động của thiết bị xác minh từng động tác để mỗi lần lặp đều nhận thưởng token đầy đủ.',
    lpStepEarn: 'Kiếm thưởng',
    lpStepEarnDesc: 'Hoàn thành buổi tập và kiếm FitToken — ghi nhận ngoài chuỗi, có thể rút về ví Base. Thưởng chuỗi còn cộng thêm.',
    lpFtPerCompleted: 'Mỗi buổi tập hoàn thành',
    lpFtTitle: 'Phần thưởng crypto thật cho nỗ lực thật.',
    lpFtBody: 'Mỗi buổi tập kiếm FitToken — ghi nhận ngoài chuỗi, có thể rút về ví Base. Thưởng chuỗi và hệ số xác minh nghĩa là tập càng chăm, kiếm càng nhiều.',
    lpRewardBase: 'Buổi tập cơ bản',
    lpRewardStreak: 'Thưởng chuỗi 7 ngày',
    lpRewardVerified: 'Đã xác minh chuyển động',
    lpFullReward: 'Thưởng đầy đủ',
    lpFeatSmartSched: 'Lên lịch thông minh',
    lpFeatSmartSchedDesc: 'Kế hoạch bắt đầu từ ngày bạn tham gia và điều chỉnh theo sự phục hồi và mục tiêu — chọn nhóm cơ khỏe nhất mỗi khi bạn muốn tập thêm.',
    lpFeatStreak: 'Hệ thống chuỗi',
    lpFeatStreakDesc: 'Chuỗi hàng ngày với ngày nghỉ không làm gián đoạn thành tích.',
    lpFeatGps: 'Theo dõi đi bộ GPS',
    lpFeatGpsDesc: 'Ghi lại các chuyến đi bộ ngoài trời với lộ trình GPS trực tiếp và dữ liệu độ cao.',
    lpFeatMotion: 'Xác minh chuyển động',
    lpFeatMotionDesc: 'Cảm biến thiết bị xác nhận từng lần lặp và trao thưởng token đầy đủ.',
    lpFeatAchieve: 'Thành tích',
    lpFeatAchieveDesc: 'Mở khóa huy hiệu và theo dõi kỷ lục cá nhân trên mọi nhóm cơ.',
    lpFeatCalSync: 'Đồng bộ lịch',
    lpFeatCalSyncDesc: 'Đẩy lịch tập của bạn trực tiếp sang Google Calendar.',
    lpCtaTitle1: 'Bắt đầu tập luyện',
    lpCtaTitle2: 'hôm nay.',
    lpFreeNoCard: 'Miễn phí · Không cần thẻ tín dụng',
    // Schedule — smart workout time
    smartTime: 'Chọn thông minh',
    pickWorkoutTime: 'Mấy giờ?',
    smartTimeHint: 'Dựa trên giờ bạn thường tập',
    // Landing page phone mockups
    lpmPushDay: 'Ngày đẩy',
    lpmChestShoulders: 'Ngực & Vai',
    lpmRecovery: 'Phục hồi',
    lpmSetsReps: '4 hiệp · 8 lần',
    lpmRest: 'NGHỈ · 00:48',
    lpmCompleteSet: 'Xong hiệp',
    lpmRecent: 'Gần đây',
    lpmThisWeek: 'tuần này',
    lpmLegDay: 'Ngày chân',
    lpmSquats: 'Squat & Deadlift',
    lpmTrail: 'Đường mòn ven sông',
    lpmYesterday: 'Hôm qua',
    lpm2days: '2 ngày trước',
    lpm3days: '3 ngày trước',
    lpmMuChest: 'Ngực',
    lpmMuBack: 'Lưng',
    lpmMuLegs: 'Chân',
    lpmMuArms: 'Tay',
    lpmMuCore: 'Lõi',
    // Forgot-password page
    fpRecovery: 'Khôi phục mật khẩu',
    fpForgotTitle: 'Quên mật khẩu?',
    fpEnterEmail: 'Nhập email của bạn và chúng tôi sẽ gửi liên kết đặt lại.',
    fpSendLink: 'Gửi liên kết đặt lại',
    fpSending: 'Đang gửi…',
    fpRememberIt: 'Nhớ ra rồi?',
    fpError: 'Đã xảy ra lỗi. Vui lòng thử lại.',
    fpGoogleTitle: 'Tài khoản Google',
    fpGoogleBody: 'được liên kết với một tài khoản Google. Bạn không cần mật khẩu — chỉ cần đăng nhập bằng Google.',
    fpCheckTitle: 'Kiểm tra email của bạn',
    fpCheckPre: 'Nếu',
    fpCheckPost: 'có tài khoản FitSched, bạn sẽ sớm nhận được liên kết đặt lại. Liên kết hết hạn sau 1 giờ.',
    fpDidntGet: 'Không nhận được? Kiểm tra thư mục spam hoặc',
    fpTryAgain: 'thử lại',
    fpBackSignin: 'Quay lại đăng nhập',
    // Auth pages (login + register)
    authIncorrect: 'Email hoặc mật khẩu không đúng',
    authGuestError: 'Không thể bắt đầu phiên khách. Vui lòng thử lại.',
    authSigningIn: 'Đang đăng nhập…',
    regEmailTaken: 'Email đã được đăng ký hoặc mật khẩu quá yếu',
    regNamePlaceholder: 'Tên của bạn',
    regPwPlaceholder: 'Tối thiểu 8 ký tự',
    authAgreePre: 'Tôi đã đọc và đồng ý với',
    termsOfService: 'Điều khoản dịch vụ',
    privacyPolicy: 'Chính sách bảo mật',
    andLabel: 'và',
    authGoogleAgree: 'Bằng việc tiếp tục với Google, bạn đồng ý với',
    termsShort: 'Điều khoản',
    // Settings page
    setFtBalance: 'Số dư FitToken',
    setEarnedFrom: 'Kiếm từ các buổi tập',
    setWithdraw: 'Rút',
    setGoogleCal: 'Google Calendar',
    setCalSub: 'Chỉ đọc · đồng bộ hàng đêm',
    setConnecting: 'Đang kết nối…',
    setOn: 'Bật',
    setOff: 'Tắt',
    setTapSync: 'Chạm để đồng bộ',
    setLastPrefix: 'Lần cuối',
    setGoalLose: 'Giảm cân',
    setGoalBuild: 'Tăng cơ',
    setGoalActive: 'Giữ năng động',
    setGoalEndurance: 'Sức bền',
    setLvlBeginner: 'Người mới',
    setLvlBeginnerSub: 'Mới bắt đầu',
    setLvlInter: 'Trung cấp',
    setLvlInterSub: 'Có chút kinh nghiệm',
    setLvlAdv: 'Nâng cao',
    setLvlAdvSub: 'Tập luyện kỹ',
    setHeight: 'Chiều cao',
    setWeight: 'Cân nặng',
    setEnvHome: 'Tại nhà',
    setEnvHomeSub: 'Tự trọng lượng',
    setEnvDbs: '+ Tạ',
    setEnvDbsSub: 'Tạ đơn',
    setEnvGym: 'Phòng gym',
    setEnvGymSub: 'Đầy đủ',
    setPerWeek: 'Số buổi mỗi tuần',
    setPerWeekUnit: '× / tuần',
    setExLibrary: 'Thư viện bài tập',
    setExLibrarySub: 'Duyệt và quản lý bài tập',
    setNotifications: 'Thông báo',
    setUpdating: 'Đang cập nhật…',
    setAppearance: 'Giao diện',
    setDarkMode: 'Chế độ tối',
    setLightMode: 'Chế độ sáng',
    setGuestBody: 'Tài khoản khách không được lưu. Tạo tài khoản miễn phí để giữ chuỗi, buổi tập và FitToken của bạn.',
    setCreateFree: 'Tạo tài khoản miễn phí',
    setDeleteTitle: 'Xóa tài khoản của bạn?',
    setDeleteBody: 'Thao tác này xóa vĩnh viễn hồ sơ, lịch sử tập, chuỗi và FitToken của bạn. Không thể hoàn tác.',
    setDeleting: 'Đang xóa…',
    justNow: 'Vừa xong',
    minsAgoSuffix: 'phút trước',
    hoursAgoSuffix: 'giờ trước',
    // Profile page
    profTitle: 'Hồ sơ',
    profTapName: 'Chạm để đặt tên',
    profSaving: 'đang lưu…',
    profJoined: 'Tham gia',
    profGuestCta: 'Tạo tài khoản miễn phí để lưu tiến độ →',
    profOf: '/',
    profSessions: 'buổi',
    profBody: 'Cơ thể',
    bmiUnder: 'Thiếu cân',
    bmiNormal: 'Bình thường',
    bmiOver: 'Thừa cân',
    bmiObese: 'Béo phì',
    profWeightTrend: 'Xu hướng cân nặng',
    profNoChange: 'Không đổi',
    profSinceFirst: 'từ lần đầu',
    profEntries: 'mục',
    profWeightLog: 'Nhật ký cân nặng',
    profWeightLogSub: 'Theo dõi cân nặng theo thời gian',
    profHikeLogs: 'Nhật ký đi bộ',
    profHikes: 'chuyến',
    profKmTotal: 'km tổng',
    profAchievements: 'Thành tích',
    profUnlocked: 'Đã mở',
    profNotUnlocked: 'Chưa mở khóa',
    // Muscle groups (shared)
    muAll: 'Tất cả',
    muChest: 'Ngực',
    muBack: 'Lưng',
    muLegs: 'Chân',
    muShoulders: 'Vai',
    muArms: 'Tay',
    muCore: 'Lõi',
    // History page
    hPrs: 'Kỷ lục',
    hKgMax: 'kg tối đa',
    hNotePlaceholder: 'Thêm ghi chú về buổi tập này…',
    hSaveNote: 'Lưu ghi chú',
    hTapNote: 'Chạm để thêm ghi chú…',
    hDeleting: 'Đang xóa…',
    hDeleteLog: 'Xóa nhật ký',
    hNoFilteredWorkouts: 'Chưa có buổi tập cho bộ lọc này',
    hExPerSession: 'Bài tập mỗi buổi',
    hPrEmpty: 'Hoàn thành buổi tập có tạ để theo dõi kỷ lục',
    hSessions: 'buổi',
    hReps: 'lần',
    hBest: 'TỐT NHẤT',
    hProgression: 'TIẾN TRIỂN',
    hRepsLabel: 'Số lần',
    muFullBody: 'Toàn thân',
    muCardio: 'Cardio',
    // Report / Progress page
    rStreakBonus: 'Thưởng chuỗi',
    rWorkout: 'Buổi tập',
    rBoostSuffix: '(2× tăng)',
    rDay: 'ngày',
    rDays: 'ngày',
    rPersonalBest: 'Kỷ lục cá nhân',
    rMusclesHit: 'Nhóm cơ đã tập',
    rRecovery: 'Phục hồi',
    rActivity: 'Hoạt động',
    rFtEarnings: 'Thu nhập FitToken',
    rFtEmpty: 'Hoàn thành một buổi tập để kiếm FitToken đầu tiên.',
    rCaloriesBurned: 'CALO ĐÃ ĐỐT (8 TUẦN)',
    rKcalTotal: 'kcal tổng',
    rCalories: 'Calo',
    rHikeStats: 'THỐNG KÊ ĐI BỘ',
    rHikes: 'Chuyến',
    rDistance: 'Quãng đường',
    rTime: 'Thời gian',
    rViewAllHikes: 'Xem tất cả chuyến đi bộ',
    rTotal: 'tổng',
    rSearchWorkouts: 'Tìm buổi tập…',
    rNoMatching: 'Không có buổi tập khớp',
    rLoadedToday: 'Đã tải cho hôm nay!',
    rLoading: 'Đang tải…',
    rRepeatToday: 'Lặp lại hôm nay',
    // Exercise descriptions
    descInclinePush: 'Chống đẩy thân thiện cho người mới dùng bề mặt cao.',
    descPushup: 'Động tác đẩy người rèn ngực, tam đầu, vai và lõi.',
    descShoulderTap: 'Chống đẩy rồi chạm vai luân phiên.',
    descDiamond: 'Chống đẩy tay hẹp nhắm tam đầu và ngực trong.',
    descTricepDip: 'Động tác hít xà kép cô lập tam đầu và ổn định vai.',
    descPullup: 'Kéo dọc nhắm xô, nhị đầu và lưng trên.',
    descBicepCurl: 'Động tác cô lập cho đỉnh nhị đầu và sức mạnh tay.',
    descSquat: 'Động tác phức hợp thân dưới cho đùi, mông và hông.',
    descLunge: 'Bài tập chân một bên cho thăng bằng và phát triển đùi.',
    descPlank: 'Giữ lõi đẳng trường xây dựng sự ổn định thân.',
    descBurpee: 'Động tác toàn thân kết hợp squat, chống đẩy và bật nhảy.',
    descLateralRaise: 'Động tác cô lập cho bề ngang vai giữa.',
    descRussianTwist: 'Động tác xoay lõi nhắm cơ liên sườn.',
    descMountainClimb: 'Bài tập lõi động có lợi ích cardio.',
    descDefault: 'Động tác phức hợp cho sức mạnh và sức bền.',
    // Workout + schedule
    wWeeklyGoal: 'Mục tiêu tuần',
    wComputing: 'Đang tính…',
    wMin: 'phút',
    wMedium: 'trung bình',
    wTemplates: 'Mẫu',
    wTemplateActive: 'Đang dùng mẫu —',
    wReset: 'Đặt lại',
    wTrainAgain: 'Tập lại',
    scBestWindow: 'Khung giờ tốt nhất',
    scOptimalWindow: 'Khung năng lượng tối ưu',
    scStart: 'Bắt đầu',
    scStartArrow: 'Bắt đầu →',
    scTodayOnly: 'Chỉ hôm nay',
    scMorning: 'Buổi sáng',
    scMorningSub: 'Trước trưa',
    scAfternoon: 'Buổi chiều',
    scAfternoonSub: '12 – 17h',
    scEvening: 'Buổi tối',
    scEveningSub: 'Sau 17h',
    scScheduleGroup: 'Lịch',
    scMinShort: 'phút',
    // Exercise session
    exTodaysWorkout: 'BUỔI TẬP HÔM NAY',
    exOneShot: 'Chỉ một lần — thoát là mất FitToken hôm nay',
    exLetsGo: 'Bắt đầu',
    exTrackTitle: 'Theo dõi chuyển động',
    exTrackBody: 'FitSched dùng cảm biến chuyển động của thiết bị để xác minh buổi tập và trao FitToken đầy đủ. Dữ liệu không rời khỏi thiết bị của bạn.',
    exEnableMotion: 'Bật theo dõi chuyển động',
    exSkip50: 'Bỏ qua — nhận 50% FitToken',
    exTodaysWorkoutLower: 'Buổi tập hôm nay',
    exVerified: 'ĐÃ XÁC MINH',
    exUnverified: 'CHƯA XÁC MINH',
    exSwap: 'Đổi',
    exLast: 'Lần trước:',
    exRound: 'Vòng',
    exOf: '/',
    exSet: 'Hiệp',
    exAllSetsDone: 'Đã xong tất cả hiệp',
    exCompleteSet: 'Hoàn thành hiệp',
    exCamAuto: 'Đếm rep bằng camera',
    exCamBeta: 'Beta',
    exCamStarting: 'Đang bật camera…',
    exCamDenied: 'Không dùng được camera — kiểm tra quyền rồi thử lại.',
    exCamTip: 'Dựng điện thoại sao cho thấy toàn thân',
    exCamStop: 'Tắt camera',
    exOfLower: '/',
    exUpNext: 'Tiếp theo',
    exSwapHeader: 'ĐỔI',
    exNoAlts: 'Không có bài thay thế',
    exQuitTitle: 'Thoát buổi tập?',
    exQuitPre: 'Bạn chỉ có',
    exQuitBold: 'một cơ hội mỗi ngày',
    exQuitPost: '. Thoát bây giờ nghĩa là không có FitToken hôm nay và không vào lại đến mai.',
    exKeepGoing: 'Tiếp tục',
    exQuitLose: 'Thoát & mất',
    exRest: 'Nghỉ',
    exSec: 'giây',
    exSkip: 'Bỏ qua',
    exStatTime: 'Thời gian',
    exStatExercises: 'Bài tập',
    exStatSets: 'Hiệp',
    exStatReps: 'Lần',
    exEstCalories: 'CALO ƯỚC TÍNH',
    exYouReceived: 'BẠN NHẬN ĐƯỢC',
    exPartialReward: 'Thưởng một phần — lần sau chạm Xác minh để nhận đủ +1.0 FT',
    exNoTokens: 'Không có token — buổi tập quá nhanh để xác minh',
    exPersonalRecords: 'KỶ LỤC CÁ NHÂN',
    exWas: 'trước là',
    exFirstTime: 'Lần đầu ghi nhận!',
    exHowFeel: 'CẢM THẤY THẾ NÀO?',
    exFbEasy: 'Quá dễ',
    exFbEasyD: 'Tăng thử thách',
    exFbJust: 'Vừa phải',
    exFbJustD: 'Giữ nhịp',
    exFbHard: 'Quá khó',
    exFbHardD: 'Giảm cường độ',
    exFbSaved: 'Đã lưu phản hồi cho gợi ý sau này.',
    exSessionNotes: 'GHI CHÚ BUỔI TẬP',
    exNotePlaceholder: 'Buổi tập thế nào? Kỷ lục? Điều cần nhớ…',
    exSaved: 'Đã lưu',
    exAchUnlocked: 'MỞ KHÓA THÀNH TÍCH',
    exExitedTitle: 'Bạn đã thoát buổi tập hôm nay',
    exExitedBody: 'Quay lại ngày mai cho buổi tập mới và phần thưởng FitToken đầy đủ.',
    exGoExercise: 'Bắt đầu tập',
    exToday: 'hôm nay',
    exYesterday: 'hôm qua',
    exDaysAgo: ' ngày trước',
    // Hike page
    hkLogs: 'Nhật ký',
    hkHikes: 'chuyến',
    hkPendingSync: 'chờ đồng bộ',
    hkSavedOffline: 'Đã lưu ngoại tuyến — sẽ đồng bộ khi có mạng',
    hkFtEarned: 'FT đã nhận',
    hkKmExcluded: 'km bị loại — tốc độ quá cao so với đi bộ',
    hkSaveTitle: 'Lưu chuyến đi bộ',
    hkTrailName: 'Tên đường mòn',
    hkTrailPlaceholder: 'vd. Đồi Bukit Timah',
    hkLocation: 'Địa điểm',
    hkLocationPlaceholder: 'vd. Khu bảo tồn Bukit Timah',
    hkNotes: 'Ghi chú',
    hkNotesPlaceholder: 'Thế nào?',
    hkSaving: 'Đang lưu…',
    hkSaveHike: 'Lưu chuyến đi',
    hkHikeLogs: 'Nhật ký đi bộ',
    hkChipHikes: 'Chuyến',
    hkChipDistance: 'Quãng đường',
    hkChipElevation: 'Độ cao',
    hkChipTime: 'Thời gian',
    hkLoading: 'Đang tải…',
    hkNoHikes: 'Chưa có chuyến đi bộ nào.',
    // Weight page
    wtGoal: 'Mục tiêu:',
    wtLogWeight: 'Ghi cân nặng',
    wtSetGoalTitle: 'Đặt mục tiêu cân nặng',
    wtGoalDesc: 'Đặt cân nặng mục tiêu để theo dõi tiến độ của bạn.',
    wtEg: 'vd.',
    wtClearGoal: 'Xóa mục tiêu',
    wtSetGoal: 'Đặt mục tiêu',
    wtNewEntry: 'MỤC MỚI',
    wtSave: 'Lưu',
    wtNotePlaceholder: 'Ghi chú tùy chọn (vd. sau khi chạy)',
    wtLastLogged: 'Ghi gần nhất',
    wtVsPrev: 'so lần trước',
    wtToGo: 'còn lại',
    wtReached: 'đã đạt',
    wtGoalShort: 'Mục tiêu',
    wtNoEntries: 'Chưa có mục nào',
    wtEmptyHint: 'Chạm "Ghi cân nặng" để bắt đầu theo dõi tiến độ.',
    wtEntry: 'mục',
    // Withdrawal page
    wdSubtitle: 'Kiếm FIT bằng cách tập luyện. Rút về ví Base của bạn.',
    wdYourWallet: 'Ví của bạn',
    wdBaseNetwork: 'Mạng Base (EVM)',
    wdChange: 'Đổi',
    wdSaved: 'Đã lưu',
    wdEnterNew: 'Nhập địa chỉ ví Base mới:',
    wdPasteAddr: 'Dán địa chỉ ví Base để nhận FIT khi rút:',
    wdSave: 'Lưu',
    wdWalletHint: 'Chỉ hỗ trợ địa chỉ Base (chainId 8453). Không bao giờ chia sẻ khóa riêng tư của bạn.',
    wdFtBalance: 'Số dư FitToken',
    wdLiveOnBase: 'Đang hoạt động trên Base',
    wdOffchain: 'Ngoài chuỗi · Sắp ra mắt trên Base',
    wdLive: 'TRỰC TIẾP',
    wdClaimedExcl: 'đã nhận!',
    wdTokensSent: 'Token đã gửi đến ví Base của bạn.',
    wdOnchainBalance: 'Số dư trên chuỗi:',
    wdViewBasescan: 'Xem trên Basescan',
    wdClaimableBalance: 'Số dư có thể rút',
    wdAlreadyClaimed: 'đã nhận',
    wdTotalEarned: 'TỔNG KIẾM',
    wdOnChain: 'TRÊN CHUỖI',
    wdClaimedLabel: 'ĐÃ NHẬN',
    wdProgressMin: 'Tiến độ đến mức rút tối thiểu',
    wdMoreToGo: 'FIT nữa để rút',
    wdHowEarn: 'Cách kiếm',
    wdEarn1: 'Hoàn thành buổi tập',
    wdEarn1d: '+1.00 FT mỗi buổi',
    wdEarn2: 'Thưởng chuỗi',
    wdEarn2d: 'Thêm tối đa +0.20 FT',
    wdEarn3: 'Điểm xác minh',
    wdEarn3d: 'Điểm tối đa = thưởng đầy đủ',
    wdClaimHistory: 'Lịch sử nhận',
    wdRecentEarnings: 'Thu nhập gần đây',
    wdActionWithdraw: 'rút FIT',
    wdActionWallet: 'đổi ví của bạn',
    wdReasonWorkout: 'Đã hoàn thành buổi tập',
    wdSetWalletFirst: 'Đặt địa chỉ ví trước',
    wdNoFitYet: 'Chưa có FIT để rút',
    wdNeedMinPre: 'Cần tối thiểu',
    wdNeedMinPost: 'FIT',
    wdClaim: 'Rút',
    wdLaunchingSoon: 'SẮP RA MẮT',
    wdClaiming: 'Đang rút…',
    wdClaimedBtn: 'Đã rút',
    wdLaunchNote1: 'Hợp đồng FitToken chưa hoạt động trên Base. Số dư của bạn an toàn và có thể rút khi ra mắt.',
    wdLaunchNote2pre: 'Số',
    wdLaunchNote2post: 'FIT của bạn an toàn và có thể rút khi hợp đồng hoạt động trên Base.',
    wdErrGeneric: 'Đã xảy ra lỗi. Vui lòng thử lại.',
    wdErrNetwork: 'Lỗi mạng — vui lòng thử lại',
    // Exercise library
    exLibEdit: 'Sửa bài tập',
    eqBodyweight: 'Tự trọng lượng',
    eqDumbbells: 'Tạ đơn',
    eqBarbell: 'Tạ đòn',
    eqMachine: 'Máy',
    eqCables: 'Cáp',
    eqBands: 'Dây kháng lực',
    eqKettlebell: 'Tạ ấm',
    workoutNames: {
      'Chest & Triceps':  'Ngực & Cơ tam đầu',
      'Back & Biceps':    'Lưng & Cơ nhị đầu',
      'Shoulders & Core': 'Vai & Cơ trung tâm',
      'Arms & Core':      'Tay & Cơ trung tâm',
      'Legs':             'Chân',
      'Full Body':        'Toàn thân',
      'Rest':             'Nghỉ',
    },
  }
}

type TranslationKey = keyof typeof translations.EN

const LanguageContext = createContext<{
  language: Lang
  t: typeof translations.EN
  cycleLanguage: () => void
  changeLanguage: (lang: Lang) => void
}>({
  language: 'EN',
  t: translations.EN,
  cycleLanguage: () => {},
  changeLanguage: () => {}
})

export function LanguageProvider({
  children
}: {
  children: React.ReactNode
}) {
  const [language, setLanguage] = useState<Lang>('EN')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Lang || 'EN'
    setLanguage(saved)
  }, [])

  const cycleLanguage = () => {
    const langs: Lang[] = ['EN', 'CN', 'JP', 'VI']
    const next = langs[(langs.indexOf(language) + 1) % langs.length]
    setLanguage(next)
    localStorage.setItem('language', next)
    document.documentElement.setAttribute('lang', next.toLowerCase())
  }

  const changeLanguage = (lang: Lang) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
    document.documentElement.setAttribute('lang', lang.toLowerCase())
  }

  return (
    <LanguageContext.Provider value={{
      language,
      t: translations[language],
      cycleLanguage,
      changeLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
